In [1]:
from pathlib import Path
import pandas as pd
import re

# Define project folders
text_folder = Path("../data/extracted_text")
processed_folder = Path("../data/processed")
keyword_file = Path("../data/keyword_dictionary.csv")
company_file = Path("../data/company_master_list.csv")

# Check extracted text files
text_files = sorted(text_folder.glob("*.txt"))

print(f"Extracted text files found: {len(text_files)}")

for file in text_files:
    print(file.name)

Extracted text files found: 20
001_barclays_plc_annual_report_2025.txt
002_hsbc_holdings_plc_annual_report_2025.txt
003_lloyds_banking_group_plc_annual_report_2025.txt
004_natwest_group_plc_annual_report_2025.txt
005_standard_chartered_plc_annual_report_2025.txt
006_aviva_plc_annual_report_2025.txt
007_legal_and_general_group_plc_annual_report_2025.txt
008_m_and_g_plc_annual_report_2025.txt
009_admiral_group_plc_annual_report_2025.txt
010_aj_bell_plc_annual_report_2025.txt
011_ig_group_holdings_plc_annual_report_2025.txt
012_cmc_markets_plc_annual_report_2025.txt
013_integrafin_holdings_plc_annual_report_2025.txt
014_wise_plc_annual_report_2025.txt
015_cab_payments_holdings_plc_annual_report_2025.txt
016_funding_circle_holdings_plc_annual_report_2025.txt
017_boku_inc_annual_report_2025.txt
018_paypoint_plc_annual_report_2025.txt
019_london_stock_exchange_group_plc_annual_report_2025.txt
020_experian_plc_annual_report_2025.txt

In [2]:
keyword_data = [
    
    # AI and related technologies
    ["AI and related technologies", "artificial intelligence", "artificial intelligence", "Direct reference to AI"],
    ["AI and related technologies", "AI", "AI", "Direct acronym reference to artificial intelligence"],
    ["AI and related technologies", "machine learning", "machine learning", "Specific AI-related technique"],
    ["AI and related technologies", "algorithm", "algorithm", "Algorithmic systems or decision processes"],
    ["AI and related technologies", "automation", "automation", "Automated processes linked to digital operations"],
    ["AI and related technologies", "generative AI", "generative AI", "Emerging AI technology"],
    ["AI and related technologies", "large language model", "large language model", "Specific generative AI technology"],
    ["AI and related technologies", "LLM", "LLM", "Acronym for large language model"],

    # Data and analytics
    ["Data and analytics", "data analytics", "data analytics", "Evidence of data-driven operations"],
    ["Data and analytics", "advanced analytics", "advanced analytics", "Evidence of analytical capability"],
    ["Data and analytics", "predictive analytics", "predictive analytics", "Predictive decision-support capability"],
    ["Data and analytics", "data science", "data science", "Technical data capability"],
    ["Data and analytics", "digital transformation", "digital transformation", "Wider digital change context"],

    # Governance and accountability
    ["Governance and accountability", "governance", "governance", "General governance reference"],
    ["Governance and accountability", "accountability", "accountability", "Accountability in decision-making"],
    ["Governance and accountability", "oversight", "oversight", "Oversight of technology or risk"],
    ["Governance and accountability", "responsible AI", "responsible AI", "Explicit responsible AI governance"],
    ["Governance and accountability", "ethical AI", "ethical AI", "Explicit AI ethics disclosure"],
    ["Governance and accountability", "AI ethics", "AI ethics", "Explicit AI ethics disclosure"],
    ["Governance and accountability", "model risk", "model risk", "Risk management of models"],

    # Transparency and explainability
    ["Transparency and explainability", "transparency", "transparency", "Transparency disclosure"],
    ["Transparency and explainability", "explainability", "explainability", "Explainability of systems or models"],
    ["Transparency and explainability", "explainable AI", "explainable AI", "Specific explainable AI reference"],
    ["Transparency and explainability", "interpretability", "interpretability", "Model interpretability reference"],

    # Human oversight and decision-making
    ["Human oversight", "human oversight", "human oversight", "Human control over automated systems"],
    ["Human oversight", "human review", "human review", "Manual review of decisions"],
    ["Human oversight", "human-in-the-loop", "human-in-the-loop", "Human involvement in AI systems"],
    ["Human oversight", "automated decision-making", "automated decision-making", "Automated decision processes"],
    ["Human oversight", "decision support", "decision support", "Technology supporting human decisions"],

    # Fairness, bias and ethics
    ["Fairness, bias and ethics", "bias", "bias", "Potential bias in models or decisions"],
    ["Fairness, bias and ethics", "fairness", "fairness", "Fairness in decisions or systems"],
    ["Fairness, bias and ethics", "discrimination", "discrimination", "Potential unfair treatment"],
    ["Fairness, bias and ethics", "ethics", "ethics", "General ethics reference"],

    # Risk, regulation and protection
    ["Risk and regulation", "risk management", "risk management", "Technology risk management"],
    ["Risk and regulation", "regulatory compliance", "regulatory compliance", "Regulatory compliance disclosure"],
    ["Risk and regulation", "data protection", "data protection", "Protection of personal or customer data"],
    ["Risk and regulation", "privacy", "privacy", "Privacy-related disclosure"],
    ["Risk and regulation", "cybersecurity", "cybersecurity", "Technology and cyber risk disclosure"]
]

keyword_dictionary = pd.DataFrame(
    keyword_data,
    columns=[
        "category",
        "keyword",
        "search_variant",
        "reason_for_inclusion"
    ]
)

keyword_dictionary.to_csv(
    keyword_file,
    index=False
)

print(f"Keyword dictionary saved to: {keyword_file}")
print(f"Number of keywords: {len(keyword_dictionary)}")

keyword_dictionary

Keyword dictionary saved to: ..\data\keyword_dictionary.csv
Number of keywords: 38

,category,keyword,search_variant,reason_for_inclusion
0,AI and related technologies,artificial intelligence,artificial intelligence,Direct reference to AI
1,AI and related technologies,AI,AI,Direct acronym reference to artificial intelli...
2,AI and related technologies,machine learning,machine learning,Specific AI-related technique
3,AI and related technologies,algorithm,algorithm,Algorithmic systems or decision processes
4,AI and related technologies,automation,automation,Automated processes linked to digital operations
5,AI and related technologies,generative AI,generative AI,Emerging AI technology
6,AI and related technologies,large language model,large language model,Specific generative AI technology
7,AI and related technologies,LLM,LLM,Acronym for large language model
8,Data and analytics,data analytics,data analytics,Evidence of data-driven operations
9,Data and analytics,advanced analytics,advanced analytics,Evidence of analytical capability
10,Data and analytics,predictive analytics,predictive analytics,Predictive decision-support capability
11,Data and analytics,data science,data science,Technical data capability
12,Data and analytics,digital transformation,digital transformation,Wider digital change context
13,Governance and accountability,governance,governance,General governance reference
14,Governance and accountability,accountability,accountability,Accountability in decision-making
15,Governance and accountability,oversight,oversight,Oversight of technology or risk
16,Governance and accountability,responsible AI,responsible AI,Explicit responsible AI governance
17,Governance and accountability,ethical AI,ethical AI,Explicit AI ethics disclosure
18,Governance and accountability,AI ethics,AI ethics,Explicit AI ethics disclosure
19,Governance and accountability,model risk,model risk,Risk management of models
20,Transparency and explainability,transparency,transparency,Transparency disclosure
21,Transparency and explainability,explainability,explainability,Explainability of systems or models
22,Transparency and explainability,explainable AI,explainable AI,Specific explainable AI reference
23,Transparency and explainability,interpretability,interpretability,Model interpretability reference
24,Human oversight,human oversight,human oversight,Human control over automated systems
25,Human oversight,human review,human review,Manual review of decisions
26,Human oversight,human-in-the-loop,human-in-the-loop,Human involvement in AI systems
27,Human oversight,automated decision-making,automated decision-making,Automated decision processes
28,Human oversight,decision support,decision support,Technology supporting human decisions
29,"Fairness, bias and ethics",bias,bias,Potential bias in models or decisions
30,"Fairness, bias and ethics",fairness,fairness,Fairness in decisions or systems
31,"Fairness, bias and ethics",discrimination,discrimination,Potential unfair treatment
32,"Fairness, bias and ethics",ethics,ethics,General ethics reference
33,Risk and regulation,risk management,risk management,Technology risk management
34,Risk and regulation,regulatory compliance,regulatory compliance,Regulatory compliance disclosure
35,Risk and regulation,data protection,data protection,Protection of personal or customer data
36,Risk and regulation,privacy,privacy,Privacy-related disclosure
37,Risk and regulation,cybersecurity,cybersecurity,Technology and cyber risk disclosure

In [3]:
def split_text_into_pages(full_text):
    """
    Splits extracted report text using the page markers created
    in the text extraction notebook.
    """
    
    page_sections = re.split(
        r"===== PAGE (\d+) =====",
        full_text
    )
    
    pages = []
    
    for index in range(1, len(page_sections), 2):
        page_number = int(page_sections[index])
        page_text = page_sections[index + 1]
        pages.append((page_number, page_text))
        
    return pages


def get_context(text, start, end, window=220):
    """
    Returns a short text extract around a matched keyword.
    """
    
    context_start = max(0, start - window)
    context_end = min(len(text), end + window)
    
    context = text[context_start:context_end]
    
    # Clean excess spacing
    context = re.sub(r"\s+", " ", context).strip()
    
    return context


# Short acronyms are matched case-sensitively. Page-level extraction from PDFs
# routinely splits words across column and line breaks, so a case-insensitive
# search finds bare lowercase fragments of ordinary words (for example
# "sustainability" extracted as "sust ai nabilit") and counts them as AI
# disclosures. The letter-boundary lookarounds alone cannot prevent this,
# because the surrounding characters are whitespace rather than letters.

CASE_SENSITIVE_VARIANTS = {"AI", "LLM"}


def build_keyword_pattern(keyword):
    """
    Builds a search pattern.
    Uses stricter boundaries for short acronyms such as AI and LLM.
    """
    
    escaped_keyword = re.escape(keyword)
    
    if keyword in CASE_SENSITIVE_VARIANTS:
        return rf"(?<![A-Za-z]){escaped_keyword}(?![A-Za-z])"
    
    return rf"\b{escaped_keyword}\b"


# Load dictionary and company master file

keyword_dictionary = pd.read_csv(keyword_file)
company_master = pd.read_csv(company_file, dtype={"company_id": str})

all_mentions = []

# Search each extracted report text file

for text_file in text_files:
    
    company_id = text_file.name[:3]
    
    company_row = company_master[
        company_master["company_id"] == company_id
    ]
    
    if not company_row.empty:
        company_name = company_row.iloc[0]["company_name"]
        report_year = company_row.iloc[0]["annual_report_year"]
    else:
        company_name = ""
        report_year = ""
    
    full_text = text_file.read_text(
        encoding="utf-8",
        errors="ignore"
    )
    
    pages = split_text_into_pages(full_text)
    
    for _, keyword_row in keyword_dictionary.iterrows():
        
        category = keyword_row["category"]
        keyword = keyword_row["keyword"]
        search_variant = keyword_row["search_variant"]
        
        pattern = build_keyword_pattern(search_variant)

        # Acronyms are matched case-sensitively; all other terms remain
        # case-insensitive so that sentence-initial capitals still match.
        search_flags = (
            0 if search_variant in CASE_SENSITIVE_VARIANTS else re.IGNORECASE
        )
        
        for page_number, page_text in pages:
            
            for match in re.finditer(
                pattern,
                page_text,
                flags=search_flags
            ):
                
                context = get_context(
                    page_text,
                    match.start(),
                    match.end()
                )
                
                all_mentions.append({
                    "company_id": company_id,
                    "company_name": company_name,
                    "report_year": report_year,
                    "source_file": text_file.name,
                    "category": category,
                    "keyword": keyword,
                    "search_variant": search_variant,
                    "page_number": page_number,
                    "matched_text": match.group(0),
                    "context": context
                })

keyword_mentions = pd.DataFrame(all_mentions)

output_file = processed_folder / "ai_keyword_mentions.csv"

keyword_mentions.to_csv(
    output_file,
    index=False
)

print(f"Total keyword mentions found: {len(keyword_mentions)}")
print(f"Results saved to: {output_file}")

keyword_mentions.head(20)

Total keyword mentions found: 13113
Results saved to: ..\data\processed\ai_keyword_mentions.csv

,company_id,company_name,report_year,source_file,category,keyword,search_variant,page_number,matched_text,context
0,001,Barclays plc,2025,001_barclays_plc_annual_report_2025.txt,AI and related technologies,artificial intelligence,artificial intelligence,42,artificial intelligence,class customer experience; and delivering best...
1,001,Barclays plc,2025,001_barclays_plc_annual_report_2025.txt,AI and related technologies,artificial intelligence,artificial intelligence,62,artificial intelligence,ds (including business or operations; the use ...
2,001,Barclays plc,2025,001_barclays_plc_annual_report_2025.txt,AI and related technologies,artificial intelligence,artificial intelligence,109,artificial intelligence,ustainability reporting standards (including b...
3,001,Barclays plc,2025,001_barclays_plc_annual_report_2025.txt,AI and related technologies,artificial intelligence,artificial intelligence,183,Artificial Intelligence,"al Control, and standardisation of cost report..."
4,001,Barclays plc,2025,001_barclays_plc_annual_report_2025.txt,AI and related technologies,artificial intelligence,artificial intelligence,232,artificial intelligence,ordinary shareholders. legacy businesses; and ...
5,001,Barclays plc,2025,001_barclays_plc_annual_report_2025.txt,AI and related technologies,artificial intelligence,artificial intelligence,233,Artificial Intelligence,ntravention Order Removing Barriers to America...
6,001,Barclays plc,2025,001_barclays_plc_annual_report_2025.txt,AI and related technologies,artificial intelligence,artificial intelligence,233,artificial intelligence,"risks relating to AI technologies.development,..."
7,001,Barclays plc,2025,001_barclays_plc_annual_report_2025.txt,AI and related technologies,artificial intelligence,artificial intelligence,233,Artificial Intelligence,anner or These include the California Transpar...
8,001,Barclays plc,2025,001_barclays_plc_annual_report_2025.txt,AI and related technologies,artificial intelligence,artificial intelligence,233,Artificial Intelligence,-out of new AI tools in Frontier Artificial In...
9,001,Barclays plc,2025,001_barclays_plc_annual_report_2025.txt,AI and related technologies,artificial intelligence,artificial intelligence,238,artificial intelligence,“Evolving landscape with respect to The Group ...
10,001,Barclays plc,2025,001_barclays_plc_annual_report_2025.txt,AI and related technologies,artificial intelligence,artificial intelligence,238,artificial intelligence,artificial intelligence (including generative ...
11,001,Barclays plc,2025,001_barclays_plc_annual_report_2025.txt,AI and related technologies,artificial intelligence,artificial intelligence,239,artificial intelligence,"tigation, intelligence (including generative a..."
12,001,Barclays plc,2025,001_barclays_plc_annual_report_2025.txt,AI and related technologies,artificial intelligence,artificial intelligence,240,artificial intelligence,"labour, immigration and related policies in in..."
13,001,Barclays plc,2025,001_barclays_plc_annual_report_2025.txt,AI and related technologies,artificial intelligence,artificial intelligence,253,Artificial Intelligence,local entity Board Risk Committee(s). firm. en...
14,001,Barclays plc,2025,001_barclays_plc_annual_report_2025.txt,AI and related technologies,artificial intelligence,artificial intelligence,342,Artificial Intelligence,work principles and design. financing) - to a ...
15,001,Barclays plc,2025,001_barclays_plc_annual_report_2025.txt,AI and related technologies,artificial intelligence,artificial intelligence,355,Artificial intelligence,uch systems do not undertakings for breaches o...
16,001,Barclays plc,2025,001_barclays_plc_annual_report_2025.txt,AI and related technologies,artificial intelligence,artificial intelligence,355,artificial intelligence,ng adopting new laws direct marketing in the U...
17,001,Barclays plc,2025,001_barclays_plc_annual_report_2025.txt,AI and related technologies,artificial intelligence,artificial intelligence,355,Artificial Intelligence,"uding 2025, President Trump signed an investig..."
18,001,Barclays plc,2025,001_barclays_plc_annual_report_2025.txt,AI and related technologies,artificial intelligence,artificial intelligence,382,Artificial Intelligence,al period which requires a tender 31 December ...
19,001,Barclays plc,2025,001_barclays_plc_annual_report_2025.txt,AI and related technologies,artificial intelligence,artificial intelligence,493,artificial intelligence,"riting, but also may be made verbally by busin..."

In [4]:
# Validation audit: effect of case-sensitive acronym matching
#
# Re-runs the permissive (case-insensitive) rule for the acronyms only, and
# records every match the stricter rule excludes. This turns the false-positive
# rate into a reportable number for the methodology chapter rather than an
# anecdote, and preserves the excluded extracts as evidence.

false_positive_rows = []

for text_file in text_files:

    company_id = text_file.name[:3]

    company_row = company_master[
        company_master["company_id"] == company_id
    ]

    company_name = (
        company_row.iloc[0]["company_name"]
        if not company_row.empty
        else ""
    )

    full_text = text_file.read_text(
        encoding="utf-8",
        errors="ignore"
    )

    for page_number, page_text in split_text_into_pages(full_text):

        for variant in sorted(CASE_SENSITIVE_VARIANTS):

            pattern = build_keyword_pattern(variant)

            for match in re.finditer(
                pattern,
                page_text,
                flags=re.IGNORECASE
            ):

                # Kept by the permissive rule, excluded by the strict one
                if match.group(0) != variant:

                    false_positive_rows.append({
                        "company_id": company_id,
                        "company_name": company_name,
                        "search_variant": variant,
                        "page_number": page_number,
                        "matched_text": match.group(0),
                        "context": get_context(
                            page_text,
                            match.start(),
                            match.end(),
                            window=110
                        )
                    })

acronym_false_positives = pd.DataFrame(false_positive_rows)

acronym_false_positives.to_csv(
    processed_folder / "acronym_case_false_positives.csv",
    index=False
)

affected_firms = (
    acronym_false_positives["company_id"].nunique()
    if len(acronym_false_positives) > 0
    else 0
)

print(f"Acronym matches excluded by case-sensitive rule: {len(acronym_false_positives)}")
print(f"Firms affected: {affected_firms} of {len(text_files)}")
print(f"Retained AI-related mentions: {len(keyword_mentions)}")

acronym_false_positives

Acronym matches excluded by case-sensitive rule: 4
Firms affected: 3 of 20
Retained AI-related mentions: 13113

,company_id,company_name,search_variant,page_number,matched_text,context
0,002,HSBC Holdings plc,AI,32,ai,"US and China, including cross-border and AI ar..."
1,002,HSBC Holdings plc,AI,61,ai,sonal customers (IWPB) team corporate customer...
2,005,Standard Chartered plc,AI,30,ai,ly Ch ai 19% ns sets lAs
3,012,CMC Markets plc,AI,32,ai,rs aligns with several United Ourthree sust ai...

In [5]:
# Create output folder for evidence tables

evidence_folder = Path("../outputs/evidence_tables")
evidence_folder.mkdir(parents=True, exist_ok=True)

# Summary 1: keyword mentions by company and category

company_category_summary = (
    keyword_mentions
    .groupby(["company_id", "company_name", "category"])
    .agg(
        mention_count=("keyword", "count"),
        unique_pages=("page_number", "nunique"),
        keywords_found=("keyword", lambda x: ", ".join(sorted(set(x))))
    )
    .reset_index()
)

company_category_summary.to_csv(
    evidence_folder / "company_category_keyword_summary.csv",
    index=False
)

company_category_summary.head(30)

,company_id,company_name,category,mention_count,unique_pages,keywords_found
0,001,Barclays plc,AI and related technologies,231,54,"AI, artificial intelligence, automation, gener..."
1,001,Barclays plc,Data and analytics,10,6,"data analytics, digital transformation"
2,001,Barclays plc,"Fairness, bias and ethics",20,11,"bias, discrimination, ethics, fairness"
3,001,Barclays plc,Governance and accountability,927,491,"accountability, ethical AI, governance, model ..."
4,001,Barclays plc,Human oversight,1,1,human oversight
5,001,Barclays plc,Risk and regulation,358,118,"cybersecurity, data protection, privacy, regul..."
6,001,Barclays plc,Transparency and explainability,41,28,transparency
7,002,HSBC Holdings plc,AI and related technologies,91,33,"AI, artificial intelligence, automation, gener..."
8,002,HSBC Holdings plc,Data and analytics,5,5,"advanced analytics, data analytics, digital tr..."
9,002,HSBC Holdings plc,"Fairness, bias and ethics",17,13,"bias, discrimination, ethics, fairness"
10,002,HSBC Holdings plc,Governance and accountability,805,369,"AI ethics, accountability, governance, model r..."
11,002,HSBC Holdings plc,Risk and regulation,294,79,"cybersecurity, data protection, privacy, regul..."
12,002,HSBC Holdings plc,Transparency and explainability,15,14,transparency
13,003,Lloyds Banking Group plc,AI and related technologies,76,34,"AI, artificial intelligence, automation, gener..."
14,003,Lloyds Banking Group plc,Data and analytics,4,4,digital transformation
15,003,Lloyds Banking Group plc,"Fairness, bias and ethics",10,6,"bias, ethics"
16,003,Lloyds Banking Group plc,Governance and accountability,303,82,"AI ethics, accountability, ethical AI, governa..."
17,003,Lloyds Banking Group plc,Risk and regulation,200,90,"cybersecurity, privacy, regulatory compliance,..."
18,003,Lloyds Banking Group plc,Transparency and explainability,16,16,transparency
19,004,NatWest Group plc,AI and related technologies,198,56,"AI, artificial intelligence, automation, gener..."
20,004,NatWest Group plc,Data and analytics,5,5,"data analytics, data science, digital transfor..."
21,004,NatWest Group plc,"Fairness, bias and ethics",23,13,"bias, discrimination, ethics, fairness"
22,004,NatWest Group plc,Governance and accountability,891,431,"AI ethics, accountability, governance, model r..."
23,004,NatWest Group plc,Human oversight,1,1,automated decision-making
24,004,NatWest Group plc,Risk and regulation,297,107,"cybersecurity, data protection, privacy, regul..."
25,004,NatWest Group plc,Transparency and explainability,11,11,transparency
26,005,Standard Chartered plc,AI and related technologies,86,29,"AI, artificial intelligence, automation, gener..."
27,005,Standard Chartered plc,Data and analytics,6,6,"advanced analytics, data analytics, digital tr..."
28,005,Standard Chartered plc,"Fairness, bias and ethics",34,22,"bias, discrimination, ethics, fairness"
29,005,Standard Chartered plc,Governance and accountability,378,124,"accountability, governance, model risk, oversi..."

In [6]:
# Summary 2: pivot table showing category counts across companies

category_pivot = (
    company_category_summary
    .pivot_table(
        index=["company_id", "company_name"],
        columns="category",
        values="mention_count",
        fill_value=0
    )
    .reset_index()
)

category_pivot.to_csv(
    evidence_folder / "company_category_keyword_pivot.csv",
    index=False
)

category_pivot

category,company_id,company_name,AI and related technologies,Data and analytics,"Fairness, bias and ethics",Governance and accountability,Human oversight,Risk and regulation,Transparency and explainability
0,001,Barclays plc,231.0,10.0,20.0,927.0,1.0,358.0,41.0
1,002,HSBC Holdings plc,91.0,5.0,17.0,805.0,0.0,294.0,15.0
2,003,Lloyds Banking Group plc,76.0,4.0,10.0,303.0,0.0,200.0,16.0
3,004,NatWest Group plc,198.0,5.0,23.0,891.0,1.0,297.0,11.0
4,005,Standard Chartered plc,86.0,6.0,34.0,378.0,0.0,183.0,13.0
5,006,Aviva plc,90.0,2.0,16.0,568.0,0.0,89.0,5.0
6,007,Legal & General Group plc,45.0,2.0,10.0,263.0,0.0,87.0,23.0
7,008,M&G plc,20.0,0.0,5.0,552.0,0.0,134.0,13.0
8,009,Admiral Group plc,90.0,6.0,14.0,642.0,0.0,124.0,27.0
9,010,AJ Bell plc,18.0,0.0,5.0,346.0,0.0,108.0,8.0
10,011,IG Group Holdings plc,20.0,2.0,5.0,349.0,0.0,85.0,13.0
11,012,CMC Markets plc,2.0,0.0,1.0,263.0,0.0,90.0,11.0
12,013,IntegraFin Holdings plc,11.0,0.0,2.0,275.0,0.0,65.0,13.0
13,014,Wise plc,28.0,1.0,2.0,341.0,0.0,75.0,25.0
14,015,CAB Payments Holdings plc,23.0,1.0,9.0,364.0,0.0,77.0,11.0
15,016,Funding Circle Holdings plc,99.0,1.0,8.0,348.0,1.0,102.0,10.0
16,017,Boku Inc.,21.0,0.0,5.0,56.0,0.0,43.0,9.0
17,018,PayPoint plc,12.0,3.0,3.0,279.0,0.0,49.0,11.0
18,019,London Stock Exchange Group plc,112.0,10.0,9.0,324.0,0.0,95.0,8.0
19,020,Experian plc,67.0,1.0,13.0,221.0,0.0,147.0,20.0

In [7]:
# Summary 3: narrower AI-transparency-focused keyword set

ai_transparency_keywords = [
    "artificial intelligence",
    "AI",
    "machine learning",
    "algorithm",
    "automation",
    "generative AI",
    "large language model",
    "LLM",
    "responsible AI",
    "ethical AI",
    "AI ethics",
    "explainability",
    "explainable AI",
    "interpretability",
    "human oversight",
    "human review",
    "human-in-the-loop",
    "automated decision-making",
    "bias",
    "fairness"
]

ai_transparency_mentions = keyword_mentions[
    keyword_mentions["keyword"].isin(ai_transparency_keywords)
].copy()

ai_transparency_summary = (
    ai_transparency_mentions
    .groupby(["company_id", "company_name", "keyword"])
    .agg(
        mention_count=("keyword", "count"),
        unique_pages=("page_number", "nunique")
    )
    .reset_index()
    .sort_values(
        by=["company_id", "mention_count"],
        ascending=[True, False]
    )
)

ai_transparency_mentions.to_csv(
    evidence_folder / "ai_transparency_mentions_detailed.csv",
    index=False
)

ai_transparency_summary.to_csv(
    evidence_folder / "ai_transparency_keyword_summary.csv",
    index=False
)

print(f"AI-transparency-focused mentions found: {len(ai_transparency_mentions)}")

ai_transparency_summary.head(40)

AI-transparency-focused mentions found: 1448

,company_id,company_name,keyword,mention_count,unique_pages
0,001,Barclays plc,AI,195,47
1,001,Barclays plc,artificial intelligence,20,14
3,001,Barclays plc,bias,8,6
2,001,Barclays plc,automation,7,7
5,001,Barclays plc,fairness,7,7
8,001,Barclays plc,machine learning,7,6
6,001,Barclays plc,generative AI,2,2
4,001,Barclays plc,ethical AI,1,1
7,001,Barclays plc,human oversight,1,1
9,001,Barclays plc,responsible AI,1,1
10,002,HSBC Holdings plc,AI,73,29
12,002,HSBC Holdings plc,artificial intelligence,5,5
13,002,HSBC Holdings plc,automation,4,4
14,002,HSBC Holdings plc,bias,4,4
16,002,HSBC Holdings plc,generative AI,4,4
18,002,HSBC Holdings plc,machine learning,4,3
15,002,HSBC Holdings plc,fairness,3,3
11,002,HSBC Holdings plc,AI ethics,1,1
17,002,HSBC Holdings plc,large language model,1,1
19,002,HSBC Holdings plc,responsible AI,1,1
20,003,Lloyds Banking Group plc,AI,58,28
22,003,Lloyds Banking Group plc,artificial intelligence,9,8
26,003,Lloyds Banking Group plc,generative AI,5,5
23,003,Lloyds Banking Group plc,automation,3,3
21,003,Lloyds Banking Group plc,AI ethics,1,1
24,003,Lloyds Banking Group plc,bias,1,1
25,003,Lloyds Banking Group plc,ethical AI,1,1
27,003,Lloyds Banking Group plc,machine learning,1,1
28,004,NatWest Group plc,AI,144,42
30,004,NatWest Group plc,artificial intelligence,27,14
32,004,NatWest Group plc,automation,15,12
35,004,NatWest Group plc,generative AI,10,9
33,004,NatWest Group plc,bias,4,4
37,004,NatWest Group plc,responsible AI,4,3
34,004,NatWest Group plc,fairness,2,2
36,004,NatWest Group plc,machine learning,2,2
29,004,NatWest Group plc,AI ethics,1,1
31,004,NatWest Group plc,automated decision-making,1,1
38,005,Standard Chartered plc,AI,79,26
39,005,Standard Chartered plc,artificial intelligence,3,3

In [8]:
# Company-level AI transparency summary

company_ai_summary = (
    ai_transparency_mentions
    .groupby(["company_id", "company_name"])
    .agg(
        total_ai_transparency_mentions=("keyword", "count"),
        unique_pages_with_mentions=("page_number", "nunique"),
        unique_keywords_found=("keyword", "nunique"),
        keywords_found=("keyword", lambda x: ", ".join(sorted(set(x))))
    )
    .reset_index()
    .sort_values(
        by="total_ai_transparency_mentions",
        ascending=False
    )
)

company_ai_summary.to_csv(
    evidence_folder / "company_ai_transparency_summary.csv",
    index=False
)

company_ai_summary

,company_id,company_name,total_ai_transparency_mentions,unique_pages_with_mentions,unique_keywords_found,keywords_found
0,001,Barclays plc,249,60,10,"AI, artificial intelligence, automation, bias,..."
3,004,NatWest Group plc,210,61,10,"AI, AI ethics, artificial intelligence, automa..."
18,019,London Stock Exchange Group plc,119,34,8,"AI, LLM, artificial intelligence, automation, ..."
15,016,Funding Circle Holdings plc,104,30,8,"AI, artificial intelligence, automation, bias,..."
8,009,Admiral Group plc,103,39,8,"AI, artificial intelligence, automation, bias,..."
1,002,HSBC Holdings plc,100,39,10,"AI, AI ethics, artificial intelligence, automa..."
4,005,Standard Chartered plc,94,33,7,"AI, artificial intelligence, automation, bias,..."
5,006,Aviva plc,91,33,5,"AI, artificial intelligence, automation, fairn..."
2,003,Lloyds Banking Group plc,79,35,8,"AI, AI ethics, artificial intelligence, automa..."
19,020,Experian plc,74,35,7,"AI, artificial intelligence, automation, bias,..."
6,007,Legal & General Group plc,51,19,5,"AI, automation, bias, fairness, generative AI"
13,014,Wise plc,29,10,6,"AI, artificial intelligence, automation, bias,..."
14,015,CAB Payments Holdings plc,28,16,6,"AI, artificial intelligence, automation, bias,..."
7,008,M&G plc,24,19,5,"AI, artificial intelligence, automation, bias,..."
16,017,Boku Inc.,23,10,3,"AI, automation, fairness"
10,011,IG Group Holdings plc,22,16,5,"AI, artificial intelligence, automation, bias,..."
9,010,AJ Bell plc,21,14,6,"AI, artificial intelligence, automation, bias,..."
17,018,PayPoint plc,13,9,3,"AI, automation, bias"
12,013,IntegraFin Holdings plc,11,3,3,"AI, artificial intelligence, automation"
11,012,CMC Markets plc,3,3,3,"artificial intelligence, automation, bias"

In [9]:
# Pivot table: companies by AI-transparency keywords

ai_keyword_pivot = (
    ai_transparency_summary
    .pivot_table(
        index=["company_id", "company_name"],
        columns="keyword",
        values="mention_count",
        fill_value=0
    )
    .reset_index()
)

ai_keyword_pivot.to_csv(
    evidence_folder / "ai_transparency_keyword_pivot.csv",
    index=False
)

ai_keyword_pivot

keyword,company_id,company_name,AI,AI ethics,LLM,artificial intelligence,automated decision-making,automation,bias,ethical AI,fairness,generative AI,human oversight,human-in-the-loop,large language model,machine learning,responsible AI
0,001,Barclays plc,195.0,0.0,0.0,20.0,0.0,7.0,8.0,1.0,7.0,2.0,1.0,0.0,0.0,7.0,1.0
1,002,HSBC Holdings plc,73.0,1.0,0.0,5.0,0.0,4.0,4.0,0.0,3.0,4.0,0.0,0.0,1.0,4.0,1.0
2,003,Lloyds Banking Group plc,58.0,1.0,0.0,9.0,0.0,3.0,1.0,1.0,0.0,5.0,0.0,0.0,0.0,1.0,0.0
3,004,NatWest Group plc,144.0,1.0,0.0,27.0,1.0,15.0,4.0,0.0,2.0,10.0,0.0,0.0,0.0,2.0,4.0
4,005,Standard Chartered plc,79.0,0.0,0.0,3.0,0.0,3.0,2.0,0.0,3.0,1.0,0.0,0.0,0.0,0.0,3.0
5,006,Aviva plc,65.0,0.0,0.0,17.0,0.0,6.0,0.0,0.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0
6,007,Legal & General Group plc,43.0,0.0,0.0,0.0,0.0,1.0,5.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
7,008,M&G plc,13.0,0.0,0.0,4.0,0.0,3.0,2.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
8,009,Admiral Group plc,71.0,0.0,0.0,8.0,0.0,3.0,1.0,0.0,5.0,3.0,0.0,0.0,0.0,5.0,7.0
9,010,AJ Bell plc,5.0,0.0,0.0,2.0,0.0,8.0,1.0,0.0,2.0,3.0,0.0,0.0,0.0,0.0,0.0
10,011,IG Group Holdings plc,13.0,0.0,0.0,4.0,0.0,3.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
11,012,CMC Markets plc,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,013,IntegraFin Holdings plc,9.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,014,Wise plc,13.0,0.0,0.0,3.0,0.0,9.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,0.0
14,015,CAB Payments Holdings plc,13.0,0.0,0.0,2.0,0.0,7.0,2.0,0.0,3.0,0.0,0.0,0.0,0.0,1.0,0.0
15,016,Funding Circle Holdings plc,91.0,0.0,0.0,2.0,0.0,3.0,3.0,0.0,1.0,1.0,0.0,1.0,0.0,2.0,0.0
16,017,Boku Inc.,12.0,0.0,0.0,0.0,0.0,9.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
17,018,PayPoint plc,4.0,0.0,0.0,0.0,0.0,8.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,019,London Stock Exchange Group plc,96.0,0.0,2.0,7.0,0.0,4.0,7.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
19,020,Experian plc,44.0,0.0,0.0,8.0,0.0,7.0,2.0,0.0,5.0,6.0,0.0,0.0,0.0,2.0,0.0

In [10]:
# Created a smaller evidence sample for manual review

manual_review_sample = (
    ai_transparency_mentions
    .sort_values(
        by=["company_id", "page_number", "keyword"]
    )
    .groupby(["company_id", "company_name", "keyword"])
    .head(3)
    .reset_index(drop=True)
)

manual_review_sample.to_csv(
    evidence_folder / "manual_review_sample_ai_mentions.csv",
    index=False
)

manual_review_sample.head(50)

,company_id,company_name,report_year,source_file,category,keyword,search_variant,page_number,matched_text,context
0,001,Barclays plc,2025,001_barclays_plc_annual_report_2025.txt,"Fairness, bias and ethics",fairness,fairness,2,fairness,"d opportunity in courage, transparency and hum..."
1,001,Barclays plc,2025,001_barclays_plc_annual_report_2025.txt,AI and related technologies,AI,AI,6,AI,rough 2025 with rapid We are guided by our Val...
2,001,Barclays plc,2025,001_barclays_plc_annual_report_2025.txt,AI and related technologies,AI,AI,6,AI,bringing both opportunity and risk. Barclays i...
3,001,Barclays plc,2025,001_barclays_plc_annual_report_2025.txt,AI and related technologies,AI,AI,7,AI,to deepen our grasp of the opportunities and c...
4,001,Barclays plc,2025,001_barclays_plc_annual_report_2025.txt,AI and related technologies,automation,automation,22,automation,"control resilience, including by increasing ou..."
5,001,Barclays plc,2025,001_barclays_plc_annual_report_2025.txt,AI and related technologies,generative AI,generative AI,22,generative AI,"folios, and maintained their strong underlying..."
6,001,Barclays plc,2025,001_barclays_plc_annual_report_2025.txt,AI and related technologies,artificial intelligence,artificial intelligence,42,artificial intelligence,class customer experience; and delivering best...
7,001,Barclays plc,2025,001_barclays_plc_annual_report_2025.txt,AI and related technologies,automation,automation,43,automation,ith colleagues working on The Board has contin...
8,001,Barclays plc,2025,001_barclays_plc_annual_report_2025.txt,AI and related technologies,artificial intelligence,artificial intelligence,62,artificial intelligence,ds (including business or operations; the use ...
9,001,Barclays plc,2025,001_barclays_plc_annual_report_2025.txt,AI and related technologies,artificial intelligence,artificial intelligence,109,artificial intelligence,ustainability reporting standards (including b...
10,001,Barclays plc,2025,001_barclays_plc_annual_report_2025.txt,"Fairness, bias and ethics",fairness,fairness,111,fairness,"le what we do, and are passionate inclusion in..."
11,001,Barclays plc,2025,001_barclays_plc_annual_report_2025.txt,AI and related technologies,automation,automation,123,automation,mme and discussed its the operating environmen...
12,001,Barclays plc,2025,001_barclays_plc_annual_report_2025.txt,"Fairness, bias and ethics",fairness,fairness,165,fairness,", simple and transparent for all our as possib..."
13,001,Barclays plc,2025,001_barclays_plc_annual_report_2025.txt,"Fairness, bias and ethics",bias,bias,170,bias,"an employee, which includes any issues relatin..."
14,001,Barclays plc,2025,001_barclays_plc_annual_report_2025.txt,AI and related technologies,machine learning,machine learning,183,Machine Learning,ion of cost reporting effectiveness and effici...
15,001,Barclays plc,2025,001_barclays_plc_annual_report_2025.txt,AI and related technologies,machine learning,machine learning,211,machine learning,ry Digital services and workplace tools must O...
16,001,Barclays plc,2025,001_barclays_plc_annual_report_2025.txt,AI and related technologies,machine learning,machine learning,232,machine learning,"on situation, public business. generative and ..."
17,001,Barclays plc,2025,001_barclays_plc_annual_report_2025.txt,"Fairness, bias and ethics",bias,bias,238,bias,an be highly cybersecurity regulation applicab...
18,001,Barclays plc,2025,001_barclays_plc_annual_report_2025.txt,"Fairness, bias and ethics",bias,bias,239,bias,"significant, as AI technologies give rise to i..."
19,001,Barclays plc,2025,001_barclays_plc_annual_report_2025.txt,Human oversight,human oversight,human oversight,241,human oversight,"tomers, particularly those that are The Group ..."
20,001,Barclays plc,2025,001_barclays_plc_annual_report_2025.txt,Governance and accountability,ethical AI,ethical AI,253,Ethical AI,with regulations and relevant technical regula...
21,001,Barclays plc,2025,001_barclays_plc_annual_report_2025.txt,AI and related technologies,generative AI,generative AI,342,Generative AI,customers is at the heart of these plans. furt...
22,001,Barclays plc,2025,001_barclays_plc_annual_report_2025.txt,Governance and accountability,responsible AI,responsible AI,355,Responsible AI,ion laws. These reforms conduct automated scan...
23,002,HSBC Holdings plc,2025,002_hsbc_holdings_plc_annual_report_2025.txt,AI and related technologies,AI,AI,7,AI,offset by the significant momentum generated b...
24,002,HSBC Holdings plc,2025,002_hsbc_holdings_plc_annual_report_2025.txt,AI and related technologies,AI,AI,8,AI,Board at our 2026 AGM. I want to thank Ann gro...
25,002,HSBC Holdings plc,2025,002_hsbc_holdings_plc_annual_report_2025.txt,AI and related technologies,AI,AI,8,AI,"global trade is also set to grow, supported by..."
26,002,HSBC Holdings plc,2025,002_hsbc_holdings_plc_annual_report_2025.txt,AI and related technologies,automation,automation,10,automation,announced in 2024. We are modernising the bank...
27,002,HSBC Holdings plc,2025,002_hsbc_holdings_plc_annual_report_2025.txt,AI and related technologies,artificial intelligence,artificial intelligence,13,artificial intelligence,"source of funding for us, and forms the Hongko..."
28,002,HSBC Holdings plc,2025,002_hsbc_holdings_plc_annual_report_2025.txt,AI and related technologies,generative AI,generative AI,13,Generative AI,Bank plc. Improving operational excellence thr...
29,002,HSBC Holdings plc,2025,002_hsbc_holdings_plc_annual_report_2025.txt,AI and related technologies,large language model,large language model,13,large language model,inue to prioritisestaff in their roles. Around...
30,002,HSBC Holdings plc,2025,002_hsbc_holdings_plc_annual_report_2025.txt,"Fairness, bias and ethics",fairness,fairness,35,fairness,57 Building customer inclusion and resilience ...
31,002,HSBC Holdings plc,2025,002_hsbc_holdings_plc_annual_report_2025.txt,"Fairness, bias and ethics",bias,bias,55,bias,ce in average pay ethnicity pay gap was 9.8% (...
32,002,HSBC Holdings plc,2025,002_hsbc_holdings_plc_annual_report_2025.txt,Governance and accountability,AI ethics,AI ethics,58,AI ethics,et future challenges. and their level of AI in...
33,002,HSBC Holdings plc,2025,002_hsbc_holdings_plc_annual_report_2025.txt,Governance and accountability,responsible AI,responsible AI,58,responsible AI,preparing them to meet future challenges. and ...
34,002,HSBC Holdings plc,2025,002_hsbc_holdings_plc_annual_report_2025.txt,AI and related technologies,artificial intelligence,artificial intelligence,61,Artificial Intelligence,e human rights audits of suppliers HSBC’s Prin...
35,002,HSBC Holdings plc,2025,002_hsbc_holdings_plc_annual_report_2025.txt,"Fairness, bias and ethics",fairness,fairness,64,fairness,Additional Governance Report statements inform...
36,002,HSBC Holdings plc,2025,002_hsbc_holdings_plc_annual_report_2025.txt,AI and related technologies,generative AI,generative AI,104,Generative AI,"the importance of nature-related risks, as wel..."
37,002,HSBC Holdings plc,2025,002_hsbc_holdings_plc_annual_report_2025.txt,AI and related technologies,machine learning,machine learning,105,machine learning,and analytics infrastructure Mitigating action...
38,002,HSBC Holdings plc,2025,002_hsbc_holdings_plc_annual_report_2025.txt,AI and related technologies,machine learning,machine learning,106,machine learning,k for transformative initiatives. Additionally...
39,002,HSBC Holdings plc,2025,002_hsbc_holdings_plc_annual_report_2025.txt,AI and related technologies,machine learning,machine learning,183,machine learning,nued enhancements to our framework for the ind...
40,002,HSBC Holdings plc,2025,002_hsbc_holdings_plc_annual_report_2025.txt,AI and related technologies,artificial intelligence,artificial intelligence,191,artificial intelligence,businesses on digital transformation. develope...
41,002,HSBC Holdings plc,2025,002_hsbc_holdings_plc_annual_report_2025.txt,"Fairness, bias and ethics",fairness,fairness,211,fairness,election and and exit management process. This...
42,002,HSBC Holdings plc,2025,002_hsbc_holdings_plc_annual_report_2025.txt,AI and related technologies,automation,automation,216,automation,– The GTO reviewed plans to further embed the ...
43,002,HSBC Holdings plc,2025,002_hsbc_holdings_plc_annual_report_2025.txt,AI and related technologies,automation,automation,217,automation,operational resilience across the organisation...
44,002,HSBC Holdings plc,2025,002_hsbc_holdings_plc_annual_report_2025.txt,AI and related technologies,generative AI,generative AI,217,Generative AI,Group Technology & Operations Committee Princi...
45,002,HSBC Holdings plc,2025,002_hsbc_holdings_plc_annual_report_2025.txt,"Fairness, bias and ethics",bias,bias,258,bias,these methodologies when forecasting the exten...
46,002,HSBC Holdings plc,2025,002_hsbc_holdings_plc_annual_report_2025.txt,"Fairness, bias and ethics",bias,bias,259,bias,significant assumptions would give rise to ind...
47,003,Lloyds Banking Group plc,2025,003_lloyds_banking_group_plc_annual_report_202...,AI and related technologies,AI,AI,2,AI,"people, technology and data ...reinforcing com..."
48,003,Lloyds Banking Group plc,2025,003_lloyds_banking_group_plc_annual_report_202...,AI and related technologies,AI,AI,4,AI,for 2025 for growth. At the heart of our trans...
49,003,Lloyds Banking Group plc,2025,003_lloyds_banking_group_plc_annual_report_202...,AI and related technologies,AI,AI,6,AI,"bank, we continued to accelerate the shift Lev..."