In [38]:
# Importing necessary libraries
from pathlib import Path
import pandas as pd

data_folder = Path("../data")
processed_folder = Path("../data/processed")
evidence_folder = Path("../outputs/evidence_tables")

scores_file = data_folder / "transparency_scores.csv"
manual_review_file = data_folder / "manual_review_notes.csv"
ai_mentions_file = evidence_folder / "ai_transparency_mentions_detailed.csv"
ranking_file = evidence_folder / "strict_transparency_score_ranking_simple.csv"

scores = pd.read_csv(scores_file, dtype={"company_id": str})
manual_review = pd.read_csv(manual_review_file, dtype={"company_id": str})
ai_mentions = pd.read_csv(ai_mentions_file, dtype={"company_id": str})
ranking = pd.read_csv(ranking_file, dtype={"company_id": str})

print("Scores loaded:", len(scores))
print("Manual review rows:", len(manual_review))
print("AI evidence extracts:", len(ai_mentions))
print("Ranking rows:", len(ranking))

ranking

Scores loaded: 20
Manual review rows: 20
AI evidence extracts: 1452
Ranking rows: 20

,company_id,company_name,total_ai_transparency_mentions,unique_keywords,unique_pages,total_score,score_percentage
0,004,NatWest Group plc,210,10,61,13,92.86
1,001,Barclays plc,249,10,60,12,85.71
2,009,Admiral Group plc,103,8,39,11,78.57
3,016,Funding Circle Holdings plc,104,8,30,9,64.29
4,002,HSBC Holdings plc,102,10,39,9,64.29
5,005,Standard Chartered plc,95,7,33,9,64.29
6,003,Lloyds Banking Group plc,79,8,35,9,64.29
7,019,London Stock Exchange Group plc,119,8,34,8,57.14
8,020,Experian plc,74,7,35,7,50.00
9,006,Aviva plc,91,5,33,6,42.86
10,007,Legal & General Group plc,51,5,19,6,42.86
11,014,Wise plc,29,6,10,6,42.86
12,015,CAB Payments Holdings plc,28,6,16,6,42.86
13,008,M&G plc,24,5,19,6,42.86
14,011,IG Group Holdings plc,22,5,16,6,42.86
15,010,AJ Bell plc,21,6,14,6,42.86
16,017,Boku Inc.,23,3,10,5,35.71
17,013,IntegraFin Holdings plc,11,3,3,3,21.43
18,018,PayPoint plc,13,3,9,2,14.29
19,012,CMC Markets plc,4,4,4,1,7.14

In [2]:
def show_company_evidence(company_id, keywords=None, max_rows=30):
    """
    Displays evidence extracts for one company.
    Optional: filter by selected keywords.
    """
    
    evidence = ai_mentions[
        ai_mentions["company_id"] == company_id
    ].copy()
    
    if keywords is not None:
        evidence = evidence[
            evidence["keyword"].isin(keywords)
        ]
    
    evidence = evidence[
        [
            "company_id",
            "company_name",
            "keyword",
            "page_number",
            "matched_text",
            "context"
        ]
    ].sort_values(
        by=["keyword", "page_number"]
    )
    
    return evidence.head(max_rows)

In [3]:
show_company_evidence(
    company_id="004",
    keywords=[
        "artificial intelligence",
        "AI",
        "machine learning",
        "generative AI",
        "responsible AI",
        "AI ethics",
        "ethical AI",
        "human oversight",
        "automated decision-making",
        "bias",
        "fairness"
    ],
    max_rows=40
)

,company_id,company_name,keyword,page_number,matched_text,context
457,004,NatWest Group plc,AI,11,AI,"ivity. In addition, our newly established can ..."
458,004,NatWest Group plc,AI,11,AI,"cutting-edge research, leading responsible rev..."
459,004,NatWest Group plc,AI,11,AI,"and communities across the UK. For example, gr..."
460,004,NatWest Group plc,AI,12,AI,While we have momentum across NatWest • Custom...
461,004,NatWest Group plc,AI,12,AI,the full strength of NatWest Group – using the...
462,004,NatWest Group plc,AI,22,AI,Share of AUMA in total Private Banking coders ...
463,004,NatWest Group plc,AI,24,AI,to keep customers safe UK inflation rose to 3....
464,004,NatWest Group plc,AI,24,AI,"a of Excellence, we continued to develop Unemp..."
465,004,NatWest Group plc,AI,24,AI,"our defensive capabilities against the slowed,..."
466,004,NatWest Group plc,AI,25,AI,"transformation, driven by accelerated advancem..."
467,004,NatWest Group plc,AI,25,AI,"appropriate government policy, NatWest Group i..."
468,004,NatWest Group plc,AI,25,AI,NatWest Group is aiming to be a trusted leader...
469,004,NatWest Group plc,AI,25,AI,tors to discuss their help them reduce emissio...
470,004,NatWest Group plc,AI,25,AI,", assets under • Capital and liquidity managem..."
471,004,NatWest Group plc,AI,25,AI,management and operational value chain by 2050...
472,004,NatWest Group plc,AI,25,AI,timeliness and quality of responses to custome...
473,004,NatWest Group plc,AI,25,AI,"decisions. of over 22,000 hours in 2025. Ombud..."
474,004,NatWest Group plc,AI,25,AI,customer protection. funding and financing fra...
475,004,NatWest Group plc,AI,25,AI,• We’ve set ourselves standards for responsibl...
476,004,NatWest Group plc,AI,25,AI,"0 billion target, which was exceeded in Q1 202..."
477,004,NatWest Group plc,AI,28,AI,spending and security. To support first-time b...
478,004,NatWest Group plc,AI,28,AI,to 1.3 million whenever they needed it. We are...
479,004,NatWest Group plc,AI,28,AI,leagues to contribute a deposit or hold any ow...
480,004,NatWest Group plc,AI,28,AI,property responded to the needs of our custome...
481,004,NatWest Group plc,AI,31,AI,ancial statements Additional information NatWe...
482,004,NatWest Group plc,AI,34,AI,their to provide £100 billion of climate and s...
483,004,NatWest Group plc,AI,34,AI,ial & Institutional will continue Many busines...
484,004,NatWest Group plc,AI,34,AI,icity in faster and improve services. In Busin...
485,004,NatWest Group plc,AI,34,AI,to make banking simpler and strengthen more th...
486,004,NatWest Group plc,AI,35,AI,"ure (+1), and ways. This included ongoing cons..."
487,004,NatWest Group plc,AI,36,AI,engaged How we engaged • We established and bu...
488,004,NatWest Group plc,AI,42,AI,nd accessibility of our integrity and responsi...
489,004,NatWest Group plc,AI,45,AI,"laboration with in spring 2025, to harness aca..."
490,004,NatWest Group plc,AI,48,AI,"accessibility, stability, and responsible use ..."
491,004,NatWest Group plc,AI,49,AI,NatWest Group plc 2025 Annual Report and Accou...
492,004,NatWest Group plc,AI,49,AI,Embedding AI in our customer journeys Our aim ...
493,004,NatWest Group plc,AI,49,AI,"Spotlight experience for all our customers, wh..."
494,004,NatWest Group plc,AI,49,AI,lp us become a simpler organisation for Using ...
495,004,NatWest Group plc,AI,49,AI,we focused on strengthening our allows us to a...
496,004,NatWest Group plc,AI,49,AI,and telephony customer journeys. We continued ...

In [4]:
pd.set_option("display.max_colwidth", None)
pd.set_option("display.max_rows", 100)

natwest_keyword_counts = (
    ai_mentions[ai_mentions["company_id"] == "004"]
    .groupby("keyword")
    .agg(
        mention_count=("keyword", "count"),
        unique_pages=("page_number", "nunique")
    )
    .reset_index()
    .sort_values(by="mention_count", ascending=False)
)

natwest_keyword_counts

                     keyword  mention_count  unique_pages
0                         AI            144            42
2    artificial intelligence             27            14
4                 automation             15            12
7              generative AI             10             9
9             responsible AI              4             3
5                       bias              4             4
8           machine learning              2             2
6                   fairness              2             2
1                  AI ethics              1             1
3  automated decision-making              1             1

In [5]:
def print_company_evidence(company_id, keywords, max_items=25):
    evidence = ai_mentions[
        (ai_mentions["company_id"] == company_id) &
        (ai_mentions["keyword"].isin(keywords))
    ].copy()
    
    evidence = evidence.sort_values(
        by=["keyword", "page_number"]
    )
    
    for _, row in evidence.head(max_items).iterrows():
        print("=" * 100)
        print(f"Company: {row['company_name']}")
        print(f"Keyword: {row['keyword']}")
        print(f"Page: {row['page_number']}")
        print("-" * 100)
        print(row["context"])
        print()

In [6]:
print_company_evidence(
    company_id="004",
    keywords=[
        "artificial intelligence",
        "machine learning",
        "generative AI",
        "responsible AI",
        "AI ethics",
        "ethical AI",
        "human oversight",
        "human review",
        "human-in-the-loop",
        "automated decision-making",
        "bias",
        "fairness"
    ],
    max_items=30
)

====================================================================================================
Company: NatWest Group plc
Keyword: AI ethics
Page: 49
----------------------------------------------------------------------------------------------------
ed on appropriate guardrails to ensure thebest practice with an expectation that suppliers (now 21, as at 31 December 2025). As a result, the University’s Data and AI Ethics masters safe and secure deployment of AI.(1)conform to the most recent version of the we have seen around a 20-percentage-point course, with more cohorts planned for 2026.

====================================================================================================
Company: NatWest Group plc
Keyword: artificial intelligence
Page: 59
----------------------------------------------------------------------------------------------------
for example, privacy training to our data customers and suppliers. and artificial intelligence colleagues. Regular risk assessments: Risk assessments During 2025, there were a small number are condu

====================================================================================================
Company: NatWest Group plc
Keyword: artificial intelligence
Page: 80
----------------------------------------------------------------------------------------------------
merging risks scenarios that follow are shown in alphabetical order. Top risk scenarios in focus in 2025 Description Risk management actions Artificial intelligence Innovations in artificial intelligence (AI), including generative AI, may rapidly • NatWest Group closely monitors developments in disruptive technologies, including AI.

====================================================================================================
Company: NatWest Group plc
Keyword: artificial intelligence
Page: 80
----------------------------------------------------------------------------------------------------
betical order. Top risk scenarios in focus in 2025 Description Risk management actions Artificial intelligence Innovations in artificial intelligence (AI), including generative AI, may rapidly • NatWest Group closely monitors developments in disruptive technologies, including AI. transform and disrupt customer i

====================================================================================================
Company: NatWest Group plc
Keyword: artificial intelligence
Page: 118
----------------------------------------------------------------------------------------------------
behavioural the refresh of our purpose, strategy, ambition and performance culture, the new artificial intelligence (AI), and how cultural The Board also sets NatWest Group’s framework framework consolidated previous colleague frameworks into a single set of

====================================================================================================
Company: NatWest Group plc
Keyword: artificial intelligence
Page: 270
----------------------------------------------------------------------------------------------------
esponses to manage any associated and to help with horizon scanning. risks. Artificial Intelligence, Quantum Risk management framework section.• Compliance with UK and EU operational By me

====================================================================================================
Company: NatWest Group plc
Keyword: artificial intelligence
Page: 406
----------------------------------------------------------------------------------------------------
on loans, customer exchange rates. Nevertheless, changes in stakeholders regarding how NatWest Group artificial intelligence in NatWest Group’s behaviour (which may adversely impact the currency exchange rates, particularly in the addresses environ

====================================================================================================
Company: NatWest Group plc
Keyword: artificial intelligence
Page: 408
----------------------------------------------------------------------------------------------------
segments. Moreover, innovations in attractive and/or better value range of invests in new technologies and participates technology conglomerates and new market biometrics, artificial intelligence, automation, products and services and geographic in industry and research-led technology entrants leveraging technology and/or other cloud services, blockchain, cryptocurrencies diversit

====================================================================================================
Company: NatWest Group plc
Keyword: artificial intelligence
Page: 408
----------------------------------------------------------------------------------------------------
anks”) and digitalisation, automation, and the use offintechs are aiming to compete to serve artificial intelligence while needing to continue Failure to offer competitive, attractive, Any of the above may have a materialcustomers that increasingly use a complying with applic

====================================================================================================
Company: NatWest Group plc
Keyword: artificial intelligence
Page: 408
----------------------------------------------------------------------------------------------------
. NatWest customer-facing businesses, including customers, certain assets, liabilities, technological changes (including digital Group’s innovation strategy, which includes through artificial intelligence. There can be no transactions and activities of NatWest Group currencies, stablecoins and the growth of investing in its IT capability to address certainty that such initiatives will allow

====================================================================================================
Company: NatWest Group plc
Keyword: artificial intelligence
Page: 413
----------------------------------------------------------------------------------------------------
ding to invest in building new capabilities that requires management to make judgements, Accounting policies deemed critical to position, cost of funding and could limit the employ new artificial intelligence technologies, estimates and assumptions that affect the NatWest Group’s results and financial range of counterparties willing to enter into such as generative artificial intelligence, and it reported

====================================================================================================
Company: NatWest Group plc
Keyword: artificial intelligence
Page: 413
----------------------------------------------------------------------------------------------------
the employ new artificial intelligence technologies, estimates and assumptions that affect the NatWest Group’s results and financial range of counterparties willing to enter into such as generative artificial intelligence, and it reported amounts of assets, liabilities, position, based upon materiality and transactions with NatWest Group on expects its use of these technologies to income, expenses,

====================================================================================================
Company: NatWest Group plc
Keyword: artificial intelligence
Page: 413
----------------------------------------------------------------------------------------------------
sophisticated modelling approaches, including other factors (including market practice and these include loan impairments, fair value, artificial intelligence, and no assurance can expectations of future events that are and deferred tax. These are set out in Any of the above may have a material be provided that NatWest Group’s use of believe

====================================================================================================
Company: NatWest Group plc
Keyword: artificial intelligence
Page: 413
----------------------------------------------------------------------------------------------------
a material be provided that NatWest Group’s use of believed to be reasonable under the ‘Critical accounting policies and sources of adverse effect on NatWest Group’s future artificial intelligence in its models will enhance circumstances), actual results may differ due estimation uncertainty’. results, financial condition, prospects, and/or its business or produce only intended or to t

====================================================================================================
Company: NatWest Group plc
Keyword: artificial intelligence
Page: 415
----------------------------------------------------------------------------------------------------
thorities continued digitalisation and the integration of inadvertently facilitating financial crime which shares of the relevant entity to a private may adversely affect holders of NatWest artificial intelligence in the business; may result in regulatory investigation, sector purchaser; (ii) transfer of all or part of Group plc’s ordinary shares or other NatWest acquisition, divestments and other

====================================================================================================
Company: NatWest Group plc
Keyword: artificial intelligence
Page: 415
----------------------------------------------------------------------------------------------------
mobile banking. Financial crime assessment,entities within NatWest Group, and the Operational risk is the risk of loss or services and artificial intelligence) and systems and controls, internal stress testsAuthorities have the power to modify or disruption resulting from inadeq

====================================================================================================
Company: NatWest Group plc
Keyword: artificial intelligence
Page: 416
----------------------------------------------------------------------------------------------------
s, third-party certain solutions and customer interactions, compliance with cybersecurity and data evolving cybersecurity capabilities and providers or other users with access to including through artificial intelligence. Such protection regulations is becoming controls that are designed to mitigate the NatWest Group’s systems to wrongfully initiatives may result in operational, increasingly compl

====================================================================================================
Company: NatWest Group plc
Keyword: artificial intelligence
Page: 416
----------------------------------------------------------------------------------------------------
mation (including defective, inadequate or resources and planning devoted to mitigate are increasing in terms of frequency, and cybersecurity policies, procedures or inappropriately used artificial intelligence operational risk, such measures may not be sophistication, impact and severity. The controls, may result in significant financial based solutions). effective in controlling each of the operation

====================================================================================================
Company: NatWest Group plc
Keyword: artificial intelligence
Page: 417
----------------------------------------------------------------------------------------------------
f transactions efficiently and interacts. As NatWest Group develops new regulatory focus. accurately while complying with applicable NatWest Group uses IT systems that enable artificial intelligence-based products, laws and regulations. The proper functioning remote working interface with third-party proprietary, sensitive, or confidential

====================================================================================================
Company: NatWest Group plc
Keyword: artificial intelligence
Page: 417
----------------------------------------------------------------------------------------------------
d result in including if such information is used to train the inability to deliver products and services. systems, including cloud services providers business and customer interruption and third-party artificial intelligence models. This This could also place NatWest Group at a (some of which are owned and operated by related reputational damage, significant may increase the risk of data leakage, data competitive di

====================================================================================================
Company: NatWest Group plc
Keyword: artificial intelligence
Page: 417
----------------------------------------------------------------------------------------------------
se consequences due to upgrade and improve its IT and technology or artificial intelligence based solutions), lossNatWest Group’s operations and strategy inappropriate models, systems, processes, capabilities (including migration of certain

====================================================================================================
Company: NatWest Group plc
Keyword: artificial intelligence
Page: 417
----------------------------------------------------------------------------------------------------
could result in reputational damage, operations, innovate its products offering, and artificial intelligence based solutions in its significant compensation costs and regulatory meet its regulatory obligations, and

====================================================================================================
Company: NatWest Group plc
Keyword: artificial intelligence
Page: 418
----------------------------------------------------------------------------------------------------
substantial regulation and oversight, which financial condition, strategic delivery, or result technology, artificial intelligence and data), in (including any outsourced functions); ensure are constantly evolving and may adversely

====================================================================================================
Company: NatWest Group plc
Keyword: artificial intelligence
Page: 420
----------------------------------------------------------------------------------------------------
• any regulatory requirements relating to regulations, may adversely affect NatWest and resilience of, and competition and • increased innovation in private digital the use of artificial intelligence and large Group’s business, results of operations and innovation in, digital and other markets, asset propositions, such as stablecoin or language models across the financial outlo

====================================================================================================
Company: NatWest Group plc
Keyword: artificial intelligence
Page: 420
----------------------------------------------------------------------------------------------------
hich may challenge services industry (such as the European insufficient international regulatory development of the government’s traditional payment methods and have Union Artificial Intelligence Act). coordination as enhanced supervisory National Payments Vision and Strategy) other potential adverse effects on UK standards are d

====================================================================================================
Company: NatWest Group plc
Keyword: artificial intelligence
Page: 423
----------------------------------------------------------------------------------------------------
Moreover, the rising energy demand impacts, risks and opportunities, including the zero across its financed emissions, assets associated with artificial intelligence effective measurement, governance and under management and operational value NatWest Group’s ability to achieve its workloads, whether generated internally or reporting of progre

====================================================================================================
Company: NatWest Group plc
Keyword: artificial intelligence
Page: 423
----------------------------------------------------------------------------------------------------
n many factors to assess the potential impacts of increased the availability of accurate, reliable, verifiable, activity-based targets. and uncertainties beyond NatWest Group’s artificial intelligence usage, its full effects on auditable, consistent and comparable internal control. These include (but are not limited to): NatWest Group’s own operational

====================================================================================================
Company: NatWest Group plc
Keyword: artificial intelligence
Page: 431
----------------------------------------------------------------------------------------------------
ty suppliers); cyberattacks; the accuracy with a consistent basis for comparing business related forward-looking statements, including, without limitation those referred to below). and effective use of data; artificial intelligence; performance between financial periods and but not limited to, NatWest Group’s ambition

====================================================================================================
Company: NatWest Group plc
Keyword: automated decision-making
Page: 190
----------------------------------------------------------------------------------------------------
expected under stress. Credit customers. The assessment process depends and challenge of frontline credit risk by automated decision-making. To maintain risk is further controlled through operational on the complexity of the transaction. management activi

====================================================================================================
Company: NatWest Group plc
Keyword: bias
Page: 125
----------------------------------------------------------------------------------------------------
(in relation to Provision 23 of the Code) the gender balance of senior management and their direct reports. criteria without bias, prejudice, or discrimination, and that searches for Board candidates are conducted with due regard to the benefits of diversity and inclusion.

In [7]:
# Manual validation outcome for NatWest

manual_review.loc[
    manual_review["company_id"] == "004",
    "manual_adjusted_score"
] = 13

manual_review.loc[
    manual_review["company_id"] == "004",
    "manual_adjusted_percentage"
] = 92.86

manual_review.loc[
    manual_review["company_id"] == "004",
    "reason_for_adjustment"
] = (
    "No adjustment made. NatWest shows repeated AI-related disclosures, "
    "including artificial intelligence, generative AI, AI ethics, risk scenarios, "
    "automated decision-making and risk/control language. Some extracted contexts "
    "are noisy, but the overall evidence supports a high provisional transparency score."
)

manual_review.loc[
    manual_review["company_id"] == "004",
    "important_pages"
] = "49, 80, 190, 413-420"

manual_review.loc[
    manual_review["company_id"] == "004",
    "important_extracts"
] = (
    "References to AI ethics, responsible guardrails, generative AI, "
    "AI-related risk scenarios, artificial intelligence usage and automated decision-making."
)

manual_review.loc[
    manual_review["company_id"] == "004",
    "review_status"
] = "Reviewed - provisional score retained"

manual_review.to_csv(
    manual_review_file,
    index=False
)

manual_review[manual_review["company_id"] == "004"]

,company_id,company_name,total_ai_transparency_mentions,unique_keywords,unique_pages,total_score,score_percentage,manual_adjusted_score,manual_adjusted_percentage,reason_for_adjustment,important_pages,important_extracts,review_status
0,004,NatWest Group plc,210,10,61,13,92.86,13.0,92.86,"No adjustment made. NatWest shows repeated AI-related disclosures, including artificial intelligence, generative AI, AI ethics, risk scenarios, automated decision-making and risk/control language. Some extracted contexts are noisy, but the overall evidence supports a high provisional transparency score.","49, 80, 190, 413-420","References to AI ethics, responsible guardrails, generative AI, AI-related risk scenarios, artificial intelligence usage and automated decision-making.",Reviewed - provisional score retained

In [8]:
# Fixing manual review column data types

text_columns = [
    "reason_for_adjustment",
    "important_pages",
    "important_extracts",
    "review_status"
]

numeric_columns = [
    "manual_adjusted_score",
    "manual_adjusted_percentage"
]

# Make sure text columns can accept written notes
for column in text_columns:
    if column not in manual_review.columns:
        manual_review[column] = ""
    manual_review[column] = manual_review[column].astype("object")

# Make sure numeric columns can accept score values
for column in numeric_columns:
    if column not in manual_review.columns:
        manual_review[column] = pd.NA

# Now record manual validation outcome for NatWest again

manual_review.loc[
    manual_review["company_id"] == "004",
    "manual_adjusted_score"
] = 13

manual_review.loc[
    manual_review["company_id"] == "004",
    "manual_adjusted_percentage"
] = 92.86

manual_review.loc[
    manual_review["company_id"] == "004",
    "reason_for_adjustment"
] = (
    "No adjustment made. NatWest shows repeated AI-related disclosures, "
    "including artificial intelligence, generative AI, AI ethics, risk scenarios, "
    "automated decision-making and risk/control language. Some extracted contexts "
    "are noisy, but the overall evidence supports a high provisional transparency score."
)

manual_review.loc[
    manual_review["company_id"] == "004",
    "important_pages"
] = "49, 80, 190, 413-420"

manual_review.loc[
    manual_review["company_id"] == "004",
    "important_extracts"
] = (
    "References to AI ethics, responsible guardrails, generative AI, "
    "AI-related risk scenarios, artificial intelligence usage and automated decision-making."
)

manual_review.loc[
    manual_review["company_id"] == "004",
    "review_status"
] = "Reviewed - provisional score retained"

manual_review.to_csv(
    manual_review_file,
    index=False
)

manual_review[manual_review["company_id"] == "004"]

,company_id,company_name,total_ai_transparency_mentions,unique_keywords,unique_pages,total_score,score_percentage,manual_adjusted_score,manual_adjusted_percentage,reason_for_adjustment,important_pages,important_extracts,review_status
0,004,NatWest Group plc,210,10,61,13,92.86,13.0,92.86,"No adjustment made. NatWest shows repeated AI-related disclosures, including artificial intelligence, generative AI, AI ethics, risk scenarios, automated decision-making and risk/control language. Some extracted contexts are noisy, but the overall evidence supports a high provisional transparency score.","49, 80, 190, 413-420","References to AI ethics, responsible guardrails, generative AI, AI-related risk scenarios, artificial intelligence usage and automated decision-making.",Reviewed - provisional score retained

In [9]:
# Barclays keyword count review

barclays_keyword_counts = (
    ai_mentions[ai_mentions["company_id"] == "001"]
    .groupby("keyword")
    .agg(
        mention_count=("keyword", "count"),
        unique_pages=("page_number", "nunique")
    )
    .reset_index()
    .sort_values(by="mention_count", ascending=False)
)

barclays_keyword_counts

                   keyword  mention_count  unique_pages
0                       AI            195            47
1  artificial intelligence             20            14
3                     bias              8             6
2               automation              7             7
5                 fairness              7             7
8         machine learning              7             6
6            generative AI              2             2
4               ethical AI              1             1
7          human oversight              1             1
9           responsible AI              1             1

In [10]:
print_company_evidence(
    company_id="001",
    keywords=[
        "artificial intelligence",
        "machine learning",
        "generative AI",
        "responsible AI",
        "AI ethics",
        "ethical AI",
        "human oversight",
        "human review",
        "human-in-the-loop",
        "automated decision-making",
        "bias",
        "fairness"
    ],
    max_items=35
)

====================================================================================================
Company: Barclays plc
Keyword: artificial intelligence
Page: 42
----------------------------------------------------------------------------------------------------
class customer experience; and delivering best You can find out more about how the Directors have had regard to the matters set out in Section embracing artificial intelligence (AI) and other new in classservicecustomer 172(1) when discharging their duties, and the technologies in

====================================================================================================
Company: Barclays plc
Keyword: artificial intelligence
Page: 62
----------------------------------------------------------------------------------------------------
ds (including business or operations; the use of newor current facts. Forward-looking statements emissions accounting methodologies); changes technology, including artificial intelligence; thesometimes use words such as ‘may’, ‘will’, ‘seek’, in tax laws and practice; the outcome of current Group’s ability to access funding; and the success‘

====================================================================================================
Company: Barclays plc
Keyword: artificial intelligence
Page: 109
----------------------------------------------------------------------------------------------------
ustainability reporting standards (including business or operations; the use of new ‘continue’, ‘aim’, ‘anticipate’, ‘target’, ‘projected’, emissions accounting methodologies); changes technology, including artificial intelligence; the ‘expect’, ‘estimate’, ‘intend’, ‘plan’, ‘goal’, ‘believe’, in tax laws and practice; the outcome of current Group’s ability to access funding; and the success ‘achieve’ or other words of similar meaning.

====================================================================================================
Company: Barclays plc
Keyword: artificial intelligence
Page: 183
----------------------------------------------------------------------------------------------------
al Control, and standardisation of cost reporting effectiveness and efficiency activities, with further potential to simplify and automate in the future. • Launched nine Artificial Intelligence and Machine Learning initiatives in the Group Finance function, delivering measurable benefits, with many more use cases in the pipeline. Oversee the effective • Group Fina

====================================================================================================
Company: Barclays plc
Keyword: artificial intelligence
Page: 232
----------------------------------------------------------------------------------------------------
ordinary shareholders. legacy businesses; and (v) the extent to x) Evolving landscape with respect to Shareholders and creditors should assume which contingent risks arise in the acquired artificial intelligence (including that, in a resolution situation, public business. generative and agentic artificial

====================================================================================================
Company: Barclays plc
Keyword: artificial intelligence
Page: 233
----------------------------------------------------------------------------------------------------
ntravention Order Removing Barriers to American and compliance with existing and futureof agreements with the Group, inputting Leadership in Artificial Intelligence which laws and regulations, and “Cyber attacks”the Group’s confidential or proprietary prioritises deregulation, several state

====================================================================================================
Company: Barclays plc
Keyword: artificial intelligence
Page: 233
----------------------------------------------------------------------------------------------------
risks relating to AI technologies.development, training or fine-tuning of the enacted regulations concerning the use of tool from unlawful sources or in an artificial intelligence technologies. Material existing and emerging otherwise unlawful manner or These include the California Transparency risks impacting individualimplementing the roll-out of ne

====================================================================================================
Company: Barclays plc
Keyword: artificial intelligence
Page: 233
----------------------------------------------------------------------------------------------------
anner or These include the California Transparency risks impacting individualimplementing the roll-out of new AI tools in Frontier Artificial Intelligence Act, the principal risksor functionalities without the Group’s Utah Artificial Intelligence Consumer i) Climate riskapproval. See “supplier exposure” for more

====================================================================================================
Company: Barclays plc
Keyword: artificial intelligence
Page: 233
----------------------------------------------------------------------------------------------------
-out of new AI tools in Frontier Artificial Intelligence Act, the principal risksor functionalities without the Group’s Utah Artificial Intelligence Consumer i) Climate riskapproval. See “supplier exposure” for more Protection Amendments, the updated Climate risk is the risk of financial lossesinformatio

====================================================================================================
Company: Barclays plc
Keyword: artificial intelligence
Page: 238
----------------------------------------------------------------------------------------------------
“Evolving landscape with respect to The Group holds and processes largesome other jurisdictions on the need for a artificial intelligence (including generative volumes of data, including personalcertain level of human inventorship. and agentic artificial intelligence) (AI) and information, financial data and oth

====================================================================================================
Company: Barclays plc
Keyword: artificial intelligence
Page: 238
----------------------------------------------------------------------------------------------------
artificial intelligence (including generative volumes of data, including personalcertain level of human inventorship. and agentic artificial intelligence) (AI) and information, financial data and otherAdditionally, inventions or works of machine learning technologies,” “Model confidential information, and the Group’sauthorsh

====================================================================================================
Company: Barclays plc
Keyword: artificial intelligence
Page: 239
----------------------------------------------------------------------------------------------------
tigation, intelligence (including generative and process transactions or provide banking regulatory or other government action agentic artificial intelligence) (AI) and and payment services. (including significant regulatory fines) and machine learning technologies” and “New require changes to certain operations or and emergent technology”.

====================================================================================================
Company: Barclays plc
Keyword: artificial intelligence
Page: 240
----------------------------------------------------------------------------------------------------
labour, immigration and related policies in intelligence (including generative and the jurisdictions in which the Group agentic artificial intelligence) (AI) and operates), regulatory factors (including machine learning technologies”, “New and

====================================================================================================
Company: Barclays plc
Keyword: artificial intelligence
Page: 253
----------------------------------------------------------------------------------------------------
local entity Board Risk Committee(s). firm. end management of model risk. In addition, the Model Strategy and Overview The Artificial Intelligence (AI) Policy lays out Oversight (MSO) Team, which is a first line Compliance Risk incorporates wholesale

====================================================================================================
Company: Barclays plc
Keyword: artificial intelligence
Page: 342
----------------------------------------------------------------------------------------------------
work principles and design. financing) - to a principal risk within the plans were assessed and businesses• Introduced Artificial Intelligence(AI) Enterprise Risk Management Framework ensured that driving good outcomes for Standard in support of the AI Policy,

====================================================================================================
Company: Barclays plc
Keyword: artificial intelligence
Page: 355
----------------------------------------------------------------------------------------------------
uch systems do not undertakings for breaches of consumer discriminate against applicants or Artificial intelligence law. The Advertising Standards Authority is employees on the basis of protected A number of jurisdictions whe

====================================================================================================
Company: Barclays plc
Keyword: artificial intelligence
Page: 355
----------------------------------------------------------------------------------------------------
ng adopting new laws direct marketing in the UK, and has also results. Notably, however, in December regulating artificial intelligence (AI). been focusing on greenwashing, including 2025, President Trump signed an

====================================================================================================
Company: Barclays plc
Keyword: artificial intelligence
Page: 355
----------------------------------------------------------------------------------------------------
uding 2025, President Trump signed an investigating and making rulings againstThe EU’s Artificial Intelligence Act (EU AI executive order outlining various plans to advertisements from financial servicesAct), which entered into force on 1 Augus

====================================================================================================
Company: Barclays plc
Keyword: artificial intelligence
Page: 382
----------------------------------------------------------------------------------------------------
al period which requires a tender 31 December 2027and analytics tools across our audit. We continue to expand our use of accredited Tenure of Group engagement partner 4 years Artificial Intelligence based solutions into Average tenure of component engagement partners 3 years our audit process. We have also continued to innovate our audit of the estimation of

====================================================================================================
Company: Barclays plc
Keyword: artificial intelligence
Page: 493
----------------------------------------------------------------------------------------------------
riting, but also may be made verbally by business or operations; the use of new technology, point in time. directors, officers and employees of the Group including artificial intelligence; the Group’s ability to Relevant terms that are used in this document, but (including during management presentations) in access funding; and the success of acquisitions, are not defined under applicable regula

====================================================================================================
Company: Barclays plc
Keyword: bias
Page: 170
----------------------------------------------------------------------------------------------------
an employee, which includes any issues relating to pay We will continue to conduct our assurance activities to ensure that performance ratings and pay outcomes remain fair and free from bias

====================================================================================================
Company: Barclays plc
Keyword: bias
Page: 238
----------------------------------------------------------------------------------------------------
an be highly cybersecurity regulation applicable to the technology integration and process issues sophisticated (e.g. leveraging deepfake and Group, refer to the Supervision and and programme bias in decision-making automation capabilities), and be regulation section. algorithms. Any of these risks could impair orchestrated by organised crime groups or

====================================================================================================
Company: Barclays plc
Keyword: bias
Page: 239
----------------------------------------------------------------------------------------------------
significant, as AI technologies give rise to internal (whether intentional or accidental) information, or that include AI bias, AI risk of bias, errors and hallucinations which security risks. Concerns regarding the hallucinations,

====================================================================================================
Company: Barclays plc
Keyword: bias
Page: 239
----------------------------------------------------------------------------------------------------
ies give rise to internal (whether intentional or accidental) information, or that include AI bias, AI risk of bias, errors and hallucinations which security risks. Concerns regarding the hallucinations, harmful content, may impact the Group’s ability to effective

====================================================================================================
Company: Barclays plc
Keyword: bias
Page: 241
----------------------------------------------------------------------------------------------------
ry sanctions, both for themodel types. This includes risks arising from AI hallucinating and providing false b) Customer protection risk individuals and the Group. information, the exacerbation of bias and The Group must ensure that its e) Data privacy risk fairness risk due to the automation of customers, particularly those that are The Group must ensure that personal data outcomes and th

====================================================================================================
Company: Barclays plc
Keyword: bias
Page: 355
----------------------------------------------------------------------------------------------------
s of potential California and Illinois, require employers to DMCCA also simplifies and enhances thedisruption. Such measures are resulting in conduct bias audits, provide transparency process by which the regulators mayincreased technology and compliance through notice to candidates and

====================================================================================================
Company: Barclays plc
Keyword: bias
Page: 391
----------------------------------------------------------------------------------------------------
e impact of the pressure management may be in a position to make to meet targets set out in the strategic inappropriate accounting entries and the plan. FY25 marked the second year of risk of management bias in accounting execution against the three-year estimates and judgements. strategic plan announced by Barclays In this audit, we have not identified a PLC Group in their February 2024 signi

====================================================================================================
Company: Barclays plc
Keyword: bias
Page: 391
----------------------------------------------------------------------------------------------------
about where fraud risks may effectiveness of relevant internal controls, arise. The discussions also involved our assessing significant accounting estimates forensic specialists to assist us in for bias, as well as substantive procedures identifying fraud risk factors based on to address the fraud risks. discussions of the circumstances of the Group and Parent Company, including consideration of fraudulent

====================================================================================================
Company: Barclays plc
Keyword: ethical AI
Page: 253
----------------------------------------------------------------------------------------------------
with regulations and relevant technical regulation risks. Barclays has no appetite • Define Ethical AI Principles to enable standards, following a risk-based approach for material breaches of LRR, or ethical, lawful, and appropriate use of AI. focusing on material modelling issues, Compliance Risk is

====================================================================================================
Company: Barclays plc
Keyword: fairness
Page: 2
----------------------------------------------------------------------------------------------------
d opportunity in courage, transparency and humility, putting the what we do, championing leaving things better than our business, trust those we and fairness in all we do people and businesses innovation and using we found them work with, and value we serve at the centre of

====================================================================================================
Company: Barclays plc
Keyword: fairness
Page: 111
----------------------------------------------------------------------------------------------------
le what we do, and are passionate inclusion in our transparency and businesses championing about leaving business, trust those and fairness we serve at innovation and using things better than we work with, and in all we do the centre our energy, expertise we found them value

====================================================================================================
Company: Barclays plc
Keyword: fairness
Page: 165
----------------------------------------------------------------------------------------------------
, simple and transparent for all our as possible stakeholders. All employees and stakeholders should understand how we reward our employees, and fairness should be a lens through which we make remuneration decisions. Role of the Remuneration Committee in wider workforce remuneration The Committee considers the overarching obj

====================================================================================================
Company: Barclays plc
Keyword: fairness
Page: 170
----------------------------------------------------------------------------------------------------
's role and contribution We have robust processes to review and challenge performance and pay decisions We work closely with Unite the union to review the fairness of performance management and pay distribution for the employees they cover in the UK We are actively making our approach to fair pay more transparent for employees Emplo

====================================================================================================
Company: Barclays plc
Keyword: fairness
Page: 213
----------------------------------------------------------------------------------------------------
business practices and processes tothere is no undue pressure on colleagues buying their first home. This year saw us ensure fairness. We also believe ourto sell products, which can result in mis- launch 95% Loan-to-Value lending outside commitment to fair lending and fairsellin

====================================================================================================
Company: Barclays plc
Keyword: fairness
Page: 238
----------------------------------------------------------------------------------------------------
p's business, such as those related tofinancial harm. risks from competitors. algorithmic fairness, data life-cycle A successful cyber attack may result in management, data ethics, data privacy and d) Fraud significant fines and penalties to the Group. security and records management (e.g. the The nature of

Some fairness related matches were not AI-specific and were therefore treated cautiously during manual validation.

In [11]:
# Manual validation outcome for Barclays

manual_review.loc[
    manual_review["company_id"] == "001",
    "manual_adjusted_score"
] = 12

manual_review.loc[
    manual_review["company_id"] == "001",
    "manual_adjusted_percentage"
] = 85.71

manual_review.loc[
    manual_review["company_id"] == "001",
    "reason_for_adjustment"
] = (
    "No adjustment made. Barclays shows meaningful AI transparency evidence, "
    "including Ethical AI Principles, AI Policy references, model strategy and oversight language, "
    "AI bias and hallucination risks, generative AI, agentic AI, machine learning and AI-related risk controls. "
    "However, some fairness matches were not AI-specific and relate instead to remuneration, employees or fair lending, "
    "so fairness evidence was treated cautiously."
)

manual_review.loc[
    manual_review["company_id"] == "001",
    "important_pages"
] = "183, 233, 238-241, 253, 342, 355, 382"

manual_review.loc[
    manual_review["company_id"] == "001",
    "important_extracts"
] = (
    "References to Ethical AI Principles, AI Policy, AI bias, hallucinations, "
    "generative AI, agentic AI, machine learning, AI-related risk controls and AI/ML initiatives."
)

manual_review.loc[
    manual_review["company_id"] == "001",
    "review_status"
] = "Reviewed - provisional score retained"

manual_review.to_csv(
    manual_review_file,
    index=False
)

manual_review[manual_review["company_id"] == "001"]

,company_id,company_name,total_ai_transparency_mentions,unique_keywords,unique_pages,total_score,score_percentage,manual_adjusted_score,manual_adjusted_percentage,reason_for_adjustment,important_pages,important_extracts,review_status
1,001,Barclays plc,249,10,60,12,85.71,12.0,85.71,"No adjustment made. Barclays shows meaningful AI transparency evidence, including Ethical AI Principles, AI Policy references, model strategy and oversight language, AI bias and hallucination risks, generative AI, agentic AI, machine learning and AI-related risk controls. However, some fairness matches were not AI-specific and relate instead to remuneration, employees or fair lending, so fairness evidence was treated cautiously.","183, 233, 238-241, 253, 342, 355, 382","References to Ethical AI Principles, AI Policy, AI bias, hallucinations, generative AI, agentic AI, machine learning, AI-related risk controls and AI/ML initiatives.",Reviewed - provisional score retained

In [12]:
# Admiral keyword count review

admiral_keyword_counts = (
    ai_mentions[ai_mentions["company_id"] == "009"]
    .groupby("keyword")
    .agg(
        mention_count=("keyword", "count"),
        unique_pages=("page_number", "nunique")
    )
    .reset_index()
    .sort_values(by="mention_count", ascending=False)
)

admiral_keyword_counts

                   keyword  mention_count  unique_pages
0                       AI             71            34
1  artificial intelligence              8             6
7           responsible AI              7             4
4                 fairness              5             5
6         machine learning              5             4
2               automation              3             3
5            generative AI              3             3
3                     bias              1             1

In [13]:
print_company_evidence(
    company_id="009",
    keywords=[
        "artificial intelligence",
        "machine learning",
        "generative AI",
        "responsible AI",
        "AI ethics",
        "ethical AI",
        "human oversight",
        "human review",
        "human-in-the-loop",
        "automated decision-making",
        "bias",
        "fairness"
    ],
    max_items=35
)

====================================================================================================
Company: Admiral Group plc
Keyword: artificial intelligence
Page: 10
----------------------------------------------------------------------------------------------------
ese shifts by leveraging our strengths across customer centricity, underwriting excellence, agility, and innovation. Generative and agentic UK direct insurance market artificial intelligence Generative and agentic artificial intelligence (‘AI’) is Over the past ten years, the UK direct insurance market fundamentally reshaping consumer behaviours across has demonstrated consistent growth,

====================================================================================================
Company: Admiral Group plc
Keyword: artificial intelligence
Page: 10
----------------------------------------------------------------------------------------------------
stomer centricity, underwriting excellence, agility, and innovation. Generative and agentic UK direct insurance market artificial intelligence Generative and agentic artificial intelligence (‘AI’) is Over the past ten years, the UK direct insurance market fundamentally reshaping consumer behaviours across has demonstrated consistent growth, with medium-term industries, with potential imp

====================================================================================================
Company: Admiral Group plc
Keyword: artificial intelligence
Page: 19
----------------------------------------------------------------------------------------------------
nce model. diversified products, and operational expertise to drive greater efficiency, economies of scale, and stronger We accelerated our investment in artificial intelligence and customer retention across single and multi-product policies. established a GenAI Centre of Excellence that is scaling We p

====================================================================================================
Company: Admiral Group plc
Keyword: artificial intelligence
Page: 21
----------------------------------------------------------------------------------------------------
Financial Statements Additional Information Championing Responsible AI deployment for scalable success Across the Group, we are committed to working with a range of stakeholders to ensure that artificial intelligence (‘AI’) is implemented responsibly. In October, our Head of Group Responsible AI and Data, David Crelley, took part in a panel decision at Momentum AI London. Momentum AI is a two-day event designed to equip busines

====================================================================================================
Company: Admiral Group plc
Keyword: artificial intelligence
Page: 44
----------------------------------------------------------------------------------------------------
Strategic Report Corporate Governance Financial Statements Additional Information How our ‘20% Projects’ power people, progress and problem-solving Using data and artificial intelligence (‘AI’) to make our colleagues’ and customers’ lives easier is a key priority for us. In the UK, we’ve launched our 20% Projects programme, which is a cross-functional initiative that provides colleagues with the o

====================================================================================================
Company: Admiral Group plc
Keyword: artificial intelligence
Page: 130
----------------------------------------------------------------------------------------------------
ighlighted the strategic opportunities presented by electric mobility and evolving green policies. Technology and Discussions emphasised the integration of artificial intelligence as a key lever for artificial intelligence accelerating innovation. Data protection was also identified as a key priority, with recognition of the need fo

====================================================================================================
Company: Admiral Group plc
Keyword: artificial intelligence
Page: 130
----------------------------------------------------------------------------------------------------
mobility and evolving green policies. Technology and Discussions emphasised the integration of artificial intelligence as a key lever for artificial intelligence accelerating innovation. Data protection was also identified as a key priority, with recognition of the need for sustained investment to mitigate increasing cyber

====================================================================================================
Company: Admiral Group plc
Keyword: artificial intelligence
Page: 157
----------------------------------------------------------------------------------------------------
ed with a paper on electric vehicles, noting the and Corporate Transparency Act (‘ECCTA’). potential impact of trade policy and tariffs on the supply Artificial intelligence (‘AI’) of Chinese EVs, as well as potential opportunities surrounding working with OEMs. The Committee also The Committee received regular updates regarding reviewed economic risks more broadly, completing its

====================================================================================================
Company: Admiral Group plc
Keyword: bias
Page: 206
----------------------------------------------------------------------------------------------------
raud through management override of controls, testing the appropriateness of journal entries and other adjustments; assessing whether the judgements made in making accounting estimates are indicative of a potential bias; and evaluating the business rationale of any significant transactions that are unusual or outside the normal course of business. We also communicated relevant identified laws and regulations and potential fraud ris

====================================================================================================
Company: Admiral Group plc
Keyword: fairness
Page: 66
----------------------------------------------------------------------------------------------------
the same: to use innovation responsibly and inclusively. • Admiral colleagues achieved industry-leading By focusing on fairness, security, and accessibility, certifications like CISSP and CISM, with others we build trust with customers, empower colleagues, pursuing postgraduate degrees in cyber secu

====================================================================================================
Company: Admiral Group plc
Keyword: fairness
Page: 67
----------------------------------------------------------------------------------------------------
For climate risk specifically, we align with the IIGCC Net Zero Investment Framework. In 2025, we continued to • Value means fairness and relevance, offering competitive strengthen this approach by maintaining exclusions for prices and products designed to meet diverse needs

====================================================================================================
Company: Admiral Group plc
Keyword: fairness
Page: 110
----------------------------------------------------------------------------------------------------
roduction of a new reward framework to oversee a rapidly evolving business landscape. for our UK colleagues. This project, designed to ensure More information on these appointments and what they fairness, transparency, and alignment with Admiral’s bring to the business can be found on pages 119 and 134. purpose and values, involved discussion and challenge At the executive level, we welcomed a new CEO at Admiral

====================================================================================================
Company: Admiral Group plc
Keyword: fairness
Page: 157
----------------------------------------------------------------------------------------------------
ee reviewed the risk-based and trust-by-design approach rolled out across the Group, discussing topics such as fairness, openness, transparency, and ethics. These discussions reflect the Committee's ongoing role in

====================================================================================================
Company: Admiral Group plc
Keyword: fairness
Page: 186
----------------------------------------------------------------------------------------------------
ne basis. Data for the measures is taken from the Group’s financial reports, which are reviewed by the Audit Committee and approved by the Board. Phase 2: Holistic review. The Committee will then consider the overall fairness of the formulaic Group scorecard outcome in the context of the business performance in the prevailing market conditions, which can be assessed against a non- exhaustive basket of measures such as: • Executive Direct

====================================================================================================
Company: Admiral Group plc
Keyword: generative AI
Page: 93
----------------------------------------------------------------------------------------------------
The Board also monitored the rollout of new technology journey. Engagement is supported through multiple channels, strategies, including generative AI, which improved including digital platforms (customer portals, surveys, SMS customer journeys through greater personalisation and feedback, and the Admiral App), li

====================================================================================================
Company: Admiral Group plc
Keyword: generative AI
Page: 99
----------------------------------------------------------------------------------------------------
conditions and the development and broader adoption of new and emerging technologies such as fully autonomous emerging risks facing the Group vehicles (‘AVs’), generative AI, and quantum computing. alongside engaging with the This volatility has foregrounded the role of operational resilience and cyber-secur

====================================================================================================
Company: Admiral Group plc
Keyword: generative AI
Page: 130
----------------------------------------------------------------------------------------------------
ction and contextual clarity in others. AECS – Impact of AI and The IECG confirmed a positive trajectory, noting the launch of predictive AI models September Company ambition and the implementation of generative AI across claims, IT, pricing, risk selection, 2025 productivity, and internal operations. These advancements were viewed as the start of a

====================================================================================================
Company: Admiral Group plc
Keyword: machine learning
Page: 19
----------------------------------------------------------------------------------------------------
I am confident Admiral is well-positioned for success strengths in data and telematics mean we are well-placed in 2026 and beyond. to respond to evolving mobility trends. We invested early and effectively in machine learning and predictive AI, strengthening our leadership in underwriting with over 120 models live, one of the drivers of our twelve points advantage in loss ratio versus the market. We have fully embedded scaled agile and r

====================================================================================================
Company: Admiral Group plc
Keyword: machine learning
Page: 22
----------------------------------------------------------------------------------------------------
• We have strengthened our UK car pricing capabilities fewer repeat contacts. Veybot has improved service by refreshing our key machine learning models for both speed and quality for customers risk and retail pricing, helping us to predict claims costs • The UK Insurance business has

====================================================================================================
Company: Admiral Group plc
Keyword: machine learning
Page: 22
----------------------------------------------------------------------------------------------------
osts • The UK Insurance business has made progress with their and market prices more accurately. Together, these cloud platforms, with more than 90% of core systems enhancements build on our established machine learning- now cloud-based enabling faster, and improved data driven pricing approach, improving both accuracy, quality. Data requests are now allocated and completed and competitiveness more efficiently, w

====================================================================================================
Company: Admiral Group plc
Keyword: machine learning
Page: 36
----------------------------------------------------------------------------------------------------
but our strong team and fundamentals give us a great customers with two or more risks. We’ve built strong platform to continue to provide value, trust, and ease capability in predictive AI, accelerating machine learning for customers and in doing so, make the most of our model deployment in pricing and claims. In 2025, we laid opportunities for sustainable profitable growth in 2026 good foundations in GenAI and Agentic

====================================================================================================
Company: Admiral Group plc
Keyword: machine learning
Page: 49
----------------------------------------------------------------------------------------------------
ets. Today, I am a Software particularly on business written in 2023. Strong pricing Architect in the Gold Standard Pricing team, where and underwriting actions taken throughout 2024 and in we analyse machine learning models to identify 2025 show signs of significantly improved loss ratios, patterns in customer data so that we can better serve which are now starting to earn through. Vehicles insured our customer

====================================================================================================
Company: Admiral Group plc
Keyword: responsible AI
Page: 21
----------------------------------------------------------------------------------------------------
Strategic Report Corporate Governance Financial Statements Additional Information Championing Responsible AI deployment for scalable success Across the Group, we are committed to working with a range of stakeholders to ensure that artificial intelligence (‘AI’) is implemented responsibly. In October, our Head of Group Res

====================================================================================================
Company: Admiral Group plc
Keyword: responsible AI
Page: 21
----------------------------------------------------------------------------------------------------
AI deployment for scalable success Across the Group, we are committed to working with a range of stakeholders to ensure that artificial intelligence (‘AI’) is implemented responsibly. In October, our Head of Group Responsible AI and Data, David Crelley, took part in a panel decision at Momentum AI London. Momentum AI is a two-day event designed to equip business executives with cutting-edge strategies to build scalable generative and agent

====================================================================================================
Company: Admiral Group plc
Keyword: responsible AI
Page: 21
----------------------------------------------------------------------------------------------------
le importance of working with regulators, such as the Financial that our Data and AI Academy plays in helping colleagues Conduct Authority and Prudential Regulation Authority, across the Group to understand responsible AI and the as well as the Association of British Insurers, to develop importance of collaboration across all functions to ensure safe and practical governance standards for the financial colleagues are empow

====================================================================================================
Company: Admiral Group plc
Keyword: responsible AI
Page: 52
----------------------------------------------------------------------------------------------------
ion related to the In October, our Group Company Secretary More Than acquisition, whilst 2025 comprises increased team and Responsible AI and Data team spend on alternative lending products such as secured homeowner loans in the UK. were acknowledged for their outstanding effor

====================================================================================================
Company: Admiral Group plc
Keyword: responsible AI
Page: 52
----------------------------------------------------------------------------------------------------
14 prior innovation, and integrating AI into board operations, to redemption. while our Responsible AI and Data team were Highly Commended at the DataIQ awards for the way that they ensure that AI is used responsibly

====================================================================================================
Company: Admiral Group plc
Keyword: responsible AI
Page: 58
----------------------------------------------------------------------------------------------------
2025: 21.6 India’s Best Workplaces Highly Commended 2024: 24.2 for Women™ Great Place Responsible AI Initiative 2023: 24.3 to Work® DataIQ Awards 2022: 21.0 ISS ESG

====================================================================================================
Company: Admiral Group plc
Keyword: responsible AI
Page: 66
----------------------------------------------------------------------------------------------------
ainability and Privacy monitoring of data quality across the business. This helps Initiative of the Year and a Data IQ Highly Commended ensure that our data is accurate, consistent, and reliable – Award for Responsible AI. essential for compliance and for delivering the best outcomes for our customers. Empowering our people Technology is changing f

In [14]:
# Ensuring manual review columns can hold text values
text_columns = [
    "reason_for_adjustment",
    "important_pages",
    "important_extracts",
    "review_status"
]

for col in text_columns:
    if col not in manual_review.columns:
        manual_review[col] = ""
    manual_review[col] = manual_review[col].astype("object")

numeric_columns = [
    "manual_adjusted_score",
    "manual_adjusted_percentage"
]

for col in numeric_columns:
    if col not in manual_review.columns:
        manual_review[col] = pd.NA

# Make sure company IDs are treated consistently
manual_review["company_id"] = manual_review["company_id"].astype(str).str.zfill(3)

# Record manual validation outcome for Admiral Group
admiral_mask = manual_review["company_id"] == "009"

manual_review.loc[
    admiral_mask,
    "manual_adjusted_score"
] = 11

manual_review.loc[
    admiral_mask,
    "manual_adjusted_percentage"
] = 78.57

manual_review.loc[
    admiral_mask,
    "reason_for_adjustment"
] = (
    "No adjustment made. Admiral Group shows strong AI transparency evidence, including responsible AI, "
    "AI governance standards, artificial intelligence, generative AI, agentic AI, machine learning, predictive AI, "
    "and AI use across pricing, claims, underwriting, customer retention, data quality and internal operations. "
    "The provisional score is retained because the evidence supports AI use, business application, risk, governance, "
    "ethics/fairness and specificity. However, explicit human oversight or human-in-the-loop controls were not clearly disclosed."
)

manual_review.loc[
    admiral_mask,
    "important_pages"
] = "10, 19, 21, 22, 36, 44, 49, 66, 99, 130, 157"

manual_review.loc[
    admiral_mask,
    "important_extracts"
] = (
    "Responsible AI deployment, AI governance standards, GenAI Centre of Excellence, generative and agentic AI, "
    "machine learning in pricing, predictive AI models, claims, risk selection, customer retention, data quality, "
    "fairness, openness, transparency and ethics."
)

manual_review.loc[
    admiral_mask,
    "review_status"
] = "Reviewed - provisional score retained"

manual_review.to_csv(
    manual_review_file,
    index=False
)

manual_review[manual_review["company_id"] == "009"]

,company_id,company_name,total_ai_transparency_mentions,unique_keywords,unique_pages,total_score,score_percentage,manual_adjusted_score,manual_adjusted_percentage,reason_for_adjustment,important_pages,important_extracts,review_status
2,009,Admiral Group plc,103,8,39,11,78.57,11.0,78.57,"No adjustment made. Admiral Group shows strong AI transparency evidence, including responsible AI, AI governance standards, artificial intelligence, generative AI, agentic AI, machine learning, predictive AI, and AI use across pricing, claims, underwriting, customer retention, data quality and internal operations. The provisional score is retained because the evidence supports AI use, business application, risk, governance, ethics/fairness and specificity. However, explicit human oversight or human-in-the-loop controls were not clearly disclosed.","10, 19, 21, 22, 36, 44, 49, 66, 99, 130, 157","Responsible AI deployment, AI governance standards, GenAI Centre of Excellence, generative and agentic AI, machine learning in pricing, predictive AI models, claims, risk selection, customer retention, data quality, fairness, openness, transparency and ethics.",Reviewed - provisional score retained

In [15]:
# Funding Circle keyword count review

funding_circle_keyword_counts = (
    ai_mentions[ai_mentions["company_id"] == "016"]
    .groupby("keyword")
    .agg(
        mention_count=("keyword", "count"),
        unique_pages=("page_number", "nunique")
    )
    .reset_index()
    .sort_values(by="mention_count", ascending=False)
)

funding_circle_keyword_counts

                   keyword  mention_count  unique_pages
0                       AI             91            27
2               automation              3             3
3                     bias              3             2
1  artificial intelligence              2             2
7         machine learning              2             2
4                 fairness              1             1
5            generative AI              1             1
6        human-in-the-loop              1             1

In [16]:
print_company_evidence(
    company_id="016",
    keywords=[
        "artificial intelligence",
        "machine learning",
        "generative AI",
        "responsible AI",
        "AI ethics",
        "ethical AI",
        "human oversight",
        "human review",
        "human-in-the-loop",
        "automated decision-making",
        "bias",
        "fairness"
    ],
    max_items=35
)

====================================================================================================
Company: Funding Circle Holdings plc
Keyword: artificial intelligence
Page: 59
----------------------------------------------------------------------------------------------------
ats: the dual nature of AI environment. By maintaining a disciplined and cybersecurity approach to risk while responsibly risk landscape of 2026.” Artificial intelligence is reshaping financial embracing innovation, we will support services. For us, AI is a powerful lever UK SMEs through the cycle and create

====================================================================================================
Company: Funding Circle Holdings plc
Keyword: artificial intelligence
Page: 63
----------------------------------------------------------------------------------------------------
ness. Risk appetite We will make efficient use of our available resources to build a sustainable, diversified and profitable business that can successfully adapt to environment and technological changes (in particular artificial intelligence (‘‘AI’’)), and respond adequately to competition pressures. Risk(s) and potential impact Key risk considerations and mitigation actions Strategy execution Risk that we are unable to effectively

====================================================================================================
Company: Funding Circle Holdings plc
Keyword: bias
Page: 30
----------------------------------------------------------------------------------------------------
ed groups to hire and promote top talent, based on Our Circler-led groups are at the forefront of performance and potential, while mitigating our culture, driving the initiatives that make bias and ensuring we attract diverse Funding Circle unique. 2025 highlights applicants. This is also supported by our included Circle of Pride, spotlighting Female Empowerment Programme, now queer-owned small busi

====================================================================================================
Company: Funding Circle Holdings plc
Keyword: bias
Page: 125
----------------------------------------------------------------------------------------------------
ements (including the risk of override of controls), Under the Companies Act 2006 we are required to report to and determined that the principal risks were related to bias you if, in our opinion: in accounting estimates and posting of journal entries to manipulate financial performance. Audit procedures l we have not obtained a

====================================================================================================
Company: Funding Circle Holdings plc
Keyword: bias
Page: 125
----------------------------------------------------------------------------------------------------
mptions and judgements made interest entity for eight of those financial years. by management in its accounting estimates and assessing them for bias, including those relating to the allowance for Other matter expected credit losses for FlexiPay lines of credit and The C

====================================================================================================
Company: Funding Circle Holdings plc
Keyword: fairness
Page: 31
----------------------------------------------------------------------------------------------------
34% 2021 21% 2021 32% 2021 31% Diversity, Equity and Inclusion (“DEI”) Statement our customers, we back our people by ensuring fairness ‘On A Mission, together’ iscompensationwoven into everythingto career development.we do, from recruitmentThis includesand ensuring all application

====================================================================================================
Company: Funding Circle Holdings plc
Keyword: generative AI
Page: 8
----------------------------------------------------------------------------------------------------
ives long-term profitability. In 2025, the Board’s oversight focused multi-product platform on ensuring that the Group successfully Our ongoing investment in Generative AI (“Gen AI”) applications is enhancing our secures Funding Circle’s transitioned from its 2024 reset into a ability to sca

====================================================================================================
Company: Funding Circle Holdings plc
Keyword: human-in-the-loop
Page: 66
----------------------------------------------------------------------------------------------------
tems or from external events. This definition includes operational failures resulting from the use of AI systems, such as flawed model outputs leading to poor business decisions, process automation failures, inadequate ‘human-in-the-loop’ oversight, or fraud losses resulting from AI enabled attacks. Risk appetite Funding Circle will operate well managed processes with reliable performance and effective controls preventing significant and non-anticipate

====================================================================================================
Company: Funding Circle Holdings plc
Keyword: machine learning
Page: 24
----------------------------------------------------------------------------------------------------
perior customer experience Frictionless digital experience Automated decision engine Our highly flexible interface provides At the heart of our platform, machine learning an intuitive experience across desktop models automate complex underwriting and mobile. As we have expanded our tasks. This enables SMEs to a

====================================================================================================
Company: Funding Circle Holdings plc
Keyword: machine learning
Page: 68
----------------------------------------------------------------------------------------------------
tfolio level in line with Funding Circle management’s expectations, in terms of net loss rate, risk-adjusted rate of return and volatility through economic cycles. This includes management of potential risks from AI and machine learning (‘‘ML’’) models integrated in the credit risk assessment. Risk appetite Whether or not Funding Circle owns any credit risk, credit risk resulting from our lending activities will be managed with the utmost care and att

In [17]:
# Ensuring manual review columns can hold text values
text_columns = [
    "reason_for_adjustment",
    "important_pages",
    "important_extracts",
    "review_status"
]

for col in text_columns:
    if col not in manual_review.columns:
        manual_review[col] = ""
    manual_review[col] = manual_review[col].astype("object")

numeric_columns = [
    "manual_adjusted_score",
    "manual_adjusted_percentage"
]

for col in numeric_columns:
    if col not in manual_review.columns:
        manual_review[col] = pd.NA

# Make sure company IDs are treated consistently
manual_review["company_id"] = manual_review["company_id"].astype(str).str.zfill(3)

# Record manual validation outcome for Funding Circle
funding_circle_mask = manual_review["company_id"] == "016"

manual_review.loc[
    funding_circle_mask,
    "manual_adjusted_score"
] = 9

manual_review.loc[
    funding_circle_mask,
    "manual_adjusted_percentage"
] = 64.29

manual_review.loc[
    funding_circle_mask,
    "reason_for_adjustment"
] = (
    "No adjustment made. Funding Circle shows relevant AI transparency evidence,machine learning, an automated decision engine, AI/ML models used in credit risk assessment, and AI-related risk language. "
    "The report also refers to risks from flawed AI model outputs, process automation failures, AI-enabled fraud and inadequate "
    "human-in-the-loop oversight. However, the evidence remains weaker on detailed AI governance, AI-specific fairness and "
    "clear operational human review controls."
)

manual_review.loc[
    funding_circle_mask,
    "important_pages"
] = "8, 24, 31, 59, 63, 66, 68, 125"

manual_review.loc[
    funding_circle_mask,
    "important_extracts"
] = (
    "Generative AI applications, machine learning, automated decision engine, complex underwriting, AI/ML models in credit risk "
    "assessment, AI-related operational risk, flawed model outputs, process automation failures, AI-enabled fraud, human-in-the-loop "
    "oversight, fairness and bias references."
)

manual_review.loc[
    funding_circle_mask,
    "review_status"
] = "Reviewed - provisional score retained"

manual_review.to_csv(
    manual_review_file,
    index=False
)

manual_review[manual_review["company_id"] == "016"]

,company_id,company_name,total_ai_transparency_mentions,unique_keywords,unique_pages,total_score,score_percentage,manual_adjusted_score,manual_adjusted_percentage,reason_for_adjustment,important_pages,important_extracts,review_status
3,016,Funding Circle Holdings plc,104,8,30,9,64.29,9.0,64.29,"No adjustment made. Funding Circle shows relevant AI transparency evidence,machine learning, an automated decision engine, AI/ML models used in credit risk assessment, and AI-related risk language. The report also refers to risks from flawed AI model outputs, process automation failures, AI-enabled fraud and inadequate human-in-the-loop oversight. However, the evidence remains weaker on detailed AI governance, AI-specific fairness and clear operational human review controls.","8, 24, 31, 59, 63, 66, 68, 125","Generative AI applications, machine learning, automated decision engine, complex underwriting, AI/ML models in credit risk assessment, AI-related operational risk, flawed model outputs, process automation failures, AI-enabled fraud, human-in-the-loop oversight, fairness and bias references.",Reviewed - provisional score retained

In [18]:
# HSBC keyword count review

hsbc_keyword_counts = (
    ai_mentions[ai_mentions["company_id"] == "002"]
    .groupby("keyword")
    .agg(
        mention_count=("keyword", "count"),
        unique_pages=("page_number", "nunique")
    )
    .reset_index()
    .sort_values(by="mention_count", ascending=False)
)

hsbc_keyword_counts

                   keyword  mention_count  unique_pages
0                       AI             75            29
2  artificial intelligence              5             5
8         machine learning              4             3
3               automation              4             4
4                     bias              4             4
6            generative AI              4             4
5                 fairness              3             3
1                AI ethics              1             1
7     large language model              1             1
9           responsible AI              1             1

In [19]:
print_company_evidence(
    company_id="002",
    keywords=[
        "artificial intelligence",
        "machine learning",
        "generative AI",
        "responsible AI",
        "AI ethics",
        "ethical AI",
        "human oversight",
        "human review",
        "human-in-the-loop",
        "automated decision-making",
        "bias",
        "fairness"
    ],
    max_items=35
)

====================================================================================================
Company: HSBC Holdings plc
Keyword: AI ethics
Page: 58
----------------------------------------------------------------------------------------------------
et future challenges. and their level of AI involvement. It provides comprehensive training on AI literacy, Establishing our leadership framework responsible AI, and AI ethics, with To support our refreshed strategy and participants earning badges to recognise their ambition, a cross-section of business leaders achievements. In 2025, we piloted the AI developed and launched a

====================================================================================================
Company: HSBC Holdings plc
Keyword: artificial intelligence
Page: 13
----------------------------------------------------------------------------------------------------
source of funding for us, and forms the Hongkong and Shanghai Banking Corporation foundation of our financial stability. Limited, HSBC UK and HSBC Bank plc. Improving operational excellence through artificial intelligence In 2025, we accelerated the adoption of tool, HSBC Productivity Suite, which helps colleagues, and drive performance. Through Generative AI (‘GenAI’) across HSBC, moving them to analyse and translate

====================================================================================================
Company: HSBC Holdings plc
Keyword: artificial intelligence
Page: 61
----------------------------------------------------------------------------------------------------
e human rights audits of suppliers HSBC’s Principles for the Ethical Use of Data 4,100 (a more than 15% increase since last and closed out findings from the 2024 audits. and Artificial Intelligence include how we seek year) survivors of modern slavery and human to respect the right to privacy while making trafficking in the UK.We use independent negative

====================================================================================================
Company: HSBC Holdings plc
Keyword: artificial intelligence
Page: 191
----------------------------------------------------------------------------------------------------
businesses on digital transformation. developers and independent software – Independent non-executive vendors and artificial intelligence Director of Forrit Holdings Limited solutions. – Member of Advisory Board of

====================================================================================================
Company: HSBC Holdings plc
Keyword: artificial intelligence
Page: 365
----------------------------------------------------------------------------------------------------
esult in our failure to achieve any of the expected outcomes of our strategic priorities and may result in reputational risks; evolving regulatory requirements and the development of new technologies, including artificial intelligence, affecting how we manage risk, including model risk; model limitations or failure, including, without limitation, the impact that high inflationary pressures and interest rates have had on the performance a

====================================================================================================
Company: HSBC Holdings plc
Keyword: artificial intelligence
Page: 368
----------------------------------------------------------------------------------------------------
ange in expected credit losses and other AGM Annual General Meeting credit impairment charges. In the balance sheet, ECL is AI Artificial intelligence recorded as an allowance for financial instruments to which o

====================================================================================================
Company: HSBC Holdings plc
Keyword: bias
Page: 55
----------------------------------------------------------------------------------------------------
ce in average pay ethnicity pay gap was 9.8% (2024: 7.7%). have processes to review that remuneration is between these groups of people and the free from bias. We review our pay practices These gaps are primarily driven by workforce wider workforce, regardless of their role or r

====================================================================================================
Company: HSBC Holdings plc
Keyword: bias
Page: 258
----------------------------------------------------------------------------------------------------
these methodologies when forecasting the extent and timing of future significant assumptions would give rise to indicators of possible customer defaults or when responding to emerging risks, such as management bias. climate risk. The focus of our assessment of the impact of climate risk In respect of the Hong Kong commercial real estate portfolio, we had on ECL was to evaluate management’s risk assessment process for ove

====================================================================================================
Company: HSBC Holdings plc
Keyword: bias
Page: 259
----------------------------------------------------------------------------------------------------
significant assumptions would give rise to indicators of possible – the discount rate; management bias; – short-to-medium term assumptions for operating income growth – attending certain meetings alongside management and BoCom rate, loans and advances

====================================================================================================
Company: HSBC Holdings plc
Keyword: bias
Page: 261
----------------------------------------------------------------------------------------------------
that the principal risks were related to posting inappropriate journal entries in relation to costs and income, and management bias in Based on our understanding of the Group and industry, we identified accounting estimates, particularly those related to the valuation of that the pr

====================================================================================================
Company: HSBC Holdings plc
Keyword: fairness
Page: 35
----------------------------------------------------------------------------------------------------
57 Building customer inclusion and resilience 57 Engaging with our communities Governance 58 Setting high standards of governance 59 Human rights 60 Customer experience 62 Integrity, conduct and fairness 64 Safeguarding data HSBC Holdings plc Annual Report and Accounts 2025 33 2

====================================================================================================
Company: HSBC Holdings plc
Keyword: fairness
Page: 64
----------------------------------------------------------------------------------------------------
Additional Governance Report statements information Governance Integrity, conduct and fairness Safeguarding the financial system We have continued our efforts to combat Our anti-bribery and corruption policy financial crime and reduce its impact on our We are required to comply with all applicable organis

====================================================================================================
Company: HSBC Holdings plc
Keyword: fairness
Page: 211
----------------------------------------------------------------------------------------------------
election and and exit management process. This work has ensured that the policies, – overseeing the Group’s approach to conduct, fairness and the controls and procedures relating to anti-money laundering, sanctions, prevention of financial crime.

====================================================================================================
Company: HSBC Holdings plc
Keyword: generative AI
Page: 13
----------------------------------------------------------------------------------------------------
Bank plc. Improving operational excellence through artificial intelligence In 2025, we accelerated the adoption of tool, HSBC Productivity Suite, which helps colleagues, and drive performance. Through Generative AI (‘GenAI’) across HSBC, moving them to analyse and translate documents, 2026, we intend to expand enterprise-wide from experimentation to scaled delivery. summarise information and generate insights. adopt

====================================================================================================
Company: HSBC Holdings plc
Keyword: generative AI
Page: 104
----------------------------------------------------------------------------------------------------
the importance of nature-related risks, as well as the fraud and protecting customers. The accessibility and increasing complex interactions and compounding effects of climate and nature- sophistication of Generative AI (‘GenAI’) can create additional financial related risk drivers. Nature-related risks may emerge when crime risks. While there is potential for the technology to support dependencies on natural capital – su

====================================================================================================
Company: HSBC Holdings plc
Keyword: generative AI
Page: 217
----------------------------------------------------------------------------------------------------
Group Technology & Operations Committee Principal activities and significant issues considered during 2025 (continued) Area of focus Key issues Conclusions and actions Generative AI While GenAI will provide operational – The GTO reviewed and challenged strategies to leverage the opportunities presented by innovation and strategy efficiency, none of the use cases in new technolo

====================================================================================================
Company: HSBC Holdings plc
Keyword: generative AI
Page: 368
----------------------------------------------------------------------------------------------------
GDP Gross domestic product BVI British Virgin Islands GenAI Generative AI C GHG Greenhouse Gas CAPM Capital asset pricing model GPS Global Payments

====================================================================================================
Company: HSBC Holdings plc
Keyword: machine learning
Page: 105
----------------------------------------------------------------------------------------------------
and analytics infrastructure Mitigating actions through investments in cloud technology, data visualisation, machine learning and AI. – We continue to monitor this emerging risk and advances in – We provide regular mandatory training globally to educate our technology, as well

====================================================================================================
Company: HSBC Holdings plc
Keyword: machine learning
Page: 106
----------------------------------------------------------------------------------------------------
k for transformative initiatives. Additionally, the HSBC Holdings Board provides enhanced oversight over the simplification Focus remains on AI and machine learning models given the rapid pace programme, directly supervising its mobilisation and delivery. of technological advances, including the development of GenAI and

====================================================================================================
Company: HSBC Holdings plc
Keyword: machine learning
Page: 183
----------------------------------------------------------------------------------------------------
nued enhancements to our framework for the independent We use a variety of modelling approaches, including regression, validation of models, including new GenAI techniques that are simulation, sampling, machine learning and judgemental scorecards for a becoming more widely used; and range of business applications. These activities include customer

====================================================================================================
Company: HSBC Holdings plc
Keyword: machine learning
Page: 183
----------------------------------------------------------------------------------------------------
rk to manage the range of risks for managing model risk is delegated from the Board to the Group Chief these AI techniques, including machine learning and agentic AI Risk and Compliance Officer, who authorises the Group Model Risk (autonomous systems powered by AI agents), can introduce.

====================================================================================================
Company: HSBC Holdings plc
Keyword: responsible AI
Page: 58
----------------------------------------------------------------------------------------------------
preparing them to meet future challenges. and their level of AI involvement. It provides comprehensive training on AI literacy, Establishing our leadership framework responsible AI, and AI ethics, with To support our refreshed strategy and participants earning badges to recognise their ambition, a cross-section of business leaders achievements. In 2025, we piloted the AI developed

In [20]:
# Ensuring manual review columns can hold text values
text_columns = [
    "reason_for_adjustment",
    "important_pages",
    "important_extracts",
    "review_status"
]

for col in text_columns:
    if col not in manual_review.columns:
        manual_review[col] = ""
    manual_review[col] = manual_review[col].astype("object")

numeric_columns = [
    "manual_adjusted_score",
    "manual_adjusted_percentage"
]

for col in numeric_columns:
    if col not in manual_review.columns:
        manual_review[col] = pd.NA

# Make sure company IDs are treated consistently
manual_review["company_id"] = manual_review["company_id"].astype(str).str.zfill(3)

# Record manual validation outcome for HSBC
hsbc_mask = manual_review["company_id"] == "002"

manual_review.loc[
    hsbc_mask,
    "manual_adjusted_score"
] = 12

manual_review.loc[
    hsbc_mask,
    "manual_adjusted_percentage"
] = 85.71

manual_review.loc[
    hsbc_mask,
    "reason_for_adjustment"
] = (
    "Score increased from provisional automated score. HSBC shows strong evidence of AI transparency through operational GenAI "
    "adoption, HSBC Productivity Suite, machine learning, AI-supported operational excellence, model risk governance, Board and "
    "committee oversight, responsible AI, AI ethics and AI literacy training. However, direct evidence of human-in-the-loop review "
    "for AI decisions is limited, and some bias/fairness matches relate to general conduct, pay or accounting fairness rather than "
    "AI-specific fairness."
)

manual_review.loc[
    hsbc_mask,
    "important_pages"
] = "13, 58, 61, 105, 106, 183, 217, 368"

manual_review.loc[
    hsbc_mask,
    "important_extracts"
] = (
    "HSBC Productivity Suite, Generative AI adoption, document analysis and translation, machine learning, GenAI techniques, "
    "model validation, model risk, Group Model Risk, Board oversight, Group Technology & Operations Committee review, responsible AI, "
    "AI ethics, AI literacy training, ethical use of data, AI and machine learning risk monitoring."
)

manual_review.loc[
    hsbc_mask,
    "review_status"
] = "Reviewed - score increased"

manual_review.to_csv(
    manual_review_file,
    index=False
)

manual_review[manual_review["company_id"] == "002"]

,company_id,company_name,total_ai_transparency_mentions,unique_keywords,unique_pages,total_score,score_percentage,manual_adjusted_score,manual_adjusted_percentage,reason_for_adjustment,important_pages,important_extracts,review_status
4,002,HSBC Holdings plc,102,10,39,9,64.29,12.0,85.71,"Score increased from provisional automated score. HSBC shows strong evidence of AI transparency through operational GenAI adoption, HSBC Productivity Suite, machine learning, AI-supported operational excellence, model risk governance, Board and committee oversight, responsible AI, AI ethics and AI literacy training. However, direct evidence of human-in-the-loop review for AI decisions is limited, and some bias/fairness matches relate to general conduct, pay or accounting fairness rather than AI-specific fairness.","13, 58, 61, 105, 106, 183, 217, 368","HSBC Productivity Suite, Generative AI adoption, document analysis and translation, machine learning, GenAI techniques, model validation, model risk, Group Model Risk, Board oversight, Group Technology & Operations Committee review, responsible AI, AI ethics, AI literacy training, ethical use of data, AI and machine learning risk monitoring.",Reviewed - score increased

In [21]:
# Standard Chartered keyword count review

standard_chartered_keyword_counts = (
    ai_mentions[ai_mentions["company_id"] == "005"]
    .groupby("keyword")
    .agg(
        mention_count=("keyword", "count"),
        unique_pages=("page_number", "nunique")
    )
    .reset_index()
    .sort_values(by="mention_count", ascending=False)
)

standard_chartered_keyword_counts

                   keyword  mention_count  unique_pages
0                       AI             80            26
1  artificial intelligence              3             3
2               automation              3             2
4                 fairness              3             3
6           responsible AI              3             1
3                     bias              2             2
5            generative AI              1             1

In [22]:
print_company_evidence(
    company_id="005",
    keywords=[
        "artificial intelligence",
        "machine learning",
        "generative AI",
        "responsible AI",
        "AI ethics",
        "ethical AI",
        "human oversight",
        "human review",
        "human-in-the-loop",
        "automated decision-making",
        "bias",
        "fairness"
    ],
    max_items=35
)

====================================================================================================
Company: Standard Chartered plc
Keyword: artificial intelligence
Page: 148
----------------------------------------------------------------------------------------------------
ty, sustainability challenges and Group’s strategy, the activities of the Board leadership succession. committees and a keynote presentation on artificial intelligence and cyber governance. AGM The AGM, held on 8 May in 2025, was the Board’s Provided an opportunity for retail shareholders key opportunity for engagement with retail to engag

====================================================================================================
Company: Standard Chartered plc
Keyword: artificial intelligence
Page: 195
----------------------------------------------------------------------------------------------------
the traditional bank by addressing the Ventures and the rest digital banking and lifestyle needs of clients. of the Bank • Bill championed our Group approach to artificial intelligence (AI) with 15 themes identified for execution, including ‘MyWealth Advisor’ in Singapore and Hong Kong. • Continue to develop and • Bill continues to p

====================================================================================================
Company: Standard Chartered plc
Keyword: artificial intelligence
Page: 288
----------------------------------------------------------------------------------------------------
oducts and as geopolitical factors, Nth Party Risk and the risk arising business practices 1.5% 22.9% from adoption and use of Artificial Intelligence. This enables Damage to physical assets 0.0% 0.0% the Group to keep pace with new business developments,

====================================================================================================
Company: Standard Chartered plc
Keyword: bias
Page: 34
----------------------------------------------------------------------------------------------------
re in others, taking time Live with integrity, even when so we lead rather than react to listen to diverse viewpoints no one is watching. to change. and overcome bias. Think client, always considering the Simplify to make things easier, Ask how can I help? when people outcomes in whatever we are

====================================================================================================
Company: Standard Chartered plc
Keyword: bias
Page: 320
----------------------------------------------------------------------------------------------------
the current macroeconomic environment. In addition, we assessed whether there were any indicators of aggregate bias in financial instrument marking and methodology assumptions. We also assessed management’s disclosures regarding fa

====================================================================================================
Company: Standard Chartered plc
Keyword: fairness
Page: 187
----------------------------------------------------------------------------------------------------
irement, the deferral required will decrease to 15 per cent. Ensuring executive director remuneration is appropriate Executive director remuneration is reviewed annually against internal and external measures to ensure fairness and alignment with company performance and stakeholder interests. Internal External • We maintain a consistent remuneration approach • We review executive directo

====================================================================================================
Company: Standard Chartered plc
Keyword: fairness
Page: 199
----------------------------------------------------------------------------------------------------
y measure calculated as revenue/average controllable FTE Weighting – 10% Inclusion: Measured using the My Voice Inclusion Index, considering concepts of empathy, Weighting – 5% respect, fairness, growth, career development opportunities, and work-life balance 2026 scorecard – personal performance measures Bill • Continue to personally drive the execution of the growth strategy t

====================================================================================================
Company: Standard Chartered plc
Keyword: fairness
Page: 218
----------------------------------------------------------------------------------------------------
r approach total spend. aligns with leading industry standards, specifically the Monetary Authority of Singapore Fairness, Ethics,Our purchases of goods and services are governed through Accountability, and Transparency (MAS FEAT) and Honga third-party risk management framew

====================================================================================================
Company: Standard Chartered plc
Keyword: generative AI
Page: 16
----------------------------------------------------------------------------------------------------
ts, the back of strong business investment and spending, countries in Asia are best placed to take advantage supported by corporate tax cuts and the race for AI of digitalisation, including generative AI (GenAI). adoption. We expect euro area growth to be more muted • Relatively younger populations, and the adoption at 1.1 per cent given trade pressures – from US tariffs, of digital technology,

====================================================================================================
Company: Standard Chartered plc
Keyword: responsible AI
Page: 218
----------------------------------------------------------------------------------------------------
d initial support of customers, employees and regulators in the communities in technology systems. which the Group operates. Directors and employees are asked to recommit to the Code annually, and 99.7 per cent Responsible AI have completed the 2025 recommitment. All Board members The Group has been actively embracing AI and digital have recommitted to the Code. innovation to stay competitive in the banking,

====================================================================================================
Company: Standard Chartered plc
Keyword: responsible AI
Page: 218
----------------------------------------------------------------------------------------------------
ustomer onboarding, employee with 21.6 per cent in Europe and the Americas, and 6.1 per engagement, management reporting and talent acquisition. cent in Africa and the Middle East. Furthermore, 80 per cent Our Responsible AI governance has been established for of total spend in 2025 was with 342 suppliers. In 2025, our five several years and is led by a dedicated team within the largest suppliers together accounted for 16.2 per cent of

====================================================================================================
Company: Standard Chartered plc
Keyword: responsible AI
Page: 218
----------------------------------------------------------------------------------------------------
Our Audit Committee receives twice-yearly reports on sc.com/suppliers and sc.com/supplier-diversity Data Risk, which includes responsible AI. Read more on how we create value for our suppliers and other stakeholder groups on page 11 By order of the Board Political donations The Group has a policy in place which prohibits donations

In [23]:
# Ensuring manual review columns can hold text values
text_columns = [
    "reason_for_adjustment",
    "important_pages",
    "important_extracts",
    "review_status"
]

for col in text_columns:
    if col not in manual_review.columns:
        manual_review[col] = ""
    manual_review[col] = manual_review[col].astype("object")

numeric_columns = [
    "manual_adjusted_score",
    "manual_adjusted_percentage"
]

for col in numeric_columns:
    if col not in manual_review.columns:
        manual_review[col] = pd.NA

manual_review["company_id"] = manual_review["company_id"].astype(str).str.zfill(3)

# Record manual validation outcome for Standard Chartered
standard_chartered_mask = manual_review["company_id"] == "005"

manual_review.loc[
    standard_chartered_mask,
    "manual_adjusted_score"
] = 12

manual_review.loc[
    standard_chartered_mask,
    "manual_adjusted_percentage"
] = 85.71

manual_review.loc[
    standard_chartered_mask,
    "reason_for_adjustment"
] = (
    "Score increased from provisional automated score. Standard Chartered shows AI-specific transparency evidence through "
    "responsible AI governance, annual Code recommitment, Audit Committee reporting on supplier and data risk including "
    "responsible AI, AI-related business execution themes, MyWealth Advisor, GenAI/digitalisation references, and AI-related "
    "risk disclosure. However, direct evidence of human-in-the-loop review is limited, and some fairness/bias matches relate "
    "to general remuneration, inclusion or accounting fairness rather than AI-specific fairness."
)

manual_review.loc[
    standard_chartered_mask,
    "important_pages"
] = "16, 148, 187, 195, 199, 218, 288, 320"

manual_review.loc[
    standard_chartered_mask,
    "important_extracts"
] = (
    "Responsible AI governance established; employees and directors recommit to the Code annually; Audit Committee receives "
    "reports on supplier and data risk including responsible AI; AI approach with 15 themes identified for execution; "
    "MyWealth Advisor; digitalisation including GenAI adoption; adoption and use of artificial intelligence as a risk; "
    "MAS FEAT-style fairness, ethics, accountability and transparency references."
)

manual_review.loc[
    standard_chartered_mask,
    "review_status"
] = "Reviewed - score increased"

manual_review.to_csv(
    manual_review_file,
    index=False
)

manual_review[manual_review["company_id"] == "005"]

,company_id,company_name,total_ai_transparency_mentions,unique_keywords,unique_pages,total_score,score_percentage,manual_adjusted_score,manual_adjusted_percentage,reason_for_adjustment,important_pages,important_extracts,review_status
5,005,Standard Chartered plc,95,7,33,9,64.29,12.0,85.71,"Score increased from provisional automated score. Standard Chartered shows AI-specific transparency evidence through responsible AI governance, annual Code recommitment, Audit Committee reporting on supplier and data risk including responsible AI, AI-related business execution themes, MyWealth Advisor, GenAI/digitalisation references, and AI-related risk disclosure. However, direct evidence of human-in-the-loop review is limited, and some fairness/bias matches relate to general remuneration, inclusion or accounting fairness rather than AI-specific fairness.","16, 148, 187, 195, 199, 218, 288, 320","Responsible AI governance established; employees and directors recommit to the Code annually; Audit Committee receives reports on supplier and data risk including responsible AI; AI approach with 15 themes identified for execution; MyWealth Advisor; digitalisation including GenAI adoption; adoption and use of artificial intelligence as a risk; MAS FEAT-style fairness, ethics, accountability and transparency references.",Reviewed - score increased

In [24]:
# Lloyds keyword count review

lloyds_keyword_counts = (
    ai_mentions[ai_mentions["company_id"] == "003"]
    .groupby("keyword")
    .agg(
        mention_count=("keyword", "count"),
        unique_pages=("page_number", "nunique")
    )
    .reset_index()
    .sort_values(by="mention_count", ascending=False)
)

lloyds_keyword_counts

                   keyword  mention_count  unique_pages
0                       AI             58            28
2  artificial intelligence              9             8
6            generative AI              5             5
3               automation              3             3
1                AI ethics              1             1
4                     bias              1             1
5               ethical AI              1             1
7         machine learning              1             1

In [25]:
print_company_evidence(
    company_id="003",
    keywords=[
        "artificial intelligence",
        "machine learning",
        "generative AI",
        "responsible AI",
        "AI ethics",
        "ethical AI",
        "human oversight",
        "human review",
        "human-in-the-loop",
        "automated decision-making",
        "bias",
        "fairness"
    ],
    max_items=35
)

====================================================================================================
Company: Lloyds Banking Group plc
Keyword: AI ethics
Page: 83
----------------------------------------------------------------------------------------------------
agriculture • Wider sustainability topics included: the Group’s treatment of vulnerable customers, generative AI deep dive which outlined the Group’s AI ethics principles and how use cases are overseen via the Data and AI Ethics Committee, economic crime deep dive and key drivers of people risk and mitigating action Audit

====================================================================================================
Company: Lloyds Banking Group plc
Keyword: artificial intelligence
Page: 14
----------------------------------------------------------------------------------------------------
verview Competition remains intense with high street banks and Rapidly evolving technology landscape, accelerated building societies maintaining their focus on share growth, by developments in artificial intelligence and digital and building scale by consolidating smaller players. Alongside, transformation. These shifts are enabling new engagement neobanks and fintechs continue to gain momentum by models, in

====================================================================================================
Company: Lloyds Banking Group plc
Keyword: artificial intelligence
Page: 26
----------------------------------------------------------------------------------------------------
• The RMF provides tools for colleagues to make the capabilities and ensure the safe, responsible use of models and tools right decisions, balancing stakeholder needs, risks and such as artificial intelligence. trade-offs and encouraging a culture of intellectual curiosity, innovatio

====================================================================================================
Company: Lloyds Banking Group plc
Keyword: artificial intelligence
Page: 40
----------------------------------------------------------------------------------------------------
help them fulfil their ambitions delivering Our assessment has identified the following material topics: products in a responsible manner. Our operations are built around this management of capital for our • Artificial intelligence • Financial crime stakeholders requiring safeguarding of our customers’ money and • Biodiversity and nature • Financial inclusion data. We know our colleagues are the key ingredient

====================================================================================================
Company: Lloyds Banking Group plc
Keyword: artificial intelligence
Page: 42
----------------------------------------------------------------------------------------------------
lower engagement with financial products and Conduct Social Medium Business Committee. See page 97 and resilience lower level of financial resilience Artificial intelligence impacting customer Conduct Social Short, Qualitative updates given to Board Risk Committee Financial inclusion serv

====================================================================================================
Company: Lloyds Banking Group plc
Keyword: artificial intelligence
Page: 43
----------------------------------------------------------------------------------------------------
e Rights 1 products to serve our customers page 28 of our sustainability report Digital and artificial intelligence tools to Conduct, Short, Qualitative updates given to Responsible Business Artificial Intelligence, support, empowering customers financial Operational Medium Committe

====================================================================================================
Company: Lloyds Banking Group plc
Keyword: artificial intelligence
Page: 43
----------------------------------------------------------------------------------------------------
page 28 of our sustainability report Digital and artificial intelligence tools to Conduct, Short, Qualitative updates given to Responsible Business Artificial Intelligence, support, empowering customers financial Operational Medium Committee see page 81 Financial inclusion resilience and to identify customer

====================================================================================================
Company: Lloyds Banking Group plc
Keyword: artificial intelligence
Page: 85
----------------------------------------------------------------------------------------------------
the strategy economic implications and data, digital assets, technology and use of artificial intelligence • The Board regularly received updates on customer

====================================================================================================
Company: Lloyds Banking Group plc
Keyword: artificial intelligence
Page: 94
----------------------------------------------------------------------------------------------------
k Officer providing perspectives on the • Continued oversight and challenge on model and data risk, overall credit environment. Oversight of model risk included a deep ensuring effective risk management of artificial intelligence dive on generative and agentic AI together with implementation of • Considered management of climate risk, particularly the associated assurance framework. greenwashing controls and scenario mode

====================================================================================================
Company: Lloyds Banking Group plc
Keyword: artificial intelligence
Page: 326
----------------------------------------------------------------------------------------------------
ective’, ‘deliver’, ‘endeavour’, failure of third party suppliers; conduct risk; risks related to new and ‘prospects’, ‘optimistic’ and similar expressions or variations on emerging technologies, including artificial intelligence; technological these expressions are intended to identify forward-looking changes and risks to the security of IT and operational statements. These statements concern or may affect future infrastruc

====================================================================================================
Company: Lloyds Banking Group plc
Keyword: bias
Page: 211
----------------------------------------------------------------------------------------------------
aud through management override of controls, testing the appropriateness of journal entries and other adjustments; • assessing whether the judgements made in making accounting estimates are indicative of a potential bias; and • evaluating the business rationale of any significant transactions that are unusual or outside the normal course of business. We also communicated relevant identified laws and regulations and potential fraud risk

====================================================================================================
Company: Lloyds Banking Group plc
Keyword: ethical AI
Page: 31
----------------------------------------------------------------------------------------------------
• Emerging technologies AI’ programme to over 200 senior leaders • Evolution and scaling of AI • Implemented a data ethics framework and Ethical AI • Evolution of cybercrime framework within our Group data and model risk policies

====================================================================================================
Company: Lloyds Banking Group plc
Keyword: generative AI
Page: 31
----------------------------------------------------------------------------------------------------
• Blockchain and tokenisation • Regular updates on data and technology strategy, and deep • Cloud vulnerabilities dives completed on generative AI, cyber risk, technology risk technology, AI • Digital currencies and payments and economic crime prevention at relevant committees and cybercrime • Digital sovereignty •

====================================================================================================
Company: Lloyds Banking Group plc
Keyword: generative AI
Page: 77
----------------------------------------------------------------------------------------------------
y updates for assessing customer experience outcomes • An update on workforce engagement activities during • An update on generative AI initiatives the year • A briefing on the proposed acquisition of Curve Key decisions/outcomes includ

====================================================================================================
Company: Lloyds Banking Group plc
Keyword: generative AI
Page: 80
----------------------------------------------------------------------------------------------------
since the offsite discussion in June, with a particular focus on the pace of development and impact of generative AI. June Topics discussed at the June offsite session included the complex external environment, its potential evolution beyond 2026 and key considerations for the Group. The Board also discussed the development of the Gro

====================================================================================================
Company: Lloyds Banking Group plc
Keyword: generative AI
Page: 83
----------------------------------------------------------------------------------------------------
economic and social misalignment in material sectors such as homes and agriculture • Wider sustainability topics included: the Group’s treatment of vulnerable customers, generative AI deep dive which outlined the Group’s AI ethics principles and how use cases are overseen via the Data and AI Ethics Committee, economic crime deep dive and ke

====================================================================================================
Company: Lloyds Banking Group plc
Keyword: generative AI
Page: 89
----------------------------------------------------------------------------------------------------
ain 45 to 55% female representation on their Boards, higher than the FTSEQ1 2025 Women Leaders recommendation of 40%, while recognising the • Generative AI: maximising opportunities limited numbers involved. The representation of women on the while navigating the complexities around Board is currently 50%. On ethnicity, the Boa

====================================================================================================
Company: Lloyds Banking Group plc
Keyword: machine learning
Page: 29
----------------------------------------------------------------------------------------------------
more transparent and informative reporting of model riskmeeting both internal and regulatory requirements to support the safe and strategic development of AI and machine learning applications within the Group. Investment in model risk management remains a priority for the Trend Group to further improve r

In [26]:
# Manual validation outcome for Lloyds Banking Group plc

lloyds_mask = manual_review["company_id"] == "003"

manual_review.loc[
    lloyds_mask,
    "manual_adjusted_score"
] = 12

manual_review.loc[
    lloyds_mask,
    "manual_adjusted_percentage"
] = 85.71

manual_review.loc[
    lloyds_mask,
    "reason_for_adjustment"
] = (
    "Score increased from provisional automated score. Lloyds shows stronger AI-specific transparency evidence than the "
    "automated score captured, including Board-level discussion of generative AI and generative AI initiatives. Business-use, governance and ethics/fairness scores were therefore increased. "
    "However, direct evidence of operational human-in-the-loop review or manual review of AI decisions remains limited."
)

manual_review.loc[
    lloyds_mask,
    "important_pages"
] = "26, 29, 31, 43, 77, 80, 83, 85, 94, 211"

manual_review.loc[
    lloyds_mask,
    "important_extracts"
] = (
    "Board discussed the pace and impact of generative AI; generative AI deep dive outlined AI ethics principles; use cases "
    "overseen via the Data and AI Ethics Committee; data ethics framework and Ethical AI implemented; model risk management "
    "supports safe and strategic development of AI and machine learning applications; digital and artificial intelligence tools "
    "support customers; Board received updates on data, digital assets, technology and AI; oversight and challenge over model "
    "and data risk."
)

manual_review.loc[
    lloyds_mask,
    "review_status"
] = "Reviewed - score increased"

manual_review.to_csv(
    manual_review_file,
    index=False
)

manual_review[manual_review["company_id"] == "003"]

,company_id,company_name,total_ai_transparency_mentions,unique_keywords,unique_pages,total_score,score_percentage,manual_adjusted_score,manual_adjusted_percentage,reason_for_adjustment,important_pages,important_extracts,review_status
6,003,Lloyds Banking Group plc,79,8,35,9,64.29,12.0,85.71,"Score increased from provisional automated score. Lloyds shows stronger AI-specific transparency evidence than the automated score captured, including Board-level discussion of generative AI and generative AI initiatives. Business-use, governance and ethics/fairness scores were therefore increased. However, direct evidence of operational human-in-the-loop review or manual review of AI decisions remains limited.","26, 29, 31, 43, 77, 80, 83, 85, 94, 211","Board discussed the pace and impact of generative AI; generative AI deep dive outlined AI ethics principles; use cases overseen via the Data and AI Ethics Committee; data ethics framework and Ethical AI implemented; model risk management supports safe and strategic development of AI and machine learning applications; digital and artificial intelligence tools support customers; Board received updates on data, digital assets, technology and AI; oversight and challenge over model and data risk.",Reviewed - score increased

In [27]:
# LSEG keyword count review

lseg_keyword_counts = (
    ai_mentions[ai_mentions["company_id"] == "019"]
    .groupby("keyword")
    .agg(
        mention_count=("keyword", "count"),
        unique_pages=("page_number", "nunique")
    )
    .reset_index()
    .sort_values(by="mention_count", ascending=False)
)

lseg_keyword_counts

                   keyword  mention_count  unique_pages
0                       AI             96            30
2  artificial intelligence              7             6
4                     bias              7             5
3               automation              4             3
1                      LLM              2             2
5            generative AI              1             1
6     large language model              1             1
7         machine learning              1             1

In [28]:
print_company_evidence(
    company_id="019",
    keywords=[
        "artificial intelligence",
        "machine learning",
        "generative AI",
        "large language model",
        "LLM",
        "responsible AI",
        "AI ethics",
        "ethical AI",
        "human oversight",
        "human review",
        "human-in-the-loop",
        "automated decision-making",
        "bias",
        "fairness"
    ],
    max_items=35
)

====================================================================================================
Company: London Stock Exchange Group plc
Keyword: LLM
Page: 13
----------------------------------------------------------------------------------------------------
n business, so we Interoperability is in our DNA. When other in financial services through professionals work, with can innovate faster and exchange groups focused on vertical our open, LLM-agnostic AI-enabled products that serve our customers better. integration of trading and clearing, we partnership approach. bring speed, simplicity champio

====================================================================================================
Company: London Stock Exchange Group plc
Keyword: LLM
Page: 199
----------------------------------------------------------------------------------------------------
insurance products. FTSE Russell FTSE International Limited and its subsidiaries, LLM the Group subsidiary that is a leading global Large language model. provider of index and analytics solutions.

====================================================================================================
Company: London Stock Exchange Group plc
Keyword: artificial intelligence
Page: 8
----------------------------------------------------------------------------------------------------
n track record of delivering real value through long-term partnership. David Schwimmer Chief Executive Officer AI strategy 25 February, 2026 Artificial intelligence is transforming financial markets. With our unmatched data, infrastructure and partnerships, LSEG is at London Stock Exchange Group plc | An

====================================================================================================
Company: London Stock Exchange Group plc
Keyword: artificial intelligence
Page: 13
----------------------------------------------------------------------------------------------------
creates the opportunity for strong partnership. From developing our clearing Artificial intelligence is transforming financial markets. With our unmatched data, infrastructure houses to now building new products and partnerships, we are

====================================================================================================
Company: London Stock Exchange Group plc
Keyword: artificial intelligence
Page: 55
----------------------------------------------------------------------------------------------------
d Change Frameworks, Rapid market and technological shifts, including the which provide standards and guidance for effective programme continued advancement of artificial intelligence (AI), assessment, execution and integration of acquisitions. Group Risk heighten the risk of disruption to our business model, monitor transformation activities and execution risk w

====================================================================================================
Company: London Stock Exchange Group plc
Keyword: artificial intelligence
Page: 56
----------------------------------------------------------------------------------------------------
our Model Risk Committee, supported financial loss or reputational harm. The growing use by divisional working groups to ensure full coverage and of artificial intelligence particularly ‘generative’ and alignment with risk objectives. Regular, independent review of ‘agentic’ models introduces new dimensions of risk, models by our Model Risk Man

====================================================================================================
Company: London Stock Exchange Group plc
Keyword: artificial intelligence
Page: 67
----------------------------------------------------------------------------------------------------
ers and other they take into account Directors’ duties key topics. During 2025, the Board participated key stakeholders (including the workforce, contained in the Companies Act 2006 (the in sessions relating to artificial intelligence customers, suppliers and regulators) to enable “Act”) and will consider the factors listed in strategy and governance as well as new LSEG to pursue long-term sustainable success. Section 172 of the Act

====================================================================================================
Company: London Stock Exchange Group plc
Keyword: artificial intelligence
Page: 67
----------------------------------------------------------------------------------------------------
led within the respective Committee investment in Post Trade Solutions with key wider society. reports on pages 72 to 103. customer banks; challenges and opportunities presented by artificial intelligence; multi-year The Board: technology planning and innovation; and non-executive director rotations. – Provides leadership of the Company and

====================================================================================================
Company: London Stock Exchange Group plc
Keyword: artificial intelligence
Page: 199
----------------------------------------------------------------------------------------------------
Derivatives are negotiated privately between designed to address challenges of Authorised AI two parties and may be cleared through Push Payment (APP) fraud. Artificial intelligence. a clearing house. Green Economy Mark AIM DigitalAssetClear

====================================================================================================
Company: London Stock Exchange Group plc
Keyword: bias
Page: 47
----------------------------------------------------------------------------------------------------
4; At year-end, colleagues receive equally average completion rate of 73% for modules 1.8% of the raw pay gap was non-identifiable by weighted ratings for what they achieve – covering topics such as bias, anti-racism, the factors considered in our model. The raw aligned to personal, divisional and Group accessibility, and LGBTQ+ inclusion. ethnicity pay gap in the UK and US increased objec

====================================================================================================
Company: London Stock Exchange Group plc
Keyword: bias
Page: 47
----------------------------------------------------------------------------------------------------
ll colleagues that is held accountable for creating an differences arise from protected characteristics are required to complete mandatory annual inclusive culture or improper bias. Our ambition is to reduce all training on our Code of Conduct, and in 2025 – Create merit-based processes, enabling pay gaps, particularly keeping non-identifiable 98.5% of colleagues completed the training.

====================================================================================================
Company: London Stock Exchange Group plc
Keyword: bias
Page: 84
----------------------------------------------------------------------------------------------------
– Continue to progress towards pay clarity Corporate Governance section of our website of 2025 Long-Term Incentive (LTI) awards and pay free from bias, ahead of the EU at https://www.lseg.com/en/about-us/– Remuneration approach for 2026, including Pay Transparency Directive implementation corporate-governance. t

====================================================================================================
Company: London Stock Exchange Group plc
Keyword: bias
Page: 84
----------------------------------------------------------------------------------------------------
. The review determined– Progress towards pay clarity and pay free that the Committee is performing well and from bias ahead of EU Pay Transparency operating effectively. Further details can be Directive implementation

====================================================================================================
Company: London Stock Exchange Group plc
Keyword: bias
Page: 89
----------------------------------------------------------------------------------------------------
to pay; and (iii) we are focused on clarity and pay free from bias. Fixed pay Salary Pension and Benefits Reflects value of individual roles, which is linked with individual Competitive benefits and pension pla

====================================================================================================
Company: London Stock Exchange Group plc
Keyword: bias
Page: 108
----------------------------------------------------------------------------------------------------
ages 37 to 46. by the applicable laws in the countries in which we operate. For example, in the US under the – drives towards removing bias related to Research and development Federal Election Campaign Act, eligible disability hiring and provides the necessary LSEG undertakes research and development employees can establish n

====================================================================================================
Company: London Stock Exchange Group plc
Keyword: bias
Page: 118
----------------------------------------------------------------------------------------------------
r alleged fraud; adjustments; assessing whether the judgements made in making – the internal controls established to mitigate risks of fraud or accounting estimates are indicative of a potential bias; and evaluating non-compliance with laws and regulations; the business rationale of any significant transactions that are unusual – the matters discussed among the audit engagement team in

====================================================================================================
Company: London Stock Exchange Group plc
Keyword: generative AI
Page: 53
----------------------------------------------------------------------------------------------------
and operational services and products to customers. The adoption of excellence. It helps to ensure that stakeholder interests advanced cloud-based generative AI capabilities will are considered in the development and deployment enable the Risk Intelligence division to provide faster of cloud-based solutions, particularly in areas suc

====================================================================================================
Company: London Stock Exchange Group plc
Keyword: large language model
Page: 199
----------------------------------------------------------------------------------------------------
FTSE Russell FTSE International Limited and its subsidiaries, LLM the Group subsidiary that is a leading global Large language model. provider of index and analytics solutions. London Stock Exchange Group plc | Annual Rep

====================================================================================================
Company: London Stock Exchange Group plc
Keyword: machine learning
Page: 108
----------------------------------------------------------------------------------------------------
iding such support is not existing locations language models, quantitative and data-driven considered to be a political donation or modelling, machine learning and natural expenditure under US law. In accordance with language processing. Research also includes the applicable law, contributions from the PAC

In [29]:
# Manual validation outcome for London Stock Exchange Group plc

lseg_mask = manual_review["company_id"] == "019"

manual_review.loc[
    lseg_mask,
    "manual_adjusted_score"
] = 11

manual_review.loc[
    lseg_mask,
    "manual_adjusted_percentage"
] = 78.57

manual_review.loc[
    lseg_mask,
    "reason_for_adjustment"
] = (
    "Score increased from provisional automated score. LSEG shows stronger AI-specific transparency evidence than the automated score captured. "
    "Governance and risk scores were therefore increased. However, fairness and bias references were mostly general HR, pay, "
    "audit judgement or legal references. Human oversight evidence remains partial because the report refers to independent model review. "
)

manual_review.loc[
    lseg_mask,
    "important_pages"
] = "8, 13, 53, 55, 56, 67, 108, 199"

manual_review.loc[
    lseg_mask,
    "important_extracts"
] = (
    "Artificial intelligence is transforming financial markets; LSEG refers to AI-enabled products that serve customers better; "
    "cloud-based generative AI capabilities are considered in development and deployment; language models and LLM-agnostic "
    "AI-enabled products are referenced; AI is linked to risk frameworks, model risk, generative AI risk and agentic models; "
    "the Model Risk Committee and regular independent review provide evidence of governance and oversight."
)

manual_review.loc[
    lseg_mask,
    "review_status"
] = "Reviewed - score increased"

manual_review.to_csv(
    manual_review_file,
    index=False
)

manual_review[manual_review["company_id"] == "019"]

,company_id,company_name,total_ai_transparency_mentions,unique_keywords,unique_pages,total_score,score_percentage,manual_adjusted_score,manual_adjusted_percentage,reason_for_adjustment,important_pages,important_extracts,review_status
7,019,London Stock Exchange Group plc,119,8,34,8,57.14,11.0,78.57,"Score increased from provisional automated score. LSEG shows stronger AI-specific transparency evidence than the automated score captured. Governance and risk scores were therefore increased. However, fairness and bias references were mostly general HR, pay, audit judgement or legal references. Human oversight evidence remains partial because the report refers to independent model review.","8, 13, 53, 55, 56, 67, 108, 199","Artificial intelligence is transforming financial markets; LSEG refers to AI-enabled products that serve customers better; cloud-based generative AI capabilities are considered in development and deployment; language models and LLM-agnostic AI-enabled products are referenced; AI is linked to risk frameworks, model risk, generative AI risk and agentic models; the Model Risk Committee and regular independent review provide evidence of governance and oversight.",Reviewed - score increased

In [30]:
# Experian keyword count review

experian_keyword_counts = (
    ai_mentions[ai_mentions["company_id"] == "020"]
    .groupby("keyword")
    .agg(
        mention_count=("keyword", "count"),
        unique_pages=("page_number", "nunique")
    )
    .reset_index()
    .sort_values(by="mention_count", ascending=False)
)

experian_keyword_counts

                   keyword  mention_count  unique_pages
0                       AI             44            23
1  artificial intelligence              8             7
2               automation              7             7
5            generative AI              6             5
4                 fairness              5             5
3                     bias              2             2
6         machine learning              2             2

In [31]:
print_company_evidence(
    company_id="020",
    keywords=[
        "artificial intelligence",
        "machine learning",
        "generative AI",
        "large language model",
        "LLM",
        "responsible AI",
        "AI ethics",
        "ethical AI",
        "human oversight",
        "human review",
        "human-in-the-loop",
        "automated decision-making",
        "bias",
        "fairness"
    ],
    max_items=35
)

====================================================================================================
Company: Experian plc
Keyword: artificial intelligence
Page: 6
----------------------------------------------------------------------------------------------------
rating of 4.2/5, Our client Net Promotor Score (NPS) has up from 4.1 four years ago increased for seven years running since FY18 Our Generative Artificial Intelligence >200m (GenAI)-enabled tool, Experian Assistant, Our free consumer member won the 2025 BIG Innovation Award in the

====================================================================================================
Company: Experian plc
Keyword: artificial intelligence
Page: 13
----------------------------------------------------------------------------------------------------
data – we combine it with powerful software, of Group revenue* analytics, and Artificial Intelligence (AI) to create solutions.What we do We help millions of people take control of their finances. We provide credit We integ

====================================================================================================
Company: Experian plc
Keyword: artificial intelligence
Page: 83
----------------------------------------------------------------------------------------------------
to an increasing number of events Office (GSO) has constantly updated processes, including those relating that have the potential to impact operations in a single location, to emerging threats, such as Generative Artificial Intelligence (GenAI). including extreme weather events, breakdowns in core infrastructure The Audit Committee was also briefed on the investment in people and or the emergence of a significant health-related event, we

====================================================================================================
Company: Experian plc
Keyword: artificial intelligence
Page: 86
----------------------------------------------------------------------------------------------------
control the use of data in certain areas. on regulations which have the potential to impact our business, Additional states have under consideration similar or more including regulations over Artificial Intelligence (AI) and cyber security, comprehensive privacy laws. The California Delete Act, which is rulings which could impact credit scores, and General Data Protection scheduled to go into effect in August 2026,

====================================================================================================
Company: Experian plc
Keyword: artificial intelligence
Page: 100
----------------------------------------------------------------------------------------------------
Management activities During the financial year regarding Privacy and Artificial Intelligence (AI), Consumer Credit and • The Chief Executive Officer (CEO) updates the Board at every scheduled regulatory trends and updates on the rulemaking and supervisory meeting on operational, financial, business, a

====================================================================================================
Company: Experian plc
Keyword: artificial intelligence
Page: 121
----------------------------------------------------------------------------------------------------
processes, including those relating to emerging Anti-Bribery and Corruption and Gifts and Hospitality Policies. These threats such as Generative Artificial Intelligence (GenAI). The Committee policies, together with regular communications on the Confidential was also briefed on the investment in people and technology and the Helpl

====================================================================================================
Company: Experian plc
Keyword: artificial intelligence
Page: 244
----------------------------------------------------------------------------------------------------
ions are used in this Annual Report, and are taken to have the following meanings: Abbreviation Meaning AGM Annual General Meeting AI Artificial Intelligence A/NZ Australia and New Zealand APAC Asia Pacific API Application Programming Interface B2B Business-to-Busi

====================================================================================================
Company: Experian plc
Keyword: artificial intelligence
Page: 244
----------------------------------------------------------------------------------------------------
Generally Accepted Accounting Practice GDP Gross Domestic Product GDPR General Data Protection Regulation GenAI Generative Artificial Intelligence GHGs Greenhouse gas emissions H1 The first half of Experian’s financial year, being the six months ending 30 September

====================================================================================================
Company: Experian plc
Keyword: bias
Page: 65
----------------------------------------------------------------------------------------------------
year, including Pride celebrations across our regions, talks leaders within Experian through our extensive leadership developmentto consider racial bias in Latin America, and awards in EMEA and Asia programmes.Pacific to recognise colleagues’ contributions to our culture of inclusion and belonging.

====================================================================================================
Company: Experian plc
Keyword: bias
Page: 161
----------------------------------------------------------------------------------------------------
made in making accounting estimates of fraud. The discussions also involved our forensic specialists to assist us are indicative of a potential bias. in identifying fraud risks based on discussions of the circumstances of the Group and Company, including consideration of fraudulent schemes that Work on the fraud risks was performed by a combination of compon

====================================================================================================
Company: Experian plc
Keyword: fairness
Page: 46
----------------------------------------------------------------------------------------------------
dd value • Employee assistance helpline Closer relationships with our suppliers, enabled through partnerships • Whistleblowing hotline and fairness, help us to uncover and realise new value, increase savings and reduce costs and risk of failure, as well as ensuring we comply How we add value

====================================================================================================
Company: Experian plc
Keyword: fairness
Page: 58
----------------------------------------------------------------------------------------------------
1.4 8.10 9.3 ENABLED BY Treating data with respect Security Accuracy Fairness Transparency Inclusion SUPPORTED BY Our responsible business foundations Inspiring and supporting Working with Protec

====================================================================================================
Company: Experian plc
Keyword: fairness
Page: 60
----------------------------------------------------------------------------------------------------
e use it, always in which small landowners represent 37%. compliance with legal requirements. We offer a range of solutions to help clients prevent fraud. On average, Fairness: We collect and use data fairly and for legitimate over 350,000 transactions a month are processed through CrossCore, our purposes, balancing privacy expectations with the social and integrated platform for fr

====================================================================================================
Company: Experian plc
Keyword: fairness
Page: 62
----------------------------------------------------------------------------------------------------
62 ExperianStrategic reportplc Sustainability continued Accuracy Fairness Accurate credit reports, built on accurate data, are essential to enable We are committed to collecting and using data fairly and for legitimate lenders to give people fair access to credit. We strive to continually

====================================================================================================
Company: Experian plc
Keyword: fairness
Page: 114
----------------------------------------------------------------------------------------------------
e many ongoing initiatives to support a work Inclusion and belonging environment where everyone is treated We believe inclusion and belonging are with fairness and respect, has equal access essential to our purpose of creating a better to opportunities and resources, and can tomorrow, together, by making positive change contribute fully to our success. in the world,

====================================================================================================
Company: Experian plc
Keyword: generative AI
Page: 20
----------------------------------------------------------------------------------------------------
ng the sectors’ ongoing transformation. for instant access to financial services via smartphones. Our members are able to access credit offers instantly and our Insurance Marketplace in the USA has grown rapidly in Generative AI and other emerging scale. We have also introduced our Generative AI (GenAI) technologies financial assistant EVA, which helps our members to better The world of GenAI is rapidly evolving, offering both under

====================================================================================================
Company: Experian plc
Keyword: generative AI
Page: 20
----------------------------------------------------------------------------------------------------
ial services via smartphones. Our members are able to access credit offers instantly and our Insurance Marketplace in the USA has grown rapidly in Generative AI and other emerging scale. We have also introduced our Generative AI (GenAI) technologies financial assistant EVA, which helps our members to better The world of GenAI is rapidly evolving, offering both understand their credit data and work towards improving technolo

====================================================================================================
Company: Experian plc
Keyword: generative AI
Page: 24
----------------------------------------------------------------------------------------------------
rated markets where we are ever-more tailored recommendations, which use AI, most relevant. open banking, and consumer-permissioned data. 5. Leverage advanced technologies, Generative AI and AI more 5. Reach new audiences: attract new customers and broadly to improve our product innovation and re-engineer re-engage existing members. our processes and costs to better position our businesses

====================================================================================================
Company: Experian plc
Keyword: generative AI
Page: 31
----------------------------------------------------------------------------------------------------
ulture that encourages transparency and proactive risk reporting. We drive cost effectiveness across our operations, improve service A recent example is our approach to Generative AI (GenAI). reliability, security and performance, and enable the organisation to Recognising both its potential and risks, we have put in place a clear a

====================================================================================================
Company: Experian plc
Keyword: generative AI
Page: 63
----------------------------------------------------------------------------------------------------
Intelligence (AI) At Experian, we champion the responsible use of AI, including machine learning and Generative AI (GenAI) to enhance productivity, drive innovation, and improve solutions for evolving customer and

====================================================================================================
Company: Experian plc
Keyword: generative AI
Page: 109
----------------------------------------------------------------------------------------------------
ns Our suppliers Board • Annual update to the Board on • FY26 will see an increase in the pace of automation and usage of suppliers, which includes details Generative AI within our administrative processes. of digitalisation, engagement, the • Our SRM programme focused on 20 key suppliers with regular, Group’s Supp

====================================================================================================
Company: Experian plc
Keyword: machine learning
Page: 60
----------------------------------------------------------------------------------------------------
are Experian Lift Premium enables lenders to score over two thirds of credit open about the data we collect, how we use it and who we invisibles in the USA by applying machine learning and other advanced share it with. And we use data to increase financial inclusionanalytics to additional datasets, regulated by the US Fair Credit Reporting Act (

====================================================================================================
Company: Experian plc
Keyword: machine learning
Page: 63
----------------------------------------------------------------------------------------------------
Intelligence (AI) At Experian, we champion the responsible use of AI, including machine learning and Generative AI (GenAI) to enhance productivity, drive innovation, and improve solutions for evolving customer and

In [32]:
# Manual validation outcome for Experian plc

experian_mask = manual_review["company_id"] == "020"

manual_review.loc[
    experian_mask,
    "manual_adjusted_score"
] = 11

manual_review.loc[
    experian_mask,
    "manual_adjusted_percentage"
] = 78.57

manual_review.loc[
    experian_mask,
    "reason_for_adjustment"
] = (
    "Score increased from provisional automated score. Experian shows stronger AI-specific transparency evidence than the "
    "automated score captured, including machine learning in credit scoring, and GenAI-related risks. Governance, risk, business use and specificity were therefore "
    "increased. However, most bias references were related to audit judgement, fraud risk or workforce "
    "inclusion. Human oversight evidence remains limited because the report does not clearly describe manual intervention in AI-driven decisions."
)

manual_review.loc[
    experian_mask,
    "important_pages"
] = "20, 31, 58, 60, 62, 63, 109, 121"

manual_review.loc[
    experian_mask,
    "important_extracts"
] = (
    "Experian refers to Generative AI technologies including financial assistant EVA, which helps members understand their credit data; "
    "Experian Lift Premium applies machine learning and other advanced techniques to increase credit access for credit-invisible consumers; "
    "the company states that it champions responsible use of AI, including machine learning and GenAI, to enhance productivity, drive innovation "
    "and improve customer solutions; the report references a clear approach to GenAI, including reliability, security and performance; "
    "Board updates include privacy and artificial intelligence, consumer credit and regulatory trends."
)

manual_review.loc[
    experian_mask,
    "review_status"
] = "Reviewed - score increased"

manual_review.to_csv(
    manual_review_file,
    index=False
)

manual_review[manual_review["company_id"] == "020"]

,company_id,company_name,total_ai_transparency_mentions,unique_keywords,unique_pages,total_score,score_percentage,manual_adjusted_score,manual_adjusted_percentage,reason_for_adjustment,important_pages,important_extracts,review_status
8,020,Experian plc,74,7,35,7,50.0,11.0,78.57,"Score increased from provisional automated score. Experian shows stronger AI-specific transparency evidence than the automated score captured, including machine learning in credit scoring, and GenAI-related risks. Governance, risk, business use and specificity were therefore increased. However, most bias references were related to audit judgement, fraud risk or workforce inclusion. Human oversight evidence remains limited because the report does not clearly describe manual intervention in AI-driven decisions.","20, 31, 58, 60, 62, 63, 109, 121","Experian refers to Generative AI technologies including financial assistant EVA, which helps members understand their credit data; Experian Lift Premium applies machine learning and other advanced techniques to increase credit access for credit-invisible consumers; the company states that it champions responsible use of AI, including machine learning and GenAI, to enhance productivity, drive innovation and improve customer solutions; the report references a clear approach to GenAI, including reliability, security and performance; Board updates include privacy and artificial intelligence, consumer credit and regulatory trends.",Reviewed - score increased

In [33]:
# Aviva keyword count review

aviva_keyword_counts = (
    ai_mentions[ai_mentions["company_id"] == "006"]
    .groupby("keyword")
    .agg(
        mention_count=("keyword", "count"),
        unique_pages=("page_number", "nunique")
    )
    .reset_index()
    .sort_values(by="mention_count", ascending=False)
)

aviva_keyword_counts

                   keyword  mention_count  unique_pages
0                       AI             65            26
1  artificial intelligence             17            12
2               automation              6             5
4            generative AI              2             2
3                 fairness              1             1

In [34]:
print_company_evidence(
    company_id="006",
    keywords=[
        "artificial intelligence",
        "machine learning",
        "generative AI",
        "large language model",
        "LLM",
        "responsible AI",
        "AI ethics",
        "ethical AI",
        "human oversight",
        "human review",
        "human-in-the-loop",
        "automated decision-making",
        "bias",
        "fairness"
    ],
    max_items=35
)

====================================================================================================
Company: Aviva plc
Keyword: artificial intelligence
Page: 5
----------------------------------------------------------------------------------------------------
Insurance, Wealth and Driving operating leverage with Benefitting from our diversified capital-light and respect.Retirement solutions, technology and artificial intelligence (AI) portfolio, which drives resilient performance

====================================================================================================
Company: Aviva plc
Keyword: artificial intelligence
Page: 28
----------------------------------------------------------------------------------------------------
and Driving operating leverage and transforming with data and artificial intelligence.

====================================================================================================
Company: Aviva plc
Keyword: artificial intelligence
Page: 35
----------------------------------------------------------------------------------------------------
ingcorporates. Aviva access to underwrite risks in the and exploring new and innovative the use of artificial intelligence

====================================================================================================
Company: Aviva plc
Keyword: artificial intelligence
Page: 35
----------------------------------------------------------------------------------------------------
Governance customers have adequate protection. Treasury’s ambition to establish a UK Captive regime in 2027. To support clientsOur use of artificial intelligence continues with a global risk profile, we alsoto drive efficiencies in our business, with introduced Aviva Global Risk Management

====================================================================================================
Company: Aviva plc
Keyword: artificial intelligence
Page: 80
----------------------------------------------------------------------------------------------------
We limit the sensitivity of our balance sheet to these risks within our overall risk Strategic pillars: Focus level: The rapid growth of artificial intelligence poses both risks and opportunities to global management framework. This includes setting limits on market and credit risks, Governance

====================================================================================================
Company: Aviva plc
Keyword: artificial intelligence
Page: 81
----------------------------------------------------------------------------------------------------
and New and rapidly advancing technologies such as generative Artificial Intelligence and Our operational risk and control management framework provides us with the tools and IT Control environment quantum computing threaten to out-pace regulations, governance an

====================================================================================================
Company: Aviva plc
Keyword: artificial intelligence
Page: 84
----------------------------------------------------------------------------------------------------
in a comprehensive library Riskof emerging risk scenarios, which are distinguished from current risks by the Artificial Intelligence

====================================================================================================
Company: Aviva plc
Keyword: artificial intelligence
Page: 84
----------------------------------------------------------------------------------------------------
IFRS the rapid advances in Artificial Intelligence Evolving work culture (AI) technology that enable even moresophisticated social engineering,

====================================================================================================
Company: Aviva plc
Keyword: artificial intelligence
Page: 85
----------------------------------------------------------------------------------------------------
Report HIGH VELOCITY RISKS MEDIUM TERM AND LONGER TERM RISKS and Artificial Intelligence Escalating geopolitical tensions Medical advances Societal inequality

====================================================================================================
Company: Aviva plc
Keyword: artificial intelligence
Page: 101
----------------------------------------------------------------------------------------------------
t Line integration and the Board’s Health Operations businesses, Exclusions Policy. of the transaction to acquire Direct Line, annual objectives and actions from the and how artificial intelligence and corporate restructuring following the internal Board Effectiveness Review. tools are being deployed to The Board held a session to review the plan acquisition.

====================================================================================================
Company: Aviva plc
Keyword: artificial intelligence
Page: 101
----------------------------------------------------------------------------------------------------
leagues, opportunities relating to digitisation and Strategy Offsite including with the ‘See It, Be It’ generative artificial intelligence. In June 2025, the Board held its annual SEPTEMBER charity that works with local

====================================================================================================
Company: Aviva plc
Keyword: artificial intelligence
Page: 101
----------------------------------------------------------------------------------------------------
Floating Rate Notes. regarding the effective deployment of appropriately positioned in terms of artificial intelligence tools to enhance cyber resilience. efficiency and customer experience.

====================================================================================================
Company: Aviva plc
Keyword: artificial intelligence
Page: 101
----------------------------------------------------------------------------------------------------
t and challenge the Group's The impact of the acquisition of Direct artificial intelligence approach and Line was considered as appropriate. initiatives. An exte

====================================================================================================
Company: Aviva plc
Keyword: artificial intelligence
Page: 102
----------------------------------------------------------------------------------------------------
nto its next phase of growth. These included ensuring the Board and the organisation have the appropriate skills, capacity, and capability for the future, particularly in areas such as technology, artificial intelligence and wealth management, alongside continued emphasis on talent development and succession planning. The review also highlighted the importance of maintaining the high levels

====================================================================================================
Company: Aviva plc
Keyword: artificial intelligence
Page: 109
----------------------------------------------------------------------------------------------------
ise. and non-financial risk, including cyber, Report • Reviewed and approved the outcome of data, artificial intelligence (AI), reputation, Strategic the Group Risk Identification Process,

====================================================================================================
Company: Aviva plc
Keyword: artificial intelligence
Page: 283
----------------------------------------------------------------------------------------------------
l hacking’ team and we have engaged our suppliers to put in place all reasonable measures so that services to Aviva and our customers are protected. We oversee the management of controls for the current risks generative artificial intelligence presents to ensure these remain effective as well as exploit the opportunities for process efficiency, better pricing and underwriting, product personalisation and improved customer service. Overall, Aviva services have

====================================================================================================
Company: Aviva plc
Keyword: artificial intelligence
Page: 338
----------------------------------------------------------------------------------------------------
e risks associated with adoption of and reliance on new and rapidly wider uncertainty around the evolution and impact of climate advancing technologies such as artificial intelligence and quantum change. Climate metrics include estimates of historical emissions computing; the impact of the Group’s risk mitigation strategies

====================================================================================================
Company: Aviva plc
Keyword: fairness
Page: 72
----------------------------------------------------------------------------------------------------
sustainability find solutions. Our Fairness and Our Financ

====================================================================================================
Company: Aviva plc
Keyword: generative AI
Page: 34
----------------------------------------------------------------------------------------------------
d a strong single In 2025, we made significant progress in our cyber exposure management community charity initiatives through the leadership team, optimised pricing with deploying 12 Generative AI solutions to help

====================================================================================================
Company: Aviva plc
Keyword: generative AI
Page: 40
----------------------------------------------------------------------------------------------------
accelerate. This year, we launched a new and progress in the simplification of our in volumes. generative AI tool that enables our We remain the largest combined provideroperations whilst realising additional

In [35]:
# Manual validation outcome for Aviva plc

aviva_mask = manual_review["company_id"] == "006"

manual_review.loc[
    aviva_mask,
    "manual_adjusted_score"
] = 10

manual_review.loc[
    aviva_mask,
    "manual_adjusted_percentage"
] = 71.43

manual_review.loc[
    aviva_mask,
    "reason_for_adjustment"
] = (
    "Score increased from provisional automated score. Aviva provides stronger AI-specific transparency evidence than the "
    "automated score captured, including references to artificial intelligence and generative AI in business transformation. The report also discusses "
    "AI-related risks and controls, cyber resilience, GenAI supplier risks, and the Group Risk Identification Process. Governance and risk scores were therefore increased. "
    "However, no clear evidence was found for human-in-the-loop review in AI-supported decisions. "
    "Fairness references appear mostly general rather than AI-specific, so the ethics/fairness score was not increased."
)

manual_review.loc[
    aviva_mask,
    "important_pages"
] = "5, 28, 34, 35, 40, 46, 80, 81, 84, 85, 101, 102, 109, 283, 338"

manual_review.loc[
    aviva_mask,
    "important_extracts"
] = (
    "Aviva refers to artificial intelligence as part of its technology portfolio and transformation with data and AI; "
    "the report mentions deploying 12 Generative AI solutions and launching a new Generative AI tool; "
    "the report discusses risks associated with adoption and reliance on rapidly advancing technologies such as AI and quantum change; "
    "it also references operational risk and control management, AI-related governance, the Group Risk Identification Process, "
    "supplier controls around GenAI risks, cyber resilience and Board or organisational review of AI-related skills and capability."
)

manual_review.loc[
    aviva_mask,
    "review_status"
] = "Reviewed - score increased"

manual_review.to_csv(
    manual_review_file,
    index=False
)

manual_review[manual_review["company_id"] == "006"]

,company_id,company_name,total_ai_transparency_mentions,unique_keywords,unique_pages,total_score,score_percentage,manual_adjusted_score,manual_adjusted_percentage,reason_for_adjustment,important_pages,important_extracts,review_status
9,006,Aviva plc,91,5,33,6,42.86,10.0,71.43,"Score increased from provisional automated score. Aviva provides stronger AI-specific transparency evidence than the automated score captured, including references to artificial intelligence and generative AI in business transformation. The report also discusses AI-related risks and controls, cyber resilience, GenAI supplier risks, and the Group Risk Identification Process. Governance and risk scores were therefore increased. However, no clear evidence was found for human-in-the-loop review in AI-supported decisions. Fairness references appear mostly general rather than AI-specific, so the ethics/fairness score was not increased.","5, 28, 34, 35, 40, 46, 80, 81, 84, 85, 101, 102, 109, 283, 338","Aviva refers to artificial intelligence as part of its technology portfolio and transformation with data and AI; the report mentions deploying 12 Generative AI solutions and launching a new Generative AI tool; the report discusses risks associated with adoption and reliance on rapidly advancing technologies such as AI and quantum change; it also references operational risk and control management, AI-related governance, the Group Risk Identification Process, supplier controls around GenAI risks, cyber resilience and Board or organisational review of AI-related skills and capability.",Reviewed - score increased

In [36]:
def show_contexts_for_company(company_id, keywords=None, max_items=35):
    """
    Displays extracted AI/transparency-related evidence for one company.
    Uses the manual_review dataframe.
    """

    company_id = str(company_id).zfill(3)

    df = manual_review.copy()
    df["company_id"] = df["company_id"].astype(str).str.zfill(3)

    company_df = df[df["company_id"] == company_id].copy()

    if keywords is not None:
        keywords_lower = [k.lower() for k in keywords]
        company_df = company_df[
            company_df["keyword"].astype(str).str.lower().isin(keywords_lower)
        ]

    company_df = company_df.sort_values(
        by=["keyword", "page_number"],
        ascending=[True, True]
    ).head(max_items)

    if company_df.empty:
        print(f"No matching contexts found for company_id {company_id}.")
        return

    for _, row in company_df.iterrows():
        print("=" * 100)
        print(f"Company: {row.get('company_name', '')}")
        print(f"Keyword: {row.get('keyword', '')}")
        print(f"Page: {row.get('page_number', '')}")
        print("-" * 100)
        print(row.get("context", ""))
        print()

In [37]:
# Reviewing AI transparency evidence for Legal & General Group plc

show_contexts_for_company(
    company_id="007",
    keywords=[
        "artificial intelligence",
        "AI",
        "machine learning",
        "generative AI",
        "GenAI",
        "algorithm",
        "automation",
        "automated decision-making",
        "responsible AI",
        "AI ethics",
        "ethical AI",
        "human oversight",
        "human review",
        "human-in-the-loop",
        "bias",
        "fairness",
        "model risk",
        "data science",
        "analytics"
    ],
    max_items=35
)

KeyError: 'keyword'

In [39]:
import pandas as pd
import os

In [40]:
manual_review.columns.tolist()

['company_id',
 'company_name',
 'total_ai_transparency_mentions',
 'unique_keywords',
 'unique_pages',
 'total_score',
 'score_percentage',
 'manual_adjusted_score',
 'manual_adjusted_percentage',
 'reason_for_adjustment',
 'important_pages',
 'important_extracts',
 'review_status']

In [41]:
ai_mentions.columns.tolist()

['company_id',
 'company_name',
 'report_year',
 'source_file',
 'category',
 'keyword',
 'search_variant',
 'page_number',
 'matched_text',
 'context']

In [42]:
def show_contexts_for_company(company_id, keywords=None, max_items=35):
    """
    Shows detailed AI transparency evidence for one company.
    Uses ai_mentions because this dataframe contains keyword, page_number, matched_text, and context.
    """

    df = ai_mentions.copy()

    df["company_id"] = df["company_id"].astype(str).str.zfill(3)
    company_id = str(company_id).zfill(3)

    company_df = df[df["company_id"] == company_id].copy()

    if keywords is not None:
        keywords_lower = [k.lower() for k in keywords]
        company_df = company_df[
            company_df["keyword"].astype(str).str.lower().isin(keywords_lower)
        ]

    company_df = company_df.sort_values(
        by=["keyword", "page_number"],
        ascending=[True, True]
    ).head(max_items)

    if company_df.empty:
        print(f"No matching evidence found for company_id {company_id}.")
        return

    for _, row in company_df.iterrows():
        print("=" * 100)
        print(f"Company: {row['company_name']}")
        print(f"Keyword: {row['keyword']}")
        print(f"Page: {row['page_number']}")
        print("-" * 100)
        print(row["context"])
        print()

In [43]:
show_contexts_for_company(
    company_id="007",
    keywords=[
        "artificial intelligence",
        "AI",
        "machine learning",
        "generative AI",
        "GenAI",
        "algorithm",
        "automation",
        "automated decision-making",
        "responsible AI",
        "AI ethics",
        "ethical AI",
        "human oversight",
        "human review",
        "human-in-the-loop",
        "bias",
        "fairness",
        "model risk",
        "data science",
        "analytics"
    ],
    max_items=35
)

====================================================================================================
Company: Legal & General Group plc
Keyword: AI
Page: 5
----------------------------------------------------------------------------------------------------
ust also respond to emerging trends, including developments in ArtificialIn February 2025, we announced a Intelligence (AI). In 2026, we plan to£1.8 billion transaction with Japanese introduce AI-powered features to someinsurer Meiji Yasuda Life, which saw them

====================================================================================================
Company: Legal & General Group plc
Keyword: AI
Page: 5
----------------------------------------------------------------------------------------------------
ficialIn February 2025, we announced a Intelligence (AI). In 2026, we plan to£1.8 billion transaction with Japanese introduce AI-powered features to someinsurer Meiji Yasuda Life, which saw them of our customer facing platforms withacquire our US protection business and, at

====================================================================================================
Company: Legal & General Group plc
Keyword: AI
Page: 5
----------------------------------------------------------------------------------------------------
ish a long-term strategic through personalisation, faster service,partnership with L&G to strengthen our and more intuitive digital journeys. AI is Sir John Kingmanposition in US PRT. Following completion an opportunity for the Group to improve Chairof the transaction in 2026, Meiji Yasuda

====================================================================================================
Company: Legal & General Group plc
Keyword: AI
Page: 7
----------------------------------------------------------------------------------------------------
ecution We secure and protect the retirement benefits for pension scheme members in the world’s three largest PRT markets: the UK, the Our strategic partnerships L&G has expanded its Our new ‘AI for Business US and Canada. enhance our capabilities Guided Retirement Value’ programme and strengthen our Planner

====================================================================================================
Company: Legal & General Group plc
Keyword: AI
Page: 7
----------------------------------------------------------------------------------------------------
of our US protection support to build stronger position, upskilling within their schemes. business and building a long-term retirement colleagues to deploy AI partnership with Meiji outcomes, and boost where it can drive the Yasuda has helped financ

====================================================================================================
Company: Legal & General Group plc
Keyword: AI
Page: 8
----------------------------------------------------------------------------------------------------
re we can deliver the strongest returns. Our collaboration with more future proof business. Growing Microsoft to introduce an AI enabled We delivered strong financial and strategic customer service platform will improve outcomes across our businesses. Institutional the experience for our Retail customers Retirement wrote £11.8 billio

====================================================================================================
Company: Legal & General Group plc
Keyword: AI
Page: 24
----------------------------------------------------------------------------------------------------
actions with colleagues will be£1,753 million, supported by sustained Service (ICS) score of 83.7. This is further enhanced by AI-enabled agentic assistance, andcustomer demand and our competitive demonstrated by recognition of our frontline we are reducing complexity for our em

====================================================================================================
Company: Legal & General Group plc
Keyword: AI
Page: 32
----------------------------------------------------------------------------------------------------
Asset Management downgraded, and investments prove ineffective resulting in loss. Retail Disruptive technology, including AI, impacting the value of investments. Increased frequency and severity of extreme weather events or increased nature l

====================================================================================================
Company: Legal & General Group plc
Keyword: AI
Page: 44
----------------------------------------------------------------------------------------------------
rate movements and levels, maintaining consumer and business confidence amidst international trade tensions inflation can also change the value of our obligations and and managing employment while pursuing AI-driven productivity gains. although we seek to match assets and liabilities, losses can Geopolitical risks are elevated, with growing violent conflicts

====================================================================================================
Company: Legal & General Group plc
Keyword: AI
Page: 48
----------------------------------------------------------------------------------------------------
gement New entrants and/or new technology may We continuously monitor the factors that may impact the markets in which we operate. disrupt the markets in which we operate. We have responded to rapid advancement in AI capabilities, developed both in-house and provided by third parties, through the development of a Central AI Inventory and intake Risk Category

====================================================================================================
Company: Legal & General Group plc
Keyword: AI
Page: 48
----------------------------------------------------------------------------------------------------
rate. We have responded to rapid advancement in AI capabilities, developed both in-house and provided by third parties, through the development of a Central AI Inventory and intake Risk Category Strategic process that triages AI Use Cases according to their AI Risk level, facilitating proportionate

====================================================================================================
Company: Legal & General Group plc
Keyword: AI
Page: 48
----------------------------------------------------------------------------------------------------
provided by third parties, through the development of a Central AI Inventory and intake Risk Category Strategic process that triages AI Use Cases according to their AI Risk level, facilitating proportionate second line AI Risk oversight. This is facilitated by ongoing work from the AI Governance R

====================================================================================================
Company: Legal & General Group plc
Keyword: AI
Page: 48
----------------------------------------------------------------------------------------------------
provided by third parties, through the development of a Central AI Inventory and intake Risk Category Strategic process that triages AI Use Cases according to their AI Risk level, facilitating proportionate second line AI Risk oversight. This is facilitated by ongoing work from the AI Governance Risk Priority

====================================================================================================
Company: Legal & General Group plc
Keyword: AI
Page: 48
----------------------------------------------------------------------------------------------------
ategory Strategic process that triages AI Use Cases according to their AI Risk level, facilitating proportionate second line AI Risk oversight. This is facilitated by ongoing work from the AI Governance Risk Priority Medium Program, who are responsible for maturing our overall AI Risk and Governance posture as

====================================================================================================
Company: Legal & General Group plc
Keyword: AI
Page: 48
----------------------------------------------------------------------------------------------------
that triages AI Use Cases according to their AI Risk level, facilitating proportionate second line AI Risk oversight. This is facilitated by ongoing work from the AI Governance Risk Priority Medium Program, who are responsible for maturing our overall AI Risk and Governance posture as well a

====================================================================================================
Company: Legal & General Group plc
Keyword: AI
Page: 48
----------------------------------------------------------------------------------------------------
second line AI Risk oversight. This is facilitated by ongoing work from the AI Governance Risk Priority Medium Program, who are responsible for maturing our overall AI Risk and Governance posture as well as the delivery of a secure environment for internal experimentation. Risk Climate/ Perception Stable

====================================================================================================
Company: Legal & General Group plc
Keyword: AI
Page: 48
----------------------------------------------------------------------------------------------------
he delivery of a secure environment for internal experimentation. Risk Climate/ Perception Stable Our regulatory developments remains apprised of the AI landscape across all our jurisdictions. There is already strong competition in our markets and We have been actively engaged in numerous consultations in relation to AI and generative

====================================================================================================
Company: Legal & General Group plc
Keyword: AI
Page: 48
----------------------------------------------------------------------------------------------------
apprised of the AI landscape across all our jurisdictions. There is already strong competition in our markets and We have been actively engaged in numerous consultations in relation to AI and generative AI, although we have had considerable past success at building including the FCA’s recent 'Mills Review'. scale to offer low-cost products,

====================================================================================================
Company: Legal & General Group plc
Keyword: AI
Page: 48
----------------------------------------------------------------------------------------------------
landscape across all our jurisdictions. There is already strong competition in our markets and We have been actively engaged in numerous consultations in relation to AI and generative AI, although we have had considerable past success at building including the FCA’s recent 'Mills Review'. scale to offer low-cost products, we recognise that

====================================================================================================
Company: Legal & General Group plc
Keyword: AI
Page: 48
----------------------------------------------------------------------------------------------------
Mills Review'. scale to offer low-cost products, we recognise that markets remain attractive to new entrants. Outlook We continue to invest in automation and AI to enhance operational efficiency and deliverWe are also mindful of competitors who may have lower better customer outcomes. The use of AI could bring sig

====================================================================================================
Company: Legal & General Group plc
Keyword: AI
Page: 48
----------------------------------------------------------------------------------------------------
automation and AI to enhance operational efficiency and deliverWe are also mindful of competitors who may have lower better customer outcomes. The use of AI could bring significant positive benefits, and we are return on capital requirements or be unconstrained by alive to the risks of moving too slowly an

====================================================================================================
Company: Legal & General Group plc
Keyword: AI
Page: 48
----------------------------------------------------------------------------------------------------
e to the risks of moving too slowly and therefore of missing out on those benefits. Solvency UK. We remain actively engaged with the UK Government on developments such as the Pensions AI has the potential to significantly disrupt the markets in Bill and are well-positioned to respond to pensions reforms. which we operate by (1

====================================================================================================
Company: Legal & General Group plc
Keyword: AI
Page: 48
----------------------------------------------------------------------------------------------------
hrough a carefully phased migration approach. exposed to cyber threats including the risks of data theft and fraud and more generally it is imperative that we maintain the We are closely monitoring the rapid growth of AI given its potential to significantly influence privacy of our customers' and clients’ personal data. There is business outcomes both positively and adversely. While AI offers opportunities to enhance also strong st

====================================================================================================
Company: Legal & General Group plc
Keyword: AI
Page: 48
----------------------------------------------------------------------------------------------------
We are closely monitoring the rapid growth of AI given its potential to significantly influence privacy of our customers' and clients’ personal data. There is business outcomes both positively and adversely. While AI offers opportunities to enhance also strong stakeholder expectation that our core business customer experience and streamline operations, it also introduces additional risk. We have services are resilient to oper

====================================================================================================
Company: Legal & General Group plc
Keyword: AI
Page: 48
----------------------------------------------------------------------------------------------------
stakeholder expectation that our core business customer experience and streamline operations, it also introduces additional risk. We have services are resilient to operational disruption. approached AI Risk through a bifurcated taxonomy strategy, wherein a dedicated new 'AI Risk' NFR category captures those risks that are truly unique to AI is j

====================================================================================================
Company: Legal & General Group plc
Keyword: AI
Page: 48
----------------------------------------------------------------------------------------------------
vices are resilient to operational disruption. approached AI Risk through a bifurcated taxonomy strategy, wherein a dedicated new 'AI Risk' NFR category captures those risks that are truly unique to AI is joined by the identification of those existing risk categories and controls,

====================================================================================================
Company: Legal & General Group plc
Keyword: AI
Page: 48
----------------------------------------------------------------------------------------------------
ched AI Risk through a bifurcated taxonomy strategy, wherein a dedicated new 'AI Risk' NFR category captures those risks that are truly unique to AI is joined by the identification of those existing risk categories and controls, across our other risk categories,

====================================================================================================
Company: Legal & General Group plc
Keyword: AI
Page: 48
----------------------------------------------------------------------------------------------------
identification of those existing risk categories and controls, across our other risk categories, that are relevant to the articulation and management of AI Risk. Our increasing reliance on accurate, secure and well governed ‘Data’ reinforces the importance

====================================================================================================
Company: Legal & General Group plc
Keyword: AI
Page: 48
----------------------------------------------------------------------------------------------------
of ongoing enhancements to the L&G Data Management Framework, which is a critical enabler of safe and effective AI use, development, and deployment. Risks and uncertainties Risk management The successful delivery of our strategy is Our processes include the active identification

====================================================================================================
Company: Legal & General Group plc
Keyword: AI
Page: 57
----------------------------------------------------------------------------------------------------
le for remuneration policy. management policies and the activities of the Strategy, including data overseeing the Group’s and procedures. Internal Audit function. and AI. governance framework. Read more on Read more on Read more on Read more on Read more on pages 69 to 74 p

====================================================================================================
Company: Legal & General Group plc
Keyword: AI
Page: 60
----------------------------------------------------------------------------------------------------
ormance review process. We've also Board and the GMC and reporting of the Voice invested in assets like the 'People Change survey results has been further enhanced using Playbook' which gives greater specificity to AI-generated personas derived from employee leaders about how they need to show up comments, to deep dive into specific themes. and lead change. Whilst these initiatives are These personas add depth to the quantitat

====================================================================================================
Company: Legal & General Group plc
Keyword: AI
Page: 70
----------------------------------------------------------------------------------------------------
nced working environment. • In November 2025, the Board visited L&G’s Hove office, where they participated in sessions with employees which focused on cyber security and AI. Employees were also invited to attend a panel discussion featuring strategic partners, as well as a town hall event with the Group CEO and Group Chair. Other considerations in the Act Likely co

====================================================================================================
Company: Legal & General Group plc
Keyword: AI
Page: 77
----------------------------------------------------------------------------------------------------
erprise Technology Strategy, designed to support the Group’s strategic by independent Cyber Security and including Data and AI. ambition to build a simpler, better-connected Information Technology advisers, who • Review and endorse the Enterprise

====================================================================================================
Company: Legal & General Group plc
Keyword: AI
Page: 77
----------------------------------------------------------------------------------------------------
trategy, including Data digital experiences, simplify operations, and and AI and their respective Meeting attendance ensure that technology is effectively exploited implementation plans.

====================================================================================================
Company: Legal & General Group plc
Keyword: AI
Page: 77
----------------------------------------------------------------------------------------------------
endorsed the creation of a multi-year • Consider current capabilities relating Philip Broadley2 2/2 1/1 to technology, data, AI and digital skills roadmap to support long-term planning. and plans to address any gaps. The strategy is being embedded into divisional 1. Unable

In [44]:
# Manual review for Legal & General Group plc

company_id = "007"

# Make sure company_id is treated consistently as a 3-digit string
manual_review["company_id"] = manual_review["company_id"].astype(str).str.zfill(3)

# Make sure text columns can accept written notes
text_cols = [
    "reason_for_adjustment",
    "important_pages",
    "important_extracts",
    "review_status"
]

for col in text_cols:
    if col in manual_review.columns:
        manual_review[col] = manual_review[col].astype("object")

mask = manual_review["company_id"] == company_id

# Keep the original score because the evidence supports the provisional ranking
manual_review.loc[mask, "manual_adjusted_score"] = manual_review.loc[mask, "total_score"]
manual_review.loc[mask, "manual_adjusted_percentage"] = manual_review.loc[mask, "score_percentage"]

manual_review.loc[mask, "reason_for_adjustment"] = (
    "No adjustment made. Legal & General shows strong AI transparency evidence, particularly around AI risk governance. "
    "The disclosures mention a dedicated AI Risk non-financial risk category, a Central AI Inventory, risk intake process, "
    "AI use-case triage by risk level, second-line AI risk oversight, and an AI governance programme. Some extracted contexts "
    "are repetitive, especially around page 48, but the underlying evidence supports retaining the provisional transparency score."
)

manual_review.loc[mask, "important_pages"] = "5, 7, 8, 24, 44, 48, 57, 70, 77"

manual_review.loc[mask, "important_extracts"] = (
    "Page 48: AI risk, privacy, operational disruption, dedicated AI Risk NFR category, Central AI Inventory, "
    "risk intake process, use-case triage, second-line AI risk oversight, and AI governance programme. "
    "Page 77: Data and AI strategy, cyber security, technology advisers, and technology implementation planning. "
    "Pages 5, 7, 8, 24 and 44: AI-powered features, customer outcomes, operational efficiency, productivity gains, "
    "and AI-enabled support."
)

manual_review.loc[mask, "review_status"] = "Reviewed - provisional score retained"

# Save updated manual review file
manual_review.to_csv(manual_review_file, index=False)

# Check the saved review row
manual_review.loc[mask]

,company_id,company_name,total_ai_transparency_mentions,unique_keywords,unique_pages,total_score,score_percentage,manual_adjusted_score,manual_adjusted_percentage,reason_for_adjustment,important_pages,important_extracts,review_status
10,007,Legal & General Group plc,51,5,19,6,42.86,6.0,42.86,"No adjustment made. Legal & General shows strong AI transparency evidence, particularly around AI risk governance. The disclosures mention a dedicated AI Risk non-financial risk category, a Central AI Inventory, risk intake process, AI use-case triage by risk level, second-line AI risk oversight, and an AI governance programme. Some extracted contexts are repetitive, especially around page 48, but the underlying evidence supports retaining the provisional transparency score.","5, 7, 8, 24, 44, 48, 57, 70, 77","Page 48: AI risk, privacy, operational disruption, dedicated AI Risk NFR category, Central AI Inventory, risk intake process, use-case triage, second-line AI risk oversight, and AI governance programme. Page 77: Data and AI strategy, cyber security, technology advisers, and technology implementation planning. Pages 5, 7, 8, 24 and 44: AI-powered features, customer outcomes, operational efficiency, productivity gains, and AI-enabled support.",Reviewed - provisional score retained

In [45]:
# Moving to the next company for manual validation

# Making IDs consistent
manual_review["company_id"] = manual_review["company_id"].astype(str).str.zfill(3)
ai_mentions["company_id"] = ai_mentions["company_id"].astype(str).str.zfill(3)

# Identifying companies not yet manually reviewed
review_status = manual_review["review_status"].fillna("").astype(str)

next_company = manual_review[
    ~review_status.str.contains("Reviewed", case=False, na=False)
].head(1)

next_company

,company_id,company_name,total_ai_transparency_mentions,unique_keywords,unique_pages,total_score,score_percentage,manual_adjusted_score,manual_adjusted_percentage,reason_for_adjustment,important_pages,important_extracts,review_status
11,014,Wise plc,29,6,10,6,42.86,NaN,NaN,NaN,NaN,NaN,Pending manual review

In [46]:
# AI transparency evidence for the next unreviewed company

company_id = next_company["company_id"].iloc[0]
company_name = next_company["company_name"].iloc[0]

print("Next company for review:")
print(company_id, "-", company_name)

keywords = [
    "artificial intelligence",
    "AI",
    "machine learning",
    "generative AI",
    "GenAI",
    "algorithm",
    "automation",
    "automated decision-making",
    "responsible AI",
    "AI ethics",
    "ethical AI",
    "human oversight",
    "human review",
    "human-in-the-loop",
    "bias",
    "fairness",
    "model risk",
    "data science",
    "analytics"
]

keywords_lower = [k.lower() for k in keywords]

company_mentions = ai_mentions[
    (ai_mentions["company_id"] == company_id) &
    (ai_mentions["keyword"].astype(str).str.lower().isin(keywords_lower))
].copy()

company_mentions = company_mentions.sort_values(
    by=["keyword", "page_number"],
    ascending=[True, True]
).head(40)

for _, row in company_mentions.iterrows():
    print("=" * 100)
    print(f"Company: {row['company_name']}")
    print(f"Keyword: {row['keyword']}")
    print(f"Page: {row['page_number']}")
    print("-" * 100)
    print(row["context"])

Next company for review:
014 - Wise plc
====================================================================================================
Company: Wise plc
Keyword: AI
Page: 21
----------------------------------------------------------------------------------------------------
service, it should be as easy and frictionless as possible. We have invested in AI, as well as our servicing team, to reduce contact rates; last year bringing the contact rate per active user to around
====================================================================================================
Company: Wise plc
Keyword: AI
Page: 21
----------------------------------------------------------------------------------------------------
hours. We will continue to invest in improving the service we offer our customers and we are focusing on leveraging AI and automation tools to deliver a better experience and to keep customer money moving around the world
====================================================================================================
Company: Wise plc
Keyword: AI
Page: 23
----------------------------------------------------------------------------------------------------
the biggest areas of progress in What differentiates Servicing at Wise from How are you using automation and Servicing this year? the competition? AI in Servicing? We are constantly striving towards our ‘instant’ goal, to Our customers are truly global and therefore so is our Today, we process over a million documents a month not make our customers
====================================================================================================
Company: Wise plc
Keyword: AI
Page: 23
----------------------------------------------------------------------------------------------------
so is our Today, we process over a million documents a month not make our customers wait more than 1 minute for live service. This means that our customers can expect the using automation and AI, and our single global view of all support, or more than 1 hour for back-office cases, and same level of service no matter where they are. We have the transactions helps us continue to leverage this technolog
====================================================================================================
Company: Wise plc
Keyword: AI
Page: 23
----------------------------------------------------------------------------------------------------
ed To get there, we’ve been investing heavily in the latest continuity, which means we’re not reliant on one site or Large Language Model-driven co-pilots for teams in Financial technology, especially AI, alongside our 7,000+ strong country to operate. Crime and Customer Support, to help agents hone their Servicing team of in-house and outsourced agents, to ensure
====================================================================================================
Company: Wise plc
Keyword: AI
Page: 36
----------------------------------------------------------------------------------------------------
siness growth, creating out a shared service operating model to centralise processes, an irresistible employee experience to enhance the customer and using AI-driven tools to streamline query resolution and experience, and ensuring our ways of working are optimised improve employee experience globally. We wi
====================================================================================================
Company: Wise plc
Keyword: AI
Page: 43
----------------------------------------------------------------------------------------------------
eam to improve the way we identify and manage In FY2025, Wise recruited: risk around our activities and processes related to employees. FY2026.knowledgeThismanagement,model integratesand AI-drivencentralisedtoolsprocesses,to streamlinerobust 43 interns, 73 graduates, We assess and report on people risk on a quarterly basis in query resolution and improve employee experience globally
====================================================================================================
Company: Wise plc
Keyword: AI
Page: 43
----------------------------------------------------------------------------------------------------
analyse employee queries in order to identify key pain points. We then built, tested and ran a pilot of an AI-powered bot. This “The Servicing Operations graduate We launched three new benefits platform implementations service aims to resolve employee queries more efficiently and program offers invaluable lear
====================================================================================================
Company: Wise plc
Keyword: AI
Page: 67
----------------------------------------------------------------------------------------------------
proposed. Customer experience and feedback are critical inputs into our design and planning Technological – Emergence of new technology, Resilience; Cyber; Data • Oversight through AI Forum and AI governance action plan like generative artificial intelligence (AI), creates Privacy; Financial Crime; • Additional vendor technology usage controls introduced in due diligence and ongoing monito
====================================================================================================
Company: Wise plc
Keyword: AI
Page: 67
----------------------------------------------------------------------------------------------------
proposed. Customer experience and feedback are critical inputs into our design and planning Technological – Emergence of new technology, Resilience; Cyber; Data • Oversight through AI Forum and AI governance action plan like generative artificial intelligence (AI), creates Privacy; Financial Crime; • Additional vendor technology usage controls introduced in due diligence and ongoing monitoring new ris
====================================================================================================
Company: Wise plc
Keyword: AI
Page: 67
----------------------------------------------------------------------------------------------------
inputs into our design and planning Technological – Emergence of new technology, Resilience; Cyber; Data • Oversight through AI Forum and AI governance action plan like generative artificial intelligence (AI), creates Privacy; Financial Crime; • Additional vendor technology usage controls introduced in due diligence and ongoing monitoring new risks through both industry and threat Operations
====================================================================================================
Company: Wise plc
Keyword: AI
Page: 68
----------------------------------------------------------------------------------------------------
to a combination of internal and external factors. prevent customers using our services for financial crimes, such as money • Customer due diligence helps us to know who our customers AI’s growing role will both empower criminals and enhance our laundering, bribery and corruption are and how they utilise our services defences, particularly against identity
====================================================================================================
Company: Wise plc
Keyword: AI
Page: 69
----------------------------------------------------------------------------------------------------
s growing, Wise is likely to become a more of users through the improper use or system attacks. If this happens, our comprehensive incident attractive target for cyber attackers. Increasing use of AI to develop disclosure of their personal information. response procedures help us respond at speed. We have a robust highly targeted phishing attacks, bypass detection, and develop
====================================================================================================
Company: Wise plc
Keyword: artificial intelligence
Page: 62
----------------------------------------------------------------------------------------------------
We expect to focus on model risk and the governance of At Wise we recognise that good risk management enables management system. This has significantly improved feedback artificial intelligence, as well as further strengthening our the business to make better decisions, avoid pitfalls, loops between risk controls and risk assessments, and has defences in financial crime where we will uplift
====================================================================================================
Company: Wise plc
Keyword: artificial intelligence
Page: 62
----------------------------------------------------------------------------------------------------
to in GRC tooling, process mapping, risk analytics, report capabilities in both the first and second lines of defence. relevant controls. This will help us in several ways to measure automation, artificial intelligence and Large Language We have made significant new specialist hires within the control effectiveness and reflect improved risk assessments; Model integrations. Risk and Product Compliance teams at both a Gr
====================================================================================================
Company: Wise plc
Keyword: artificial intelligence
Page: 67
----------------------------------------------------------------------------------------------------
and feedback are critical inputs into our design and planning Technological – Emergence of new technology, Resilience; Cyber; Data • Oversight through AI Forum and AI governance action plan like generative artificial intelligence (AI), creates Privacy; Financial Crime; • Additional vendor technology usage controls introduced in due diligence and ongoing monitoring new risks through both industry and threat Operations
====================================================================================================
Company: Wise plc
Keyword: automation
Page: 21
----------------------------------------------------------------------------------------------------
o invest in improving the service we offer our customers and we are focusing on leveraging AI and automation tools to deliver a better experience and to keep customer money moving around the world. Last year, we
====================================================================================================
Company: Wise plc
Keyword: automation
Page: 22
----------------------------------------------------------------------------------------------------
split across 26 sites 3.5 million+ 6 30% transactions per day direct connections to domestic payment rails automation rate (2 more coming in FY2026) (proportion of manual workload automated) 1,000+ cloud-based services powerin
====================================================================================================
Company: Wise plc
Keyword: automation
Page: 23
----------------------------------------------------------------------------------------------------
Wise Annual Report and Accounts 2025 21 Q&A with Rohan Basu, Head of Global Operations What have been the biggest areas of progress in What differentiates Servicing at Wise from How are you using automation and Servicing this year? the competition? AI in Servicing? We are constantly striving towards our ‘instant’ goal, to Our customers are truly global
====================================================================================================
Company: Wise plc
Keyword: automation
Page: 23
----------------------------------------------------------------------------------------------------
and therefore so is our Today, we process over a million documents a month not make our customers wait more than 1 minute for live service. This means that our customers can expect the using automation and AI, and our single global view of all support, or more than 1 hour for back-office cases, and same level of service no matter where they are. We have the transactions helps us continue to leverage this te
====================================================================================================
Company: Wise plc
Keyword: automation
Page: 23
----------------------------------------------------------------------------------------------------
Crime and Customer Support, to help agents hone their Servicing team of in-house and outsourced agents, to ensure precision and efficiency. Our automation rate for manual we can always be there for our customers anywhere in the But beyond that, we also operate in close alignment with workload today is 30% and we keep investing in this space. world. This also a
====================================================================================================
Company: Wise plc
Keyword: automation
Page: 23
----------------------------------------------------------------------------------------------------
take customer calls and work queues once a year. behaviour, and run operations even more efficiently. Wisers in our Servicing team have been scaling and improving the service through automation and use of Large How can Servicing act as an enabler for growth? What’s your most important focus area for the Language Models as well as a ‘chat’ function for customers
====================================================================================================
Company: Wise plc
Keyword: automation
Page: 23
----------------------------------------------------------------------------------------------------
t is responsible for the issue which has arisen. This year process improvements, including ongoing use of automation. we dropped contact rates per active user from over 8.5% to around 7%. We also estimate the cost of each contact, and
====================================================================================================
Company: Wise plc
Keyword: automation
Page: 62
----------------------------------------------------------------------------------------------------
maintained in the GRC We will improve second-line effectiveness through system, and is being enhanced with information from all implementing automation and advanced capabilities Over the past year, we have added significantly to our tests conducted across the three lines of defence linked to in GRC tooling, process mapping, risk analytics, report
====================================================================================================
Company: Wise plc
Keyword: automation
Page: 62
----------------------------------------------------------------------------------------------------
fence linked to in GRC tooling, process mapping, risk analytics, report capabilities in both the first and second lines of defence. relevant controls. This will help us in several ways to measure automation, artificial intelligence and Large Language We have made significant new specialist hires within the control effectiveness and reflect improved risk assessments; Model integrations. Risk and Product Comp
====================================================================================================
Company: Wise plc
Keyword: bias
Page: 39
----------------------------------------------------------------------------------------------------
• Inclusive Ways of Working • Uncovering Unconscious Bias
====================================================================================================
Company: Wise plc
Keyword: machine learning
Page: 22
----------------------------------------------------------------------------------------------------
contact rate Proprietary Mastercard 24/7 coverage machine learning and Visa approach to fight financial crime, predict card issuance partnerships treasury money movements and help our customer support teams be more efficient

In [47]:
# Manual review for Wise plc

company_id = "014"

mask = manual_review["company_id"].astype(str).str.zfill(3) == company_id

manual_review.loc[mask, "manual_adjusted_score"] = manual_review.loc[mask, "total_score"]
manual_review.loc[mask, "manual_adjusted_percentage"] = manual_review.loc[mask, "score_percentage"]

manual_review.loc[mask, "reason_for_adjustment"] = (
    "No adjustment made. Wise shows repeated AI-related disclosures across operational use, "
    "automation, customer servicing, Large Language Models, model risk, AI governance, financial crime, "
    "privacy and vendor technology risk. Some extracts are fragmented, but the overall evidence supports "
    "retaining the provisional transparency score."
)

manual_review.loc[mask, "important_pages"] = "21, 23, 62, 67, 68, 69"

manual_review.loc[mask, "important_extracts"] = (
    "Wise discusses investment in AI and automation tools to improve customer service and reduce contact rates. "
    "The annual report refers to automation in servicing, use of Large Language Models and chat functions, "
    "processing high volumes of documents through automation and AI, and AI-supported customer support. "
    "Further evidence links AI to model risk, governance, risk analytics, AI Forum oversight, AI governance action plans, "
    "privacy, financial crime, phishing and vendor technology controls."
)

manual_review.loc[mask, "review_status"] = "Reviewed - provisional score retained"

manual_review.to_csv(manual_review_file, index=False)

manual_review.loc[mask]

,company_id,company_name,total_ai_transparency_mentions,unique_keywords,unique_pages,total_score,score_percentage,manual_adjusted_score,manual_adjusted_percentage,reason_for_adjustment,important_pages,important_extracts,review_status
11,014,Wise plc,29,6,10,6,42.86,6.0,42.86,"No adjustment made. Wise shows repeated AI-related disclosures across operational use, automation, customer servicing, Large Language Models, model risk, AI governance, financial crime, privacy and vendor technology risk. Some extracts are fragmented, but the overall evidence supports retaining the provisional transparency score.","21, 23, 62, 67, 68, 69","Wise discusses investment in AI and automation tools to improve customer service and reduce contact rates. The annual report refers to automation in servicing, use of Large Language Models and chat functions, processing high volumes of documents through automation and AI, and AI-supported customer support. Further evidence links AI to model risk, governance, risk analytics, AI Forum oversight, AI governance action plans, privacy, financial crime, phishing and vendor technology controls.",Reviewed - provisional score retained

In [48]:
# Moving to the next company for manual validation

review_status = manual_review["review_status"].fillna("").astype(str)

next_company = manual_review[
    ~review_status.str.contains("Reviewed", case=False, na=False)
].head(1)

next_company

,company_id,company_name,total_ai_transparency_mentions,unique_keywords,unique_pages,total_score,score_percentage,manual_adjusted_score,manual_adjusted_percentage,reason_for_adjustment,important_pages,important_extracts,review_status
12,015,CAB Payments Holdings plc,28,6,16,6,42.86,NaN,NaN,NaN,NaN,NaN,Pending manual review

In [49]:
# Reviewing AI transparency evidence for CAB Payments Holdings plc

show_contexts_for_company(
    company_id="015",
    keywords=[
        "artificial intelligence",
        "AI",
        "machine learning",
        "generative AI",
        "GenAI",
        "algorithm",
        "automation",
        "automated decision-making",
        "responsible AI",
        "AI ethics",
        "ethical AI",
        "human oversight",
        "human review",
        "human-in-the-loop",
        "bias",
        "fairness",
        "model risk",
        "data science",
        "analytics"
    ],
    max_items=35
)

====================================================================================================
Company: CAB Payments Holdings plc
Keyword: AI
Page: 11
----------------------------------------------------------------------------------------------------
ategic Report Governance Statements Appendix 9 Chair’s Statement Embarking upon sustainable growth following a year of reset including AI, and diversified our revenue making as we support the executive team in streams. We are now more efficient, resilient delivering our purpose and strategy.

====================================================================================================
Company: CAB Payments Holdings plc
Keyword: AI
Page: 16
----------------------------------------------------------------------------------------------------
Renminbi (CNY) to offer more non- as fraud detection, compliance, and ■Invested in AI and automation to USD flexibility to clients customer service, ultimately reducing opti

====================================================================================================
Company: CAB Payments Holdings plc
Keyword: AI
Page: 16
----------------------------------------------------------------------------------------------------
ary 2026 partnerships, digital currency solutions, and AI-driven efficiency. Empowering cross-border growth through unrivalled payment flexibi

====================================================================================================
Company: CAB Payments Holdings plc
Keyword: AI
Page: 25
----------------------------------------------------------------------------------------------------
port our communities. Technology and innovation – including the ■Deliver Responsible Business capacity- responsible adoption of AI – are increasingly building and knowledge-sharing vital to delivering against these priorities. programmes for African Central Bankers,

====================================================================================================
Company: CAB Payments Holdings plc
Keyword: AI
Page: 27
----------------------------------------------------------------------------------------------------
including workforce wellbeing and digitalisation and the responsible use of AI. equitable opportunity with environmental We continue to show that responsible

====================================================================================================
Company: CAB Payments Holdings plc
Keyword: AI
Page: 27
----------------------------------------------------------------------------------------------------
technology and data solutions, including We champion equality We understand AI-enabled insights, to improve deliveryvalue. By aligning risk management with and invest in our our impact and are quality, tra

====================================================================================================
Company: CAB Payments Holdings plc
Keyword: AI
Page: 37
----------------------------------------------------------------------------------------------------
acceleration more profitable than the last. We're we're more diversified acrosswe create value and where we're investing. matters because it shows momentum. The investing in that now: automation, and AI- The best things about our culture haven't headline is that our growth is relationship enabled processing will reduce costs per products and geographies and changed. We are purpose and client led and d

====================================================================================================
Company: CAB Payments Holdings plc
Keyword: AI
Page: 48
----------------------------------------------------------------------------------------------------
existing control frameworks. incorporated into our principal risk assessments. In particular, advances in Internal control environmentartificial intelligence (AI) and other emerging technologies have the potential to reshape Embedded within our risk management our competitive position, workforce, and processes are the internal controls operational model. While these

====================================================================================================
Company: CAB Payments Holdings plc
Keyword: AI
Page: 48
----------------------------------------------------------------------------------------------------
limited to financial reporting, commercial,To ensure an informed and coordinated operational and risk and complianceapproach, we have established an AI activities. The control framework includesWorking Group comprising senior leaders risk assessment, control

====================================================================================================
Company: CAB Payments Holdings plc
Keyword: AI
Page: 48
----------------------------------------------------------------------------------------------------
to achieve compliance associated risks, and advising on with the material controls related elements opportunities for their safe and effective use. of the revised UK Corporate Governance In addition, our AI Policy, introduced during Code for our financial year commencing the financial year, provides a framework for 1 January 2026. This will require the Board the responsible adoption of AI across the to include

====================================================================================================
Company: CAB Payments Holdings plc
Keyword: AI
Page: 48
----------------------------------------------------------------------------------------------------
Governance In addition, our AI Policy, introduced during Code for our financial year commencing the financial year, provides a framework for 1 January 2026. This will require the Board the responsible adoption of AI across the to include a declaration in the annual report Group. explaining how it has monitored and reviewed the effectiveness of th

====================================================================================================
Company: CAB Payments Holdings plc
Keyword: AI
Page: 73
----------------------------------------------------------------------------------------------------
ational ■Board composition model. Board members consider there to have been strengths and determining modifications There has been good progress over the ■Monitor investment in AI and automation good progress on the areas of focus that would further improve its fulfilment of year to increase the Board’s diversity, to support developments into digital identified at the

====================================================================================================
Company: CAB Payments Holdings plc
Keyword: AI
Page: 74
----------------------------------------------------------------------------------------------------
ement and external presentations covering critical actions arising from the employee engagement survey. areas such as geographic expansion, cyber security enhancements, technology infrastructure and AI implementation. Risk and compliance Governance and investor relations Key to Strategy lll

====================================================================================================
Company: CAB Payments Holdings plc
Keyword: artificial intelligence
Page: 16
----------------------------------------------------------------------------------------------------
authorities to ensure a compliant this, artificial intelligence is transforming the currency crosses with Chinese solution

====================================================================================================
Company: CAB Payments Holdings plc
Keyword: artificial intelligence
Page: 74
----------------------------------------------------------------------------------------------------
In considering the above, the Board considers the views of all – market view impacted stakeholders whilst acting in the best interests of the – artificial intelligence in industry Company and members as a whole, as set out in the – whistleblowing s172 Statement on pages 56 to 58. – digital currency market evol

====================================================================================================
Company: CAB Payments Holdings plc
Keyword: automation
Page: 16
----------------------------------------------------------------------------------------------------
Renminbi (CNY) to offer more non- as fraud detection, compliance, and ■Invested in AI and automation to USD flexibility to clients customer service, ultimately reducing optimise processing

====================================================================================================
Company: CAB Payments Holdings plc
Keyword: automation
Page: 37
----------------------------------------------------------------------------------------------------
the first. That acceleration more profitable than the last. We're we're more diversified acrosswe create value and where we're investing. matters because it shows momentum. The investing in that now: automation, and AI- The best things about our culture haven't headline is that our growth is relationship enabled processing will reduce costs per products and geographies and changed. We are purpose and client led

====================================================================================================
Company: CAB Payments Holdings plc
Keyword: automation
Page: 43
----------------------------------------------------------------------------------------------------
over time. We expect additional investment in stood at £129.3m (2024: £116.0m) an increase of 12% retaining a £41.1m surplus above the client-facing teams and network to be partially offset by efficiency gains from automation Overall Capital Requirement. and process improvements. Liquidity metrics remain strong with both LCR and NSFR well above regulatory minimums at The Group expects Capi

====================================================================================================
Company: CAB Payments Holdings plc
Keyword: automation
Page: 51
----------------------------------------------------------------------------------------------------
ing hybrid-working and competitive employee benefits. frequently to ensure staffing levels reflect the size and complexity of the ■Process and control automation is proactively considered across the Group, Group. acknowledging that not all processes can be aut

====================================================================================================
Company: CAB Payments Holdings plc
Keyword: automation
Page: 73
----------------------------------------------------------------------------------------------------
■Board composition model. Board members consider there to have been strengths and determining modifications There has been good progress over the ■Monitor investment in AI and automation good progress on the areas of focus that would further improve its fulfilment of year to increase the Board’s diversity, to support developments into digital identified at the start of 2025:

====================================================================================================
Company: CAB Payments Holdings plc
Keyword: automation
Page: 146
----------------------------------------------------------------------------------------------------
8,350 7,599 The monthly average number of full-time equivalent staff employed within the Group, Process automation costs (see Note 32 B(ii)(a)) 2,484 2,115 including Executive Directors, was 362 (2024: 378) and the number of employees at year Professional fees

====================================================================================================
Company: CAB Payments Holdings plc
Keyword: automation
Page: 171
----------------------------------------------------------------------------------------------------
into a one-year contract to assist with the ongoing NICs) 8,344 4,393 automation of manual processes. The following payments are due under the contract: Post-employment benefits 65 141 Share-based payments 365

====================================================================================================
Company: CAB Payments Holdings plc
Keyword: bias
Page: 124
----------------------------------------------------------------------------------------------------
he financial statements (including the risk of override of controls), and determined that the principal risks were related to posting inappropriate journal entries in relation to revenue and cost targets, and management bias in accounting estimates. Audit Other required reporting procedures performed by the engagement team included: Companies Act 2006 exception reporting ■

====================================================================================================
Company: CAB Payments Holdings plc
Keyword: bias
Page: 124
----------------------------------------------------------------------------------------------------
xceptions to report arising from this responsibility. combinations; and ■Challenging significant assumptions and judgements made by management in its Appointment accounting estimates and assessing them for bias. We were first appointed by the Company for the financial year ended 31 December 2025. There are inherent limitations in the audit procedures described above. We are

====================================================================================================
Company: CAB Payments Holdings plc
Keyword: fairness
Page: 25
----------------------------------------------------------------------------------------------------
ty must At the same time, they demand robust Looking to 2026, our efforts will remain drive innovation, value creation, and trust. governance to ensure fairness, focused on embedding sustainability deeper The Responsible Business Board Sub- transparency, and protection of people’s into governance and strategic

====================================================================================================
Company: CAB Payments Holdings plc
Keyword: fairness
Page: 94
----------------------------------------------------------------------------------------------------
and post- key consideration of the Remuneration Directors; Remuneration Committee will engage employment shareholding requirements. Committee will be on fairness and the ■the importance of attracting, retaining, regularly with the Company’s largest ■Predictability – certain elements of the remuneration outcomes across the and motivating high-calibre Exe

====================================================================================================
Company: CAB Payments Holdings plc
Keyword: fairness
Page: 112
----------------------------------------------------------------------------------------------------
he unique contributions of its diverse workforce, fostering a culture of openness, mutual respect, and collaboration. The Group prioritises equal opportunities, ensuring fairness and inclusivity in all aspects of employment with policies prohibiting discrimination based on various factors, including race, gender, disability, and age. Equal oppo

====================================================================================================
Company: CAB Payments Holdings plc
Keyword: machine learning
Page: 50
----------------------------------------------------------------------------------------------------
g upgrades in 2024, Phase 2 enhancements were delivered in 2025, within CAB’s portfolio and Financial Institutions remain the largest segment introducing machine learning capabilities and improved alert handling. Additional of CAB’s Client portfolio. upgrades to sanctions screen

In [54]:
# Manual review for CAB Payments Holdings plc

company_id = "015"

mask = manual_review["company_id"].astype(str).str.zfill(3) == company_id

manual_review.loc[mask, "manual_adjusted_score"] = manual_review.loc[mask, "total_score"]
manual_review.loc[mask, "manual_adjusted_percentage"] = manual_review.loc[mask, "score_percentage"]

manual_review.loc[mask, "reason_for_adjustment"] = (
    "No adjustment made. CAB Payments shows moderate AI transparency evidence, including AI and automation investment, "
    "machine learning capabilities, alert handling, sanctions screening, fraud detection, compliance, customer service, "
    "and references to an AI Policy and Board-level responsibility. Some fairness and bias matches are noisy or unrelated "
    "to AI governance, but the overall evidence supports retaining the provisional transparency score."
)

manual_review.loc[mask, "important_pages"] = "11, 16, 25, 27, 37, 48, 50, 73, 74"

manual_review.loc[mask, "important_extracts"] = (
    "CAB refers to investing in AI and automation for fraud detection, compliance and customer service. "
    "The report mentions machine learning capabilities and improved alert handling. "
    "Evidence also refers to responsible adoption of AI, an AI Policy, and Board responsibility for AI governance. "
    "Further extracts link AI to technology infrastructure, cyber security enhancements and operational efficiency."
)

manual_review.loc[mask, "review_status"] = "Reviewed - provisional score retained"

manual_review.to_csv(manual_review_file, index=False)

manual_review.loc[mask]

,company_id,company_name,total_ai_transparency_mentions,unique_keywords,unique_pages,total_score,score_percentage,manual_adjusted_score,manual_adjusted_percentage,reason_for_adjustment,important_pages,important_extracts,review_status
12,015,CAB Payments Holdings plc,28,6,16,6,42.86,6.0,42.86,"No adjustment made. CAB Payments shows moderate AI transparency evidence, including AI and automation investment, machine learning capabilities, alert handling, sanctions screening, fraud detection, compliance, customer service, and references to an AI Policy and Board-level responsibility. Some fairness and bias matches are noisy or unrelated to AI governance, but the overall evidence supports retaining the provisional transparency score.","11, 16, 25, 27, 37, 48, 50, 73, 74","CAB refers to investing in AI and automation for fraud detection, compliance and customer service. The report mentions machine learning capabilities and improved alert handling. Evidence also refers to responsible adoption of AI, an AI Policy, and Board responsibility for AI governance. Further extracts link AI to technology infrastructure, cyber security enhancements and operational efficiency.",Reviewed - provisional score retained

In [51]:
# Moving to the next company for manual validation

review_status = manual_review["review_status"].fillna("").astype(str)

next_company = manual_review[
    ~review_status.str.contains("Reviewed", case=False, na=False)
].head(1)

next_company

,company_id,company_name,total_ai_transparency_mentions,unique_keywords,unique_pages,total_score,score_percentage,manual_adjusted_score,manual_adjusted_percentage,reason_for_adjustment,important_pages,important_extracts,review_status
13,008,M&G plc,24,5,19,6,42.86,NaN,NaN,NaN,NaN,NaN,Pending manual review

In [52]:
# Reviewing AI transparency evidence for M&G plc

show_contexts_for_company(
    company_id="008",
    keywords=[
        "artificial intelligence",
        "AI",
        "machine learning",
        "generative AI",
        "GenAI",
        "automation",
        "responsible AI",
        "AI ethics",
        "ethical AI",
        "human oversight",
        "human review",
        "human-in-the-loop",
        "automated decision-making",
        "bias",
        "fairness",
        "model risk",
        "data science",
        "analytics"
    ],
    max_items=35
)

====================================================================================================
Company: M&G plc
Keyword: AI
Page: 8
----------------------------------------------------------------------------------------------------
with model, international the use of advanced technology. AI will be an enabler for growth and we remain focused on footprint and depth of our increasing adoption across the business to strengthen investment expertise w

====================================================================================================
Company: M&G plc
Keyword: AI
Page: 15
----------------------------------------------------------------------------------------------------
5-2027. – Simplify and automate our processes, using technology – Leverage the strength of our business model to develop – Maintain a progressive and sustainable dividend policy. and AI, to improve efficiency, service and customer innovative products and investment solutions to meet experience.

====================================================================================================
Company: M&G plc
Keyword: AI
Page: 19
----------------------------------------------------------------------------------------------------
l Our efforts have delivered significant improvements – Advice: At the end of the year, we launched Adviser Hub, processes. This means evolving to a digital-first self-service over 2025: which provides AI-powered support and technical resources model for routine tasks and expert human assistance when – Customer satisfa

====================================================================================================
Company: M&G plc
Keyword: AI
Page: 36
----------------------------------------------------------------------------------------------------
the Chief People Officer and, where appropriate, Directors together with colleagues from a wide range of pace of decision-making and exploring the role of AI in senior management. geographies and levels of seniority, including achiev

====================================================================================================
Company: M&G plc
Keyword: AI
Page: 37
----------------------------------------------------------------------------------------------------
other matters, such as service and complaints. clients to understand their views, discuss ways to further – Technology advancement, digitisation and AI impact enhance our relationships and product offerings and The Board encourages management to improve how they

====================================================================================================
Company: M&G plc
Keyword: AI
Page: 38
----------------------------------------------------------------------------------------------------
rs. Authority (PRA). environment Representatives from the – Sustainability Disclosure During the year, the Board’s activities have included consideration of the Enterprise Data Strategy including AI and a range of FCA attended the February Requirements / Climate matters and decisions relating to strategy and execution. The Board has also considered the Financial Crime Enhancement 2025 Board meeting and

====================================================================================================
Company: M&G plc
Keyword: AI
Page: 48
----------------------------------------------------------------------------------------------------
third-party suppliers. We recognise the potential risks associated with artificial intelligence (AI) and adopt AI solutions in a considered manner, supported by an AI framework, governance structures, oversight and

====================================================================================================
Company: M&G plc
Keyword: AI
Page: 48
----------------------------------------------------------------------------------------------------
ird-party suppliers. We recognise the potential risks associated with artificial intelligence (AI) and adopt AI solutions in a considered manner, supported by an AI framework, governance structures, oversight and training.

====================================================================================================
Company: M&G plc
Keyword: AI
Page: 48
----------------------------------------------------------------------------------------------------
artificial intelligence (AI) and adopt AI solutions in a considered manner, supported by an AI framework, governance structures, oversight and training. 46

====================================================================================================
Company: M&G plc
Keyword: AI
Page: 91
----------------------------------------------------------------------------------------------------
the Board received training from an external Four of the Directors are women, one of the Directors is from a Non-Executive Directors. All Directors are subject to annual subject matter expert on technology, data, AI and cyber minority ethnic background; and two senior positions are held re-election at the Company’s AGM. security. The Board also undertook deep dives on the by women (Senior Independe

====================================================================================================
Company: M&G plc
Keyword: AI
Page: 93
----------------------------------------------------------------------------------------------------
d targets, customer matters, people and culture and transformation. – Annual Board strategy day at which the Group’s strategy was considered and debated. – Reviewed and considered the Group’s AI strategy, including progress on key initiatives. – Reviewed and monitored progress against the Group’s sustainability strategy and objectives. – Approved the strategic partnership with Dai-ic

====================================================================================================
Company: M&G plc
Keyword: AI
Page: 95
----------------------------------------------------------------------------------------------------
– External speakers have joined Board strategy days and dinners. Increase the inclusion of external perspectives at relevant Board dinners and enhance metrics – Technology, Data and AI session was held, as well as sustainability metrics updates and and or information provided on data, digital and Sustainability. management information dashboards included in committee meetin

====================================================================================================
Company: M&G plc
Keyword: AI
Page: 312
----------------------------------------------------------------------------------------------------
0% M&G Investment Funds (10) - M&G China Fund U 74%M&G Affordable Living GP Limited OS 100% M&G Investment Funds (10) - M&G Global AI U 86%M&G Alternatives GP1 Limited OS 100% Themes Fund M&G Alternatives GP2 Limited OS 100% M&G Investment

====================================================================================================
Company: M&G plc
Keyword: artificial intelligence
Page: 43
----------------------------------------------------------------------------------------------------
controls, as well as implementing an enhanced target artificial intelligence and post-quantum computing, suchchallenge. The third line Internal Audit function, empowered operating model. This work would anticipate taking any

====================================================================================================
Company: M&G plc
Keyword: artificial intelligence
Page: 48
----------------------------------------------------------------------------------------------------
third-party suppliers. We recognise the potential risks associated with artificial intelligence (AI) and adopt AI solutions in a considered manner, supported by an AI framework, governance structures, oversight

====================================================================================================
Company: M&G plc
Keyword: artificial intelligence
Page: 49
----------------------------------------------------------------------------------------------------
Champions embedded investor confidence; technological change, particularly adversely impact trust and reputation in our group or across the business support the identification and the responsible use of artificial intelligence; our brands. monitoring of key reputational risks. sustainability and the climate transition, with growing

====================================================================================================
Company: M&G plc
Keyword: artificial intelligence
Page: 309
----------------------------------------------------------------------------------------------------
liquidation) OS 100% M&G (Lux) Investment Funds 1 -M&G (Lux) responsAbility Global Micro and SME U 31% Global Artificial Intelligence Fund U 93% Finance Fund M&G (Lux) Investment Funds 1 - M&G (Lux) U 96% 6, Rue Eugène Ruppert, L-2453 Nature and

====================================================================================================
Company: M&G plc
Keyword: automation
Page: 19
----------------------------------------------------------------------------------------------------
itioned our business for growth by improving with our customers and advisers by increasing our ability to our operational platform and revitalising the range of products interact digitally and through intelligent automation, which we offer to our retail customers, third-party distributors and has contributed to improvements in customer satisfaction corporate clients. With a stronger foundation, we are now well and adviser satisfa

====================================================================================================
Company: M&G plc
Keyword: automation
Page: 19
----------------------------------------------------------------------------------------------------
oposition and the innovative options – We continue to embrace technology and intelligent a 16% increase in satisfaction with call wait times. available to our corporate clients. automation to improve customer service and operational Our efforts have delivered significant improvements – Advice: At the end of the year, we launched Adviser Hub, processes. This means evolving to a digital-first se

====================================================================================================
Company: M&G plc
Keyword: automation
Page: 71
----------------------------------------------------------------------------------------------------
present £4.0bn of AUMA. AUMA. A change in the third-party platform used during the Scope 1 & 2 2025 2024year has introduced greater automation and a more structured estimation hierarchy, which will improve accuracy FCE (kt Ce) 599 466 over time. This change results in some smaller Scope 3 Carbon Footprint (t C O 2 £m

====================================================================================================
Company: M&G plc
Keyword: bias
Page: 145
----------------------------------------------------------------------------------------------------
and considering future events that are inherently uncertain. As in all of our audits, we also addressed the risk of management override of internal controls, including consideration of whether there was evidence of bias that represented a risk of material misstatement due to fraud. – We conducted audit testing over twenty one components. These were selected based on our assessment of inherent risk and their financial significance t

====================================================================================================
Company: M&G plc
Keyword: bias
Page: 158
----------------------------------------------------------------------------------------------------
valuated management’s incentives and opportunities for fraudulent manipulation of the financial statements (including the risk of override of controls), and determined that the principal risks were related to management bias in accounting estimates and judgmental areas of the financial statements as shown in our ‘Key audit matters’, and the override of controls including the posting of inappropriate journal entries. The Group engagement tea

====================================================================================================
Company: M&G plc
Keyword: fairness
Page: 39
----------------------------------------------------------------------------------------------------
ent over 2025. standards and ethical expectations to mitigate risk and promote fairness, including the new duty under the Equality Highlights from our three OneVoice engagement surveys last

====================================================================================================
Company: M&G plc
Keyword: fairness
Page: 109
----------------------------------------------------------------------------------------------------
Committee takes great care to consider the pay and certain former members of senior management including aconditions of the wider workforce with a focus on fairness of former Executive Director, the details of which are provided onremuneration outcomes. Workforce remuneration is also a key

In [57]:
# Manual review for M&G plc

company_id = "008"

mask = manual_review["company_id"].astype(str).str.zfill(3) == company_id

manual_review.loc[mask, "manual_adjusted_score"] = manual_review.loc[mask, "total_score"]
manual_review.loc[mask, "manual_adjusted_percentage"] = manual_review.loc[mask, "score_percentage"]

manual_review.loc[mask, "reason_for_adjustment"] = (
    "No adjustment made. M&G shows moderate AI transparency evidence through references to AI in strategy, The company also refers to adopting AI solutions in a considered manner, "
    "supported by an AI framework, governance structures, oversight and training. Some matches, are noisy or only indirectly relevant, but the stronger governance and usage "
    "evidence supports retaining the provisional transparency score."
)

manual_review.loc[mask, "important_pages"] = "8, 15, 19, 38, 43, 48, 91, 93, 95"

manual_review.loc[mask, "important_extracts"] = (
    "M&G describes AI as an enabler for growth and links AI adoption to strengthening investment expertise. "
    "The report refers to simplifying and automating processes using technology and AI to improve efficiency, service and customer experience. "
    "It also mentions AI-powered support and technical resources for routine tasks, Board-level review of AI strategy, "
    "and third-party supplier risks linked to artificial intelligence. "
)

manual_review.loc[mask, "review_status"] = "Reviewed - provisional score retained"

manual_review.to_csv(manual_review_file, index=False)

manual_review.loc[mask]

,company_id,company_name,total_ai_transparency_mentions,unique_keywords,unique_pages,total_score,score_percentage,manual_adjusted_score,manual_adjusted_percentage,reason_for_adjustment,important_pages,important_extracts,review_status
13,008,M&G plc,24,5,19,6,42.86,6.0,42.86,"No adjustment made. M&G shows moderate AI transparency evidence through references to AI in strategy, The company also refers to adopting AI solutions in a considered manner, supported by an AI framework, governance structures, oversight and training. Some matches, are noisy or only indirectly relevant, but the stronger governance and usage evidence supports retaining the provisional transparency score.","8, 15, 19, 38, 43, 48, 91, 93, 95","M&G describes AI as an enabler for growth and links AI adoption to strengthening investment expertise. The report refers to simplifying and automating processes using technology and AI to improve efficiency, service and customer experience. It also mentions AI-powered support and technical resources for routine tasks, Board-level review of AI strategy, and third-party supplier risks linked to artificial intelligence.",Reviewed - provisional score retained

In [58]:
# Moving to the next company for manual validation

review_status = manual_review["review_status"].fillna("").astype(str)

next_company = manual_review[
    ~review_status.str.contains("Reviewed", case=False, na=False)
].head(1)

next_company

,company_id,company_name,total_ai_transparency_mentions,unique_keywords,unique_pages,total_score,score_percentage,manual_adjusted_score,manual_adjusted_percentage,reason_for_adjustment,important_pages,important_extracts,review_status
14,011,IG Group Holdings plc,22,5,16,6,42.86,NaN,NaN,NaN,NaN,NaN,Pending manual review

In [59]:
# AI transparency evidence for the next company

company_id = next_company["company_id"].astype(str).str.zfill(3).iloc[0]
company_name = next_company["company_name"].iloc[0]

print(f"Next company for review:")
print(f"{company_id} - {company_name}")
print("=" * 100)

keywords = [
    "artificial intelligence",
    "AI",
    "machine learning",
    "generative AI",
    "GenAI",
    "algorithm",
    "automation",
    "automated decision-making",
    "responsible AI",
    "AI ethics",
    "ethical AI",
    "human oversight",
    "human review",
    "human-in-the-loop",
    "bias",
    "fairness",
    "model risk",
    "data science",
    "analytics"
]

keywords_lower = [k.lower() for k in keywords]

company_extracts = ai_mentions[
    (ai_mentions["company_id"].astype(str).str.zfill(3) == company_id) &
    (ai_mentions["keyword"].astype(str).str.lower().isin(keywords_lower))
].sort_values(
    by=["keyword", "page_number"],
    ascending=[True, True]
).head(35)

for _, row in company_extracts.iterrows():
    print("=" * 100)
    print(f"Company: {row['company_name']}")
    print(f"Keyword: {row['keyword']}")
    print(f"Page: {row['page_number']}")
    print("-" * 100)
    print(row["context"])

Next company for review:
011 - IG Group Holdings plc
====================================================================================================
====================================================================================================
Company: IG Group Holdings plc
Keyword: AI
Page: 20
----------------------------------------------------------------------------------------------------
FY23 Reported 358.5 FY23 Reported 72.6 FY23 35% In FY25 we invested in an agile, AI-powered employee The number of active customers is the most relevant metric for First trades refers to a new customer funding their account and Our gender diversity metric represents the percentage
====================================================================================================
Company: IG Group Holdings plc
Keyword: AI
Page: 47
----------------------------------------------------------------------------------------------------
igate the ever-present and changing processes, people, systems, cyber threats or external events.  AI controls ensure that any sensitive information is only used in private, paid for and licensed services so as not to be mad
====================================================================================================
Company: IG Group Holdings plc
Keyword: AI
Page: 47
----------------------------------------------------------------------------------------------------
ng and maturing their attack methods and Trading  A 24/7 approach with trading desks located in London, Frankfurt and Australia providing targets. The incorporation of AI to improve The risk related to any issues around 24-hour coverage. We apply Board-approved market risk limits and operate under a robust efficiency and productivity, as well as our internal hed
====================================================================================================
Company: IG Group Holdings plc
Keyword: AI
Page: 48
----------------------------------------------------------------------------------------------------
ur risk Improving understanding the Group’s business and identify any of the Group’s financial materiality and framework remains culture, processes and and controls around AI areas for potential enhancement. risk framework as we accountability across the effective and agile as we practices across new technology and digital
====================================================================================================
Company: IG Group Holdings plc
Keyword: AI
Page: 61
----------------------------------------------------------------------------------------------------
participated in cryptocurrency market evolution, stakeholder groups. Find out more on pages 72-73 shareholder interactions technology infrastructure, AI implementation and tax planning
====================================================================================================
Company: IG Group Holdings plc
Keyword: AI
Page: 72
----------------------------------------------------------------------------------------------------
ect engagement opportunities 3 Internal evaluation via FY27  Strengthen the Board’s knowledge in areas highlighted by members as priorities, questionnaire and including AI, cybersecurity, crypto, and regulatory landscapes across key markets individual director  Ensure alignment between the Board and Executives on Diversity and Inc
====================================================================================================
Company: IG Group Holdings plc
Keyword: AI
Page: 73
----------------------------------------------------------------------------------------------------
6/11 3/11 2/11 Schedule dedicated training or The Board received training on these topics, including Board discussions on D&I, sessions on AI, crypto, and Powering Inclusion. Board Consumer Marketing 5/11 1/11 6/11 cryptocurrencies and Artificial members have expressed interest
====================================================================================================
Company: IG Group Holdings plc
Keyword: AI
Page: 73
----------------------------------------------------------------------------------------------------
ard Consumer Marketing 5/11 1/11 6/11 cryptocurrencies and Artificial members have expressed interest in continued updates Intelligence (AI) in the context of in these areas, especially as they relate to product Auditing 5/11 4/11 2/11 our business
====================================================================================================
Company: IG Group Holdings plc
Keyword: AI
Page: 87
----------------------------------------------------------------------------------------------------
 Received updates on cryptocurrency hedging developments and approach in March 2025  Reviewed reporting on current and emerging risks facing the business in March 2025 and May 2025, including cyber risk, AI adoption opportunities, and macro factors driving market  Recommended market risk limit increases for equity indices from £200m to £300m to volatility
====================================================================================================
Company: IG Group Holdings plc
Keyword: AI
Page: 87
----------------------------------------------------------------------------------------------------
mber 2024 and May 2025  Recommended the CRO’s annual assessment of the effectiveness of the Risk Management  Considered AI risks in ICARA operational risk scenarios as part of forward-looking stress and Internal Control Framework to the Audit Committee and the Board in May 2025 testing requirements
====================================================================================================
Company: IG Group Holdings plc
Keyword: AI
Page: 88
----------------------------------------------------------------------------------------------------
specific questions, the review found that Other Compliance Matters the Committee had the right combination opportunities associated with AI technology and cryptocurrency in
====================================================================================================
Company: IG Group Holdings plc
Keyword: AI
Page: 88
----------------------------------------------------------------------------------------------------
isional structure Insurance  Reviewed the adequacy of our Global Insurance Programme and recommended the annual renewal proposal for Board approval in March 2025, including consideration of cyber insurance coverage AI and Cryptocurrency  Received reporting on AI opportunities and risks, including efficiency gains in customer servicing and manual processes, while monitoring management’s measured approach to implementation with pr
====================================================================================================
Company: IG Group Holdings plc
Keyword: AI
Page: 88
----------------------------------------------------------------------------------------------------
quacy of our Global Insurance Programme and recommended the annual renewal proposal for Board approval in March 2025, including consideration of cyber insurance coverage AI and Cryptocurrency  Received reporting on AI opportunities and risks, including efficiency gains in customer servicing and manual processes, while monitoring management’s measured approach to implementation with proportionate risk controls  Reviewed cryptocur
====================================================================================================
Company: IG Group Holdings plc
Keyword: artificial intelligence
Page: 17
----------------------------------------------------------------------------------------------------
st in prioritise investment in larger and fast- and enabling cryptocurrency deposits automation and artificial intelligence across growing markets. and withdrawals for seven digital assets. the business to enhance scalability.
====================================================================================================
Company: IG Group Holdings plc
Keyword: artificial intelligence
Page: 43
----------------------------------------------------------------------------------------------------
dditional oversight with membership of our RMF and sets the tone for conduct comprised of senior management Vendor Risk Management Committee Transaction Reporting Committee Artificial Intelligence Committee in all business activities and expected with subject matter expertise.
====================================================================================================
Company: IG Group Holdings plc
Keyword: artificial intelligence
Page: 57
----------------------------------------------------------------------------------------------------
Vendor Risk Transaction Reporting Artificial Intelligence Pricing Committee Technology Committee Management
====================================================================================================
Company: IG Group Holdings plc
Keyword: artificial intelligence
Page: 86
----------------------------------------------------------------------------------------------------
functions implications and opportunities presented by assessment process and outcomes for  Review the design and implementation of Artificial Intelligence, and we will continue to the Risk and Compliance functions. risk management policy and measurement The Terms of Reference of the Committee monitor management’s response to these
====================================================================================================
Company: IG Group Holdings plc
Keyword: automation
Page: 11
----------------------------------------------------------------------------------------------------
Taking ownership and increasing Increase digital servicing and accountability to enhance automation to lower fixed costs and outcomes enhance scalability. Make the right choices about where to invest and
====================================================================================================
Company: IG Group Holdings plc
Keyword: automation
Page: 12
----------------------------------------------------------------------------------------------------
 Lowering fixed costs to enhance scalability  Exiting initiatives delivering unacceptable Delivering on self-help via digital servicing and automation returns02.  Increasing conversion of customer fee and measures to unlock our potential
====================================================================================================
Company: IG Group Holdings plc
Keyword: automation
Page: 17
----------------------------------------------------------------------------------------------------
ontinue to invest in prioritise investment in larger and fast- and enabling cryptocurrency deposits automation and artificial intelligence across growing markets. and withdrawals for seven digital assets. the business to enhance scalabili
====================================================================================================
Company: IG Group Holdings plc
Keyword: bias
Page: 117
----------------------------------------------------------------------------------------------------
of the US (tastytrade) CGU involves a  Assessed whether judgements made in deriving the assumptions gave rise to indicators of possible management bias. significant degree of judgement and the estimation uncertainty is high. As part of our risk assessment procedures, we also assessed the Representations were obtained from management that assumptions used were their be
====================================================================================================
Company: IG Group Holdings plc
Keyword: fairness
Page: 23
----------------------------------------------------------------------------------------------------
ocess, with data trackedwith our business objectives, ensuring that culture where diverse talent of all throughout to ensure fairness, objectivityinclusion continues to be a lever for growth, backgrounds, identities and experiences and a meritocratic approach tohigh p

In [61]:
# Manual review for IG Group Holdings plc

company_id = "011"

mask = manual_review["company_id"].astype(str).str.zfill(3) == company_id

manual_review.loc[mask, "manual_adjusted_score"] = manual_review.loc[mask, "total_score"]
manual_review.loc[mask, "manual_adjusted_percentage"] = manual_review.loc[mask, "score_percentage"]

manual_review.loc[mask, "reason_for_adjustment"] = (
    "No adjustment made. IG Group shows relevant AI transparency evidence, including AI-powered employee "
    "support, automation and artificial intelligence across growing markets, AI controls for sensitive "
    "information, AI-related operational and customer service opportunities, risk management oversight, "
    "and Board attention to AI, cybersecurity and crypto-related risks. Some fairness and bias "
    "matches are less directly connected to AI governance, but the overall evidence supports retaining "
    "the provisional transparency score."
)

manual_review.loc[mask, "important_pages"] = "11, 12, 17, 20, 47, 48, 61, 72, 73, 86, 87, 88"

manual_review.loc[mask, "important_extracts"] = (
    "IG refers to investment in an agile, AI-powered employee metric. "
    "The report states that AI controls help ensure sensitive information is used appropriately. "
    "It discusses automation and artificial intelligence across growing markets, including digital servicing and customer support. "
    "Board and committee materials refer to AI, cybersecurity, crypto, risk appetite, and ongoing reporting on AI opportunities and risks."
)

manual_review.loc[mask, "review_status"] = "Reviewed - provisional score retained"

manual_review.to_csv(manual_review_file, index=False)

manual_review.loc[mask]

,company_id,company_name,total_ai_transparency_mentions,unique_keywords,unique_pages,total_score,score_percentage,manual_adjusted_score,manual_adjusted_percentage,reason_for_adjustment,important_pages,important_extracts,review_status
14,011,IG Group Holdings plc,22,5,16,6,42.86,6.0,42.86,"No adjustment made. IG Group shows relevant AI transparency evidence, including AI-powered employee support, automation and artificial intelligence across growing markets, AI controls for sensitive information, AI-related operational and customer service opportunities, risk management oversight, and Board attention to AI, cybersecurity and crypto-related risks. Some fairness and bias matches are less directly connected to AI governance, but the overall evidence supports retaining the provisional transparency score.","11, 12, 17, 20, 47, 48, 61, 72, 73, 86, 87, 88","IG refers to investment in an agile, AI-powered employee metric. The report states that AI controls help ensure sensitive information is used appropriately. It discusses automation and artificial intelligence across growing markets, including digital servicing and customer support. Board and committee materials refer to AI, cybersecurity, crypto, risk appetite, and ongoing reporting on AI opportunities and risks.",Reviewed - provisional score retained

In [62]:
# Moving to the next company for manual validation

review_status = manual_review["review_status"].fillna("").astype(str)

next_company = manual_review[
    ~review_status.str.contains("Reviewed", case=False, na=False)
].head(1)

next_company

,company_id,company_name,total_ai_transparency_mentions,unique_keywords,unique_pages,total_score,score_percentage,manual_adjusted_score,manual_adjusted_percentage,reason_for_adjustment,important_pages,important_extracts,review_status
15,010,AJ Bell plc,21,6,14,6,42.86,NaN,NaN,NaN,NaN,NaN,Pending manual review

In [66]:
# Reviewing AI transparency evidence for AJ Bell plc

company_id = "010"

keywords = [
    "artificial intelligence",
    "AI",
    "machine learning",
    "generative AI",
    "GenAI",
    "large language model",
    "LLM",
    "algorithm",
    "automation",
    "automated decision-making",
    "responsible AI",
    "AI ethics",
    "ethical AI",
    "human oversight",
    "human review",
    "human-in-the-loop",
    "bias",
    "fairness",
    "model risk",
    "data science",
    "analytics"
]

company_extracts = ai_mentions[
    ai_mentions["company_id"].astype(str).str.zfill(3) == company_id
].copy()

company_extracts = company_extracts[
    company_extracts["keyword"].astype(str).str.lower().isin(
        [keyword.lower() for keyword in keywords]
    )
]

company_extracts = company_extracts.sort_values(
    by=["page_number", "keyword"],
    ascending=[True, True]
)

print("Company: AJ Bell plc")
print("Company ID:", company_id)
print("Extracts found:", len(company_extracts))
print("=" * 100)

for _, row in company_extracts.iterrows():
    print(f"Company: {row['company_name']}")
    print(f"Keyword: {row['keyword']}")
    print(f"Page: {row['page_number']}")
    print("-" * 100)
    print(row["context"])
    print("=" * 100)

Company: AJ Bell plc
Company ID: 010
Extracts found: 21
====================================================================================================
Company: AJ Bell plc
Keyword: AI
Page: 7
----------------------------------------------------------------------------------------------------
service, allowing our customers to invest when they choose. Increasingly, we leverage generative AI (GenAI) to streamline back-office processes, enabling us to
====================================================================================================
Company: AJ Bell plc
Keyword: generative AI
Page: 7
----------------------------------------------------------------------------------------------------
service, allowing our customers to invest when they choose. Increasingly, we leverage generative AI (GenAI) to streamline back-office processes, enabling us to
====================================================================================================
Company: AJ Bell plc
Keyword: automation
Page: 12
----------------------------------------------------------------------------------------------------
in proposition, in June 2025 and are enhancing cash further growth in FY26 and beyond. the pension tax system throughout this Parliament, management and investment automation on our full- focusing on tax-free cash and tax relief. service advised platform. Link to strategy:
====================================================================================================
Company: AJ Bell plc
Keyword: automation
Page: 15
----------------------------------------------------------------------------------------------------
amework. propositions, with a focus on ease of use. This The unwelcome theme of unnecessary Michael Summersgill includes increasing automation in the adviser journey, allowing advisers to serve their clients Campaigning for better complexity and poorly constructed policy has Chief Executive Officer more efficiently, and launching a new
====================================================================================================
Company: AJ Bell plc
Keyword: automation
Page: 17
----------------------------------------------------------------------------------------------------
According to a recent survey 1 Work is also underway to bring greater automation to the What this means for our customers investment and divestment processes for advisers, delivering 65% and advisers
====================================================================================================
Company: AJ Bell plc
Keyword: AI
Page: 19
----------------------------------------------------------------------------------------------------
across various teams in the business. This year, we including the integration of generative AI (GenAI) across key Our philosophy has always been to share the processes and the deployment of robotics within back-office developed a ‘single customer view’ dashboard for our
====================================================================================================
Company: AJ Bell plc
Keyword: AI
Page: 19
----------------------------------------------------------------------------------------------------
within back-office developed a ‘single customer view’ dashboard for our Customer Service Team using AI to monitor all customer benefits of operating at increasing scale with operations. We have streamlined workflows, reduced manual interactions and drive efficiencies and better customer
====================================================================================================
Company: AJ Bell plc
Keyword: automation
Page: 19
----------------------------------------------------------------------------------------------------
Several projects are underway to drive further operational 0.15 bps efficiencies across the business through the automation of (FY24: 0.16 bps) back-office processes. Our philosophy remains to share the
====================================================================================================
Company: AJ Bell plc
Keyword: generative AI
Page: 19
----------------------------------------------------------------------------------------------------
across various teams in the business. This year, we including the integration of generative AI (GenAI) across key Our philosophy has always been to share the processes and the deployment of robotics within back-office developed a ‘single customer view’ dashboard for our
====================================================================================================
Company: AJ Bell plc
Keyword: automation
Page: 24
----------------------------------------------------------------------------------------------------
elerated platform enhancements, including of FX dealing activity experienced in the year. As part of the wind down of our non-platform business, the launch of AJ Bell Touch in the year, as well as implementing further automation in our advised revenues of £12.7 million recognised in FY25 will not recur in FY26. propositions. Although these initiatives have elevated short-term costs, they form part of our stra
====================================================================================================
Company: AJ Bell plc
Keyword: automation
Page: 35
----------------------------------------------------------------------------------------------------
We will continue to enhance AJ Bell Touch with Strategy Accessible solutions – We believe investing further functionality, automation and integratedResponsible is for everyone. Our low-cost, easy-to-use advice tools, supporting our ambition to make
====================================================================================================
Company: AJ Bell plc
Keyword: fairness
Page: 39
----------------------------------------------------------------------------------------------------
to our success, and as Why it is important Place to Work® survey were fairness, inclusion a responsible employer, we are Our success is built on delivering a Principled and safety in the workplace, reflecting the
====================================================================================================
Company: AJ Bell plc
Keyword: artificial intelligence
Page: 41
----------------------------------------------------------------------------------------------------
y of leadership and open communication to AJ Bell’s People Strategy. Our framework artificial intelligence (GenAI) to enhance development journey.remain central to our culture. We deliver a range is a set of activities and processes designed
====================================================================================================
Company: AJ Bell plc
Keyword: bias
Page: 43
----------------------------------------------------------------------------------------------------
ble representation. creating psychological safety, understanding AJ Bell’s dedication to diversity, equity and cognitive bias and leading inclusively. Feedback Total number of employees 20251 inclusion is embedded in our policies, ensu
====================================================================================================
Company: AJ Bell plc
Keyword: automation
Page: 95
----------------------------------------------------------------------------------------------------
deliver good and disaster recovery capabilities, and continues the implementation of a new Governance and Risk (ICARA) at Committee meetings and customer outcomes, was reviewed by the to invest in automation, where appropriate. Risk & Control platform; members of the Committee and other Board Committee before being approved by the Board. In addition to the bi-annual operational • ensuring that r
====================================================================================================
Company: AJ Bell plc
Keyword: fairness
Page: 104
----------------------------------------------------------------------------------------------------
The targets are set by reference to strategic objectives. • participation in or responsibility for conduct resulting in significant loss to a Group company; • failure to meet appropriate standards of fairness and propriety including fraud, material Deferred awards are subject to specific conditions that are designed to protect shareholder value dishonesty or material wrongdoing;
====================================================================================================
Company: AJ Bell plc
Keyword: automation
Page: 109
----------------------------------------------------------------------------------------------------
udited) the business, driving continued operational gearing through a focus on increased As set out in last year’s Directors Remuneration Report, Roger Stott retired and stepped down as automation, strategic workforce planning and contract renegotiations. These an Executive Director on 31 December 2024. As disclosed in the total single figure of remuneration, initiatives have delivered
====================================================================================================
Company: AJ Bell plc
Keyword: AI
Page: 164
----------------------------------------------------------------------------------------------------
162 Glossary AGM Annual General Meeting ExCo Executive Committee NED Non-Executive Director AI Artificial Intelligence FCA Financial Conduct Authority NGFS Network for Greening the Financial System AJBI AJ Bell Investments
====================================================================================================
Company: AJ Bell plc
Keyword: AI
Page: 164
----------------------------------------------------------------------------------------------------
t FX Foreign Exchange PCAF Partnership for Carbon Accounting Financials BAYE Buy As You Earn GenAI Generative AI PLC Public Limited Company BPS Basis points GHG Greenhouse Gas PR&U Principal Risks and Uncertaintie
====================================================================================================
Company: AJ Bell plc
Keyword: artificial intelligence
Page: 164
----------------------------------------------------------------------------------------------------
162 Glossary AGM Annual General Meeting ExCo Executive Committee NED Non-Executive Director AI Artificial Intelligence FCA Financial Conduct Authority NGFS Network for Greening the Financial System AJBI AJ Bell Investments FRC Financ
====================================================================================================
Company: AJ Bell plc
Keyword: generative AI
Page: 164
----------------------------------------------------------------------------------------------------
r Management FX Foreign Exchange PCAF Partnership for Carbon Accounting Financials BAYE Buy As You Earn GenAI Generative AI PLC Public Limited Company BPS Basis points GHG Greenhouse Gas PR&U Principal Risks and Uncertaintie
====================================================================================================

In [64]:
# Manual review for AJ Bell plc

company_id = "010"

mask = manual_review["company_id"].astype(str).str.zfill(3) == company_id

manual_review.loc[mask, "manual_adjusted_score"] = manual_review.loc[
    mask, "total_score"
]

manual_review.loc[mask, "manual_adjusted_percentage"] = manual_review.loc[
    mask, "score_percentage"
]

manual_review.loc[mask, "reason_for_adjustment"] = (
    "No adjustment made. AJ Bell provides moderate and relevant AI transparency "
    "evidence, The report also indicates review of investment in automation. However, the disclosures provide limited "
    "detail on AI-specific governance. Several fairness and bias matches relate to employment, "
    "remuneration and workplace inclusion rather than AI, while the page 164 "
    "matches are glossary references. The overall evidence therefore supports "
    "retaining the provisional transparency score."
)

manual_review.loc[mask, "important_pages"] = "7, 19, 41, 95"

manual_review.loc[mask, "important_extracts"] = (
    "The report describes the integration of GenAI across key business processes, "
    "robotics in back-office operations and an AI-supported single-customer-view "
    "dashboard used by the Customer Service Team. "
    "Committee materials indicate that investment in automation was reviewed as "
    "part of governance and risk discussions."
)

manual_review.loc[mask, "review_status"] = (
    "Reviewed - provisional score retained"
)

manual_review.to_csv(manual_review_file, index=False)

manual_review.loc[mask]

,company_id,company_name,total_ai_transparency_mentions,unique_keywords,unique_pages,total_score,score_percentage,manual_adjusted_score,manual_adjusted_percentage,reason_for_adjustment,important_pages,important_extracts,review_status
15,010,AJ Bell plc,21,6,14,6,42.86,6.0,42.86,"No adjustment made. AJ Bell provides moderate and relevant AI transparency evidence, The report also indicates review of investment in automation. However, the disclosures provide limited detail on AI-specific governance. Several fairness and bias matches relate to employment, remuneration and workplace inclusion rather than AI, while the page 164 matches are glossary references. The overall evidence therefore supports retaining the provisional transparency score.","7, 19, 41, 95","The report describes the integration of GenAI across key business processes, robotics in back-office operations and an AI-supported single-customer-view dashboard used by the Customer Service Team. Committee materials indicate that investment in automation was reviewed as part of governance and risk discussions.",Reviewed - provisional score retained

In [65]:
# Moving to the next company for manual validation

review_status = manual_review["review_status"].fillna("").astype(str)

next_company = manual_review[
    ~review_status.str.contains("Reviewed", case=False, na=False)
].head(1)

next_company

,company_id,company_name,total_ai_transparency_mentions,unique_keywords,unique_pages,total_score,score_percentage,manual_adjusted_score,manual_adjusted_percentage,reason_for_adjustment,important_pages,important_extracts,review_status
16,017,Boku Inc.,23,3,10,5,35.71,NaN,NaN,NaN,NaN,NaN,Pending manual review

In [67]:
# Reviewing AI transparency evidence for Boku Inc.

company_id = "017"

company_extracts = ai_mentions[
    ai_mentions["company_id"].astype(str).str.zfill(3) == company_id
].copy()

company_extracts = company_extracts.sort_values(
    by=["keyword", "page_number"],
    ascending=[True, True]
)

print("Company: Boku Inc.")
print("Company ID:", company_id)
print("Extracts found:", len(company_extracts))
print("=" * 90)

for _, row in company_extracts.iterrows():
    print(f"Company: {row['company_name']}")
    print(f"Keyword: {row['keyword']}")
    print(f"Page: {row['page_number']}")
    print("-" * 90)
    print(row["context"])
    print("=" * 90)

Company: Boku Inc.
Company ID: 017
Extracts found: 23
==========================================================================================
Company: Boku Inc.
Keyword: AI
Page: 4
------------------------------------------------------------------------------------------
utomation and scalability through +30% vs 2024 (+29% CER) operational infrastructure enhancements Growing EBITDA $41.3m +36% vs 2024 Invested in key capabilities including data, AI, product and transformation to drive scalability Operating proﬁt $18.9M +205% vs 2024 Launched Singapore Innovation Hub B
==========================================================================================
Company: Boku Inc.
Keyword: AI
Page: 10
------------------------------------------------------------------------------------------
clear priority. • Innovate: Innovation remains central to our culture and a core differentiator for Boku. During the year, we advanced our platform beyond core payment processing, investing in automation, AI and data-driven capabilities to enhance transaction conversion rates, settlement speed and scalability for our merchants, while reducing friction across the payment journey. In November 2025, we
==========================================================================================
Company: Boku Inc.
Keyword: AI
Page: 10
------------------------------------------------------------------------------------------
our business and a part of the world that is seeing rapid developments in payments innovation. The Hub brings together a dedicated team working on FX solutions, payouts and emerging technologies, including AI and digital assets (stablecoin), enabling the development of payment infrastructure that reduces complexity for our merchants while expanding their global reach. Boku, Inc. Annual Report and Accounts for the
==========================================================================================
Company: Boku Inc.
Keyword: AI
Page: 12
------------------------------------------------------------------------------------------
at the same rate. • Build the platform of the future: We are committed to evolving Boku’s platform to remain at the forefront of global payments. This includes the intentional and responsible incorporation of AI tools, including agentic AI, across the business, spanning areas such as fraud and risk management, customer support, operational automation, data analysis and product development. AI will be an enabler of bette
==========================================================================================
Company: Boku Inc.
Keyword: AI
Page: 12
------------------------------------------------------------------------------------------
the platform of the future: We are committed to evolving Boku’s platform to remain at the forefront of global payments. This includes the intentional and responsible incorporation of AI tools, including agentic AI, across the business, spanning areas such as fraud and risk management, customer support, operational automation, data analysis and product development. AI will be an enabler of better decision making, faster ex
==========================================================================================
Company: Boku Inc.
Keyword: AI
Page: 12
------------------------------------------------------------------------------------------
esponsible incorporation of AI tools, including agentic AI, across the business, spanning areas such as fraud and risk management, customer support, operational automation, data analysis and product development. AI will be an enabler of better decision making, faster execution and improved outcomes for both merchants and consumers. Building on the establishment of our Innovation Hub in Singapore in 2025, we will continue to
==========================================================================================
Company: Boku Inc.
Keyword: AI
Page: 19
------------------------------------------------------------------------------------------
ategic growth & investment: The Group competitive environment invests in innovative products, new markets, and emerging technologies including AI, to support The Group operates in a fast-evolving competitiveness and adaptability, alongside the ongoing evaluation of new business models, payments i
==========================================================================================
Company: Boku Inc.
Keyword: AI
Page: 19
------------------------------------------------------------------------------------------
supports growth in both new and competitive landscape. Changes in market existing markets. dynamics, including the emergence of new payment technologies, AI-enabled • Product and service expansion and solutions, evolving user behaviour, optimisation: The Group tests and develops new regulatory shifts, and pricing pressures,
==========================================================================================
Company: Boku Inc.
Keyword: AI
Page: 19
------------------------------------------------------------------------------------------
. Ongoing training, certifications, and development programmes, including the use of modern digital platforms and AI tools, support continuous learning and awareness of emerging technologies and industry trends.
==========================================================================================
Company: Boku Inc.
Keyword: AI
Page: 20
------------------------------------------------------------------------------------------
maintained and continues to production systems, particularly those evolve to accommodate anticipated growth and underpinning transaction processing and expansion. This may include scalable, AI-enabled settlement, is essential to maintaining technologies where appropriate to support service reliability. automation and operational resilience. Failure to sc
==========================================================================================
Company: Boku Inc.
Keyword: AI
Page: 21
------------------------------------------------------------------------------------------
policies and procedures aligned to applicable The evolving regulatory landscape, obligations. A strengthened compliance monitoring including emerging regulation related to AI, and testing programme enhances early identification may impact operational processes and of non-compliance risks and timely remediation. service delivery. Failure to comply with applic
==========================================================================================
Company: Boku Inc.
Keyword: AI
Page: 23
------------------------------------------------------------------------------------------
systems, including threat detection, endpoint affect the Group’s financial position, protection, network security, and AI-enabled reputation, and long-term competitiveness. analytics and automated response capabilities. Risk level: High
==========================================================================================
Company: Boku Inc.
Keyword: automation
Page: 4
------------------------------------------------------------------------------------------
cies ISO 27001 certiﬁed Profitable growth driven by scale, diversification and financial strength Excellent ﬁnancial results Platform innovation Broad based revenue growth $128.8M Improved automation and scalability through +30% vs 2024 (+29% CER) operational infrastructure enhancements Growing EBITDA $41.3m +36% vs 2024 Invested in key capabilities including data, AI,
==========================================================================================
Company: Boku Inc.
Keyword: automation
Page: 10
------------------------------------------------------------------------------------------
ins a clear priority. • Innovate: Innovation remains central to our culture and a core differentiator for Boku. During the year, we advanced our platform beyond core payment processing, investing in automation, AI and data-driven capabilities to enhance transaction conversion rates, settlement speed and scalability for our merchants, while reducing friction across the payment journey. In November 2025,
==========================================================================================
Company: Boku Inc.
Keyword: automation
Page: 12
------------------------------------------------------------------------------------------
lobally. • Drive scalability: As volumes and complexity increase, scalable operations are critical. Building on our programme to modernise payment operations and settlement systems, we will continue to invest in automation, straight-through processing, treasury and finance infrastructure together with global compliance capabilities. These initiatives will support automated reconciliation and near real-time fund flows across our int
==========================================================================================
Company: Boku Inc.
Keyword: automation
Page: 12
------------------------------------------------------------------------------------------
lobal payments. This includes the intentional and responsible incorporation of AI tools, including agentic AI, across the business, spanning areas such as fraud and risk management, customer support, operational automation, data analysis and product development. AI will be an enabler of better decision making, faster execution and improved outcomes for both merchants and consumers. Building on the establishment of our Innovation Hu
==========================================================================================
Company: Boku Inc.
Keyword: automation
Page: 20
------------------------------------------------------------------------------------------
nd expansion. This may include scalable, AI-enabled settlement, is essential to maintaining technologies where appropriate to support service reliability. automation and operational resilience. Failure to scale effectively could result in • Capability and expertise enhancement: The processing disruptions, settlement delays, Group seeks to strengthen operatio
==========================================================================================
Company: Boku Inc.
Keyword: automation
Page: 20
------------------------------------------------------------------------------------------
on of best practices and continuous improvement across teams. Risk movement: Unchanged • Back-office transformation and automation: Continued investment is being made in operations, finance, treasury, and human resources systems
==========================================================================================
Company: Boku Inc.
Keyword: automation
Page: 20
------------------------------------------------------------------------------------------
ued investment is being made in operations, finance, treasury, and human resources systems to enhance automation, strengthen controls, improve efficiency, and support scalability. Transformation initiatives including straight
==========================================================================================
Company: Boku Inc.
Keyword: automation
Page: 21
------------------------------------------------------------------------------------------
Regulatory and legal readiness assessments are conducted prior to launching new services, supported by continued automation of key compliance processes to enhance control and reduce manual risk. Boku, Inc. Annual Report and Accounts for
==========================================================================================
Company: Boku Inc.
Keyword: automation
Page: 42
------------------------------------------------------------------------------------------
control and risk assurance framework Last year Boku commenced a review and strengthening of its internal control and risk assurance framework to ensure it remains fit for purpose. The Finance team continues to focus on automation and enhancement of our internal financial controls framework, related processes and underlying systems. During the year, this included two successful upgrades of our general ledger to strengthen financial reporting and
==========================================================================================
Company: Boku Inc.
Keyword: fairness
Page: 48
------------------------------------------------------------------------------------------
Committee applies this approach to the Executive Directors and Global Leadership Team, ensuring they are incentivised to deliver value for shareholders while maintaining a strong focus on risk management, affordability, fairness in relation to the wider workforce, and alignment with AIM Rules and principles. Executive Directors Executive Director remuneration consists of 5 elements: • Salary • Annual Bonus • Long Term Incent
==========================================================================================
Company: Boku Inc.
Keyword: fairness
Page: 56
------------------------------------------------------------------------------------------
ving senior leaders. Progress was also made in strengthening reward and pay governance through the development of a clear Reward Philosophy and job-levelling framework, designed to promote consistency, transparency and fairness in pay and career progression. The Group is committed to providing equal opportunities and promoting inclusive behaviours, which are viewed as important enablers of innovation, effective decision-making and long-term p
==========================================================================================

In [68]:
# Manual review for Boku Inc.

company_id = "017"

mask = manual_review["company_id"].astype(str).str.zfill(3) == company_id

manual_review.loc[mask, "manual_adjusted_score"] = 7.0
manual_review.loc[mask, "manual_adjusted_percentage"] = 50.00

manual_review.loc[mask, "reason_for_adjustment"] = (
    "Score adjusted upward from 5 to 7. Boku provides meaningful AI transparency evidence, "
    "including the intentional and responsible incorporation of AI tools. The report also refers to "
    "AI-related regulatory developments, compliance monitoring and operational resilience. "
    "However, disclosure remains limited regarding human oversight, model testing, explainability, "
    "bias controls, performance monitoring and formal accountability. Fairness references relate "
    "mainly to remuneration and workforce matters."
)

manual_review.loc[mask, "important_pages"] = "4, 10, 12, 19, 20, 21, 23"

manual_review.loc[mask, "important_extracts"] = (
    "Boku reports investment in data, AI and transformation capabilities to improve scalability. "
    "It describes the intentional and responsible incorporation of AI tools, including agentic AI, "
    "across fraud and risk management, customer support, operational automation, data analysis and "
    "product development. AI is presented as an enabler of better decision-making, faster execution "
    "and improved outcomes. Further extracts refer to AI-enabled settlement, operational resilience, "
    "emerging AI regulation and strengthened compliance monitoring."
)

manual_review.loc[mask, "review_status"] = "Reviewed - score manually adjusted"

manual_review.to_csv(manual_review_file, index=False)

manual_review.loc[mask]

,company_id,company_name,total_ai_transparency_mentions,unique_keywords,unique_pages,total_score,score_percentage,manual_adjusted_score,manual_adjusted_percentage,reason_for_adjustment,important_pages,important_extracts,review_status
16,017,Boku Inc.,23,3,10,5,35.71,7.0,50.0,"Score adjusted upward from 5 to 7. Boku provides meaningful AI transparency evidence, including the intentional and responsible incorporation of AI tools. The report also refers to AI-related regulatory developments, compliance monitoring and operational resilience. However, disclosure remains limited regarding human oversight, model testing, explainability, bias controls, performance monitoring and formal accountability. Fairness references relate mainly to remuneration and workforce matters.","4, 10, 12, 19, 20, 21, 23","Boku reports investment in data, AI and transformation capabilities to improve scalability. It describes the intentional and responsible incorporation of AI tools, including agentic AI, across fraud and risk management, customer support, operational automation, data analysis and product development. AI is presented as an enabler of better decision-making, faster execution and improved outcomes. Further extracts refer to AI-enabled settlement, operational resilience, emerging AI regulation and strengthened compliance monitoring.",Reviewed - score manually adjusted

In [69]:
# Moving to the next company for manual validation

review_status = manual_review["review_status"].fillna("").astype(str)

next_company = manual_review[
    ~review_status.str.contains("Reviewed", case=False, na=False)
].head(1)

next_company

,company_id,company_name,total_ai_transparency_mentions,unique_keywords,unique_pages,total_score,score_percentage,manual_adjusted_score,manual_adjusted_percentage,reason_for_adjustment,important_pages,important_extracts,review_status
17,013,IntegraFin Holdings plc,11,3,3,3,21.43,NaN,NaN,NaN,NaN,NaN,Pending manual review

In [70]:
# Reviewing AI transparency evidence for IntegraFin Holdings plc

company_id = "013"

company_extracts = ai_mentions[
    ai_mentions["company_id"].astype(str).str.zfill(3) == company_id
].copy()

company_extracts = company_extracts.sort_values(
    by=["page_number", "keyword"],
    ascending=[True, True]
)

print("Company:", company_extracts["company_name"].iloc[0])
print("Company ID:", company_id)
print("Extracts found:", len(company_extracts))
print("=" * 90)

for _, row in company_extracts.iterrows():
    print(f"Company: {row['company_name']}")
    print(f"Keyword: {row['keyword']}")
    print(f"Page: {row['page_number']}")
    print("-" * 90)
    print(row["context"])
    print("=" * 90)

Company: IntegraFin Holdings plc
Company ID: 013
Extracts found: 11
==========================================================================================
Company: IntegraFin Holdings plc
Keyword: AI
Page: 10
------------------------------------------------------------------------------------------
heir the adviser platform market to grow at 12% propositions and our overall IHP integrations data and unique access to AI capabilities. per annum from £806 billion at the end of strategy are aligned to these trends.
==========================================================================================
Company: IntegraFin Holdings plc
Keyword: AI
Page: 53
------------------------------------------------------------------------------------------
umer behaviour and confidence as well as increasing Time horizon: ongoing the risk of civil unrest and cyber attacks, particularly state sponsored or politically motivated cyber attacks. Artificial intelligence AI is a constantly evolving opportunity and risk for the Group. Key areas of activity have included business Time horizon: ongoing proposition and competitive advantage, day-to-day operations, workforce education, cyber
==========================================================================================
Company: IntegraFin Holdings plc
Keyword: AI
Page: 53
------------------------------------------------------------------------------------------
orce education, cyber security, workforce impact, data protection and IP risk as well as many ethical and social implications. In order to harness the benefits of AI whilst effectively managing the associated risks it presents to the Group and society: l our people must be AI informed; AI awareness training is a core part of AI adoption alongside active
==========================================================================================
Company: IntegraFin Holdings plc
Keyword: AI
Page: 53
------------------------------------------------------------------------------------------
ocial implications. In order to harness the benefits of AI whilst effectively managing the associated risks it presents to the Group and society: l our people must be AI informed; AI awareness training is a core part of AI adoption alongside active monitoring of AI societal, ethical or industry impacts; l adoption happens within a go
==========================================================================================
Company: IntegraFin Holdings plc
Keyword: AI
Page: 53
------------------------------------------------------------------------------------------
tions. In order to harness the benefits of AI whilst effectively managing the associated risks it presents to the Group and society: l our people must be AI informed; AI awareness training is a core part of AI adoption alongside active monitoring of AI societal, ethical or industry impacts; l adoption happens within a governance fram
==========================================================================================
Company: IntegraFin Holdings plc
Keyword: AI
Page: 53
------------------------------------------------------------------------------------------
benefits of AI whilst effectively managing the associated risks it presents to the Group and society: l our people must be AI informed; AI awareness training is a core part of AI adoption alongside active monitoring of AI societal, ethical or industry impacts; l adoption happens within a governance framework; l the use
==========================================================================================
Company: IntegraFin Holdings plc
Keyword: AI
Page: 53
------------------------------------------------------------------------------------------
ated risks it presents to the Group and society: l our people must be AI informed; AI awareness training is a core part of AI adoption alongside active monitoring of AI societal, ethical or industry impacts; l adoption happens within a governance framework; l the use of AI is continuously monitored; and l data gove
==========================================================================================
Company: IntegraFin Holdings plc
Keyword: AI
Page: 53
------------------------------------------------------------------------------------------
ption alongside active monitoring of AI societal, ethical or industry impacts; l adoption happens within a governance framework; l the use of AI is continuously monitored; and l data governance is a critical practice that supports positive AI outcomes. Blockchain, The prevalence of blockchain, tokenisation and digital asset a
==========================================================================================
Company: IntegraFin Holdings plc
Keyword: AI
Page: 53
------------------------------------------------------------------------------------------
l adoption happens within a governance framework; l the use of AI is continuously monitored; and l data governance is a critical practice that supports positive AI outcomes. Blockchain, The prevalence of blockchain, tokenisation and digital asset adoption in the financial services industry is gaining tokenisation, and momentum, and beginning to gain traction wit
==========================================================================================
Company: IntegraFin Holdings plc
Keyword: artificial intelligence
Page: 53
------------------------------------------------------------------------------------------
economic environment and consumer behaviour and confidence as well as increasing Time horizon: ongoing the risk of civil unrest and cyber attacks, particularly state sponsored or politically motivated cyber attacks. Artificial intelligence AI is a constantly evolving opportunity and risk for the Group. Key areas of activity have included business Time horizon: ongoing proposition and competitive advantage, day-to-day operations, workforce educatio
==========================================================================================
Company: IntegraFin Holdings plc
Keyword: automation
Page: 72
------------------------------------------------------------------------------------------
t out in last year’s Directors’ is appropriate to retain and reward 30 September and continuing delivery against Remuneration Report and can be found in employees, and remains competitive our automation and integration strategy. the Investor Relations section of our website. and appropriate For the financial
==========================================================================================

In [71]:
# Manual review for IntegraFin Holdings plc

company_id = "013"

mask = manual_review["company_id"].astype(str).str.zfill(3) == company_id

manual_review.loc[mask, "manual_adjusted_score"] = 5.0
manual_review.loc[mask, "manual_adjusted_percentage"] = round(
    (5 / 14) * 100,
    2
)

manual_review.loc[mask, "reason_for_adjustment"] = (
    "Manual upward adjustment made. IntegraFin's provisional score understates the "
    "substantive AI transparency evidence contained mainly on page 53. The report states "
    "that AI adoption occurs within a governance framework, AI use is continuously "
    "monitored, AI-awareness training is provided, and societal, ethical and industry "
    "impacts are actively monitored. It also identifies data governance as an important "
    "support for positive AI outcomes. Most extracts are overlapping passages "
    "from the same page, and the report does not clearly disclose human review, "
    "explainability, model testing, bias controls or formal AI audit arrangements. "
    "The score is therefore increased conservatively from 3 to 5."
)

manual_review.loc[mask, "important_pages"] = "10, 53"

manual_review.loc[mask, "important_extracts"] = (
    "IntegraFin identifies AI as an evolving opportunity and risk affecting business "
    "operations, competitive advantage, workforce education, cybersecurity, data "
    "protection and ethical or social considerations. "
    "The report states that employees should be AI-informed and that AI-awareness "
    "training forms a core part of adoption. "
    "AI adoption is described as occurring within a governance framework, supported by "
    "continuous monitoring of AI use, active monitoring of societal and ethical impacts, "
    "and data-governance practices."
)

manual_review.loc[mask, "review_status"] = (
    "Reviewed - manual score increased from 3 to 5"
)

manual_review.to_csv(
    manual_review_file,
    index=False
)

manual_review.loc[mask]

,company_id,company_name,total_ai_transparency_mentions,unique_keywords,unique_pages,total_score,score_percentage,manual_adjusted_score,manual_adjusted_percentage,reason_for_adjustment,important_pages,important_extracts,review_status
17,013,IntegraFin Holdings plc,11,3,3,3,21.43,5.0,35.71,"Manual upward adjustment made. IntegraFin's provisional score understates the substantive AI transparency evidence contained mainly on page 53. The report states that AI adoption occurs within a governance framework, AI use is continuously monitored, AI-awareness training is provided, and societal, ethical and industry impacts are actively monitored. It also identifies data governance as an important support for positive AI outcomes. Most extracts are overlapping passages from the same page, and the report does not clearly disclose human review, explainability, model testing, bias controls or formal AI audit arrangements. The score is therefore increased conservatively from 3 to 5.","10, 53","IntegraFin identifies AI as an evolving opportunity and risk affecting business operations, competitive advantage, workforce education, cybersecurity, data protection and ethical or social considerations. The report states that employees should be AI-informed and that AI-awareness training forms a core part of adoption. AI adoption is described as occurring within a governance framework, supported by continuous monitoring of AI use, active monitoring of societal and ethical impacts, and data-governance practices.",Reviewed - manual score increased from 3 to 5

In [72]:
# Moving to the next company for manual validation

review_status = manual_review["review_status"].fillna("").astype(str)

next_company = manual_review[
    ~review_status.str.contains("Reviewed", case=False, na=False)
].head(1)

next_company

,company_id,company_name,total_ai_transparency_mentions,unique_keywords,unique_pages,total_score,score_percentage,manual_adjusted_score,manual_adjusted_percentage,reason_for_adjustment,important_pages,important_extracts,review_status
18,018,PayPoint plc,13,3,9,2,14.29,NaN,NaN,NaN,NaN,NaN,Pending manual review

In [73]:
# Reviewing AI transparency evidence for PayPoint plc

company_id = "018"
company_name = "PayPoint plc"

paypoint_extracts = ai_mentions[
    ai_mentions["company_id"].astype(str).str.zfill(3) == company_id
].copy()

paypoint_extracts = paypoint_extracts.sort_values(
    by=["page_number", "keyword"],
    ascending=[True, True]
)

print(f"Company: {company_name}")
print(f"Company ID: {company_id}")
print(f"Extracts found: {len(paypoint_extracts)}")

for _, row in paypoint_extracts.iterrows():
    print("=" * 100)
    print(f"Company: {row['company_name']}")
    print(f"Keyword: {row['keyword']}")
    print(f"Page: {row['page_number']}")
    print("-" * 100)
    print(row["context"])

Company: PayPoint plc
Company ID: 018
Extracts found: 13
====================================================================================================
Company: PayPoint plc
Keyword: automation
Page: 5
----------------------------------------------------------------------------------------------------
organisational a reduction of at least in the range of 5% to framework which 20% of our issued share 8% per annum across will deliver greater capital, with scope for the Group automation of processes leverage in the range and greater agility to of 1.2x to 1.5x support the delivery of our plan Our strategy over the past five ye
====================================================================================================
Company: PayPoint plc
Keyword: automation
Page: 5
----------------------------------------------------------------------------------------------------
in the range of 1.2x to 1.5x. growth rate in the range of 5-8% per annum. operational structure and business processes today and develop a plan to deliver greater automation and business agility in the future to support the delivery of our plan.
====================================================================================================
Company: PayPoint plc
Keyword: automation
Page: 9
----------------------------------------------------------------------------------------------------
to Love2shop vouchers/rewards and prepaid solutions. 8% per annum across the Group; • Establishing an organisational framework which will deliver greater automation of processes and greater agility to support the delivery of our plan; and • Delivering a reduction of at least 20% of our issued share capital through an enhanced share buyback programme. Unpara
====================================================================================================
Company: PayPoint plc
Keyword: automation
Page: 9
----------------------------------------------------------------------------------------------------
ough an enhanced share buyback programme. Unparalleled retailer & SME Organisational framework Enhanced rewards for networks delivering vital to deliver greater automation shareholders with increased and community services and agility extended share buyback programme Our expanded proposition helps our SMEs and retailer
====================================================================================================
Company: PayPoint plc
Keyword: automation
Page: 9
----------------------------------------------------------------------------------------------------
operational structure and business processes today Programme based on business performance, market and develop a plan to deliver greater automation and conditions, cash generation and the overall capital needs business agility in the future to support the delivery of the business.
====================================================================================================
Company: PayPoint plc
Keyword: automation
Page: 13
----------------------------------------------------------------------------------------------------
of FY28, reflecting our confidence in the growth the Group automation of leverage in the range prospects of the business and our processes and of 1.2x to 1.5x continued commitment to
====================================================================================================
Company: PayPoint plc
Keyword: automation
Page: 13
----------------------------------------------------------------------------------------------------
5-8% per annum. business processes today and develop a plan to deliver greater automation and business agility in the future to support
====================================================================================================
Company: PayPoint plc
Keyword: AI
Page: 14
----------------------------------------------------------------------------------------------------
with the launch of a new consumers and our carrier partners. We have also demonstrable performance optimisation and AI-driven statement reader to further speed expanded our Zebra printer technology to over services adoption. In addition, we continue to drive
====================================================================================================
Company: PayPoint plc
Keyword: automation
Page: 17
----------------------------------------------------------------------------------------------------
e end Nick Wiles of FY28: achieving net revenue growth in the Chief Executive range of 5% to 8% per annum across the Group; 11 June 2025 establishing an organisational framework which will deliver greater automation of processes and
====================================================================================================
Company: PayPoint plc
Keyword: AI
Page: 49
----------------------------------------------------------------------------------------------------
cial distress. Retailer Rewards scheme, launched in September our core proposition, with the launch of a new services in the year. We continue to have a 2024, giving retailers additional commission for AI-driven statement reader to further speed strong community impact through our work with Our Community Cash Access and Banking Network scanning goods in store. Our next generation up and enhance the mer
====================================================================================================
Company: PayPoint plc
Keyword: AI
Page: 56
----------------------------------------------------------------------------------------------------
xperience enhanced in the year: new We provide card use a range of channels and methods to communicate Executive Board. AI-driven statement reader launched to payments services with and seek feedback from new and existing enhance th
====================================================================================================
Company: PayPoint plc
Keyword: AI
Page: 61
----------------------------------------------------------------------------------------------------
nological developments, including Risk is stable as Group acquisitions, investments and Trend = technology supporting the service provision. Pressures the evolution of AI, to understand how new technologies partnerships have helped to mitigate risks associated with to deliver new and innovative products remain with new can be used to support
====================================================================================================
Company: PayPoint plc
Keyword: bias
Page: 119
----------------------------------------------------------------------------------------------------
ement is materially consistent with the financial inappropriate journal entries to increase revenue and management bias in accounting estimates. The statements and our knowledge obtained during the audit: group engagement team shared this risk asse

In [74]:
# Manual review for PayPoint plc

company_id = "018"

mask = manual_review["company_id"].astype(str).str.zfill(3) == company_id

manual_review.loc[mask, "manual_adjusted_score"] = manual_review.loc[
    mask, "total_score"
]

manual_review.loc[mask, "manual_adjusted_percentage"] = manual_review.loc[
    mask, "score_percentage"
]

manual_review.loc[mask, "reason_for_adjustment"] = (
    "No adjustment made. PayPoint shows limited but relevant AI transparency evidence, "
    "including the operational use of an AI-driven statement reader and acknowledgement "
    "of risks associated with the evolution of AI. Most of the remaining extracts "
    "refer to general process automation and organisational efficiency rather than AI-specific "
    "governance. The report does not clearly disclose human oversight, explainability, model "
    "testing, AI fairness controls or formal accountability arrangements. The bias match relates "
    "to accounting estimates rather than algorithmic bias. The available evidence therefore "
    "supports retaining the provisional transparency score."
)

manual_review.loc[mask, "important_pages"] = "14, 49, 56, 61"

manual_review.loc[mask, "important_extracts"] = (
    "PayPoint reports the use of an AI-driven statement reader within its retailer and payments services. "
    "The statement reader is presented as an operational tool intended to improve service delivery and efficiency. "
    "The report also recognises risks associated with the evolution of AI and refers to monitoring technological "
    "developments and using partnerships to help mitigate these risks."
)

manual_review.loc[mask, "review_status"] = "Reviewed - provisional score retained"

manual_review.to_csv(manual_review_file, index=False)

manual_review.loc[mask]

,company_id,company_name,total_ai_transparency_mentions,unique_keywords,unique_pages,total_score,score_percentage,manual_adjusted_score,manual_adjusted_percentage,reason_for_adjustment,important_pages,important_extracts,review_status
18,018,PayPoint plc,13,3,9,2,14.29,2.0,14.29,"No adjustment made. PayPoint shows limited but relevant AI transparency evidence, including the operational use of an AI-driven statement reader and acknowledgement of risks associated with the evolution of AI. Most of the remaining extracts refer to general process automation and organisational efficiency rather than AI-specific governance. The report does not clearly disclose human oversight, explainability, model testing, AI fairness controls or formal accountability arrangements. The bias match relates to accounting estimates rather than algorithmic bias. The available evidence therefore supports retaining the provisional transparency score.","14, 49, 56, 61",PayPoint reports the use of an AI-driven statement reader within its retailer and payments services. The statement reader is presented as an operational tool intended to improve service delivery and efficiency. The report also recognises risks associated with the evolution of AI and refers to monitoring technological developments and using partnerships to help mitigate these risks.,Reviewed - provisional score retained

In [75]:
# Moving to the next company for manual validation

review_status = manual_review["review_status"].fillna("").astype(str)

next_company = manual_review[
    ~review_status.str.contains("Reviewed", case=False, na=False)
].head(1)

next_company

,company_id,company_name,total_ai_transparency_mentions,unique_keywords,unique_pages,total_score,score_percentage,manual_adjusted_score,manual_adjusted_percentage,reason_for_adjustment,important_pages,important_extracts,review_status
19,012,CMC Markets plc,4,4,4,1,7.14,NaN,NaN,NaN,NaN,NaN,Pending manual review

In [76]:
# Displaying all extracts for CMC Markets plc

company_id = "012"

company_extracts = ai_mentions[
    ai_mentions["company_id"].astype(str).str.zfill(3) == company_id
].copy()

company_name = (
    company_extracts["company_name"].iloc[0]
    if not company_extracts.empty
    else "CMC Markets plc"
)

print(f"Company: {company_name}")
print(f"Company ID: {company_id}")
print(f"Extracts found: {len(company_extracts)}")
print("=" * 100)

for _, row in company_extracts.iterrows():
    print(f"Company: {row['company_name']}")
    print(f"Keyword: {row['keyword']}")
    print(f"Page: {row['page_number']}")
    print("-" * 100)
    print(row["context"])
    print("=" * 100)

Company: CMC Markets plc
Company ID: 012
Extracts found: 4
====================================================================================================
Company: CMC Markets plc
Keyword: artificial intelligence
Page: 25
----------------------------------------------------------------------------------------------------
os. Operational risks | Risks arising from our people, processes, systems and external service providers Emerging risks We monitor emerging regulatory developments and technological advancements, including the rise of artificial intelligence and broader digital disruption. These trends have the potential to reshape how financial services are delivered and consumed. As part of our strategy, we aim to adapt our platforms, processes and product offerings to re
====================================================================================================
Company: CMC Markets plc
Keyword: AI
Page: 32
----------------------------------------------------------------------------------------------------
lity principles ypilla Our ESG strategy rs aligns with several United Ourthree sust ai nabilit Nations Sustainable Development Goals The Board oversees the conduct of our business, shaping
====================================================================================================
Company: CMC Markets plc
Keyword: automation
Page: 74
----------------------------------------------------------------------------------------------------
ve close to complete. aligning the value proposition. Lead the automation roll out of the robotics across 75% Project progresses to time with several business Expanding depth and breadth of product offering 75% Project has successfully delivered 3 of 4 defined agreed teams a
====================================================================================================
Company: CMC Markets plc
Keyword: bias
Page: 90
----------------------------------------------------------------------------------------------------
ing whether the judgements made in making accounting estimates are procedures relating to: indicative of a potential bias; and evaluating the business rationale of any significant transactions that are unusual or outside the
====================================================================================================

In [78]:
# Manual review for CMC Markets plc

company_id = "012"

mask = manual_review["company_id"].astype(str).str.zfill(3) == company_id

manual_review.loc[mask, "manual_adjusted_score"] = manual_review.loc[
    mask, "total_score"
]

manual_review.loc[mask, "manual_adjusted_percentage"] = manual_review.loc[
    mask, "score_percentage"
]

manual_review.loc[mask, "reason_for_adjustment"] = (
    "No adjustment made. CMC Markets provides limited AI transparency evidence. "
    "The report identifies artificial intelligence and wider digital disruption as emerging "
    "operational risks and indicates that the Group intends to adapt its platforms, processes "
    "and product offerings. It also reports an operational automation and robotics rollout. "
    "The disclosure remains general and does not provide detailed evidence of an AI "
    "The page 32 AI match appears to be an OCR or keyword false positive. The limited valid evidence therefore "
    "supports retaining the provisional transparency score."
)

manual_review.loc[mask, "important_pages"] = "25, 74"

manual_review.loc[mask, "important_extracts"] = (
    "Page 25 identifies artificial intelligence and broader digital disruption as emerging "
    "operational risks with the potential to reshape financial services. "
    "Page 74 refers to the rollout of automation and robotics across business operations. "
    "The remaining AI and bias matches are not directly relevant to substantive AI transparency."
)

manual_review.loc[mask, "review_status"] = (
    "Reviewed - provisional score retained"
)

manual_review.to_csv(manual_review_file, index=False)

manual_review.loc[mask]

,company_id,company_name,total_ai_transparency_mentions,unique_keywords,unique_pages,total_score,score_percentage,manual_adjusted_score,manual_adjusted_percentage,reason_for_adjustment,important_pages,important_extracts,review_status
19,012,CMC Markets plc,4,4,4,1,7.14,1.0,7.14,"No adjustment made. CMC Markets provides limited AI transparency evidence. The report identifies artificial intelligence and wider digital disruption as emerging operational risks and indicates that the Group intends to adapt its platforms, processes and product offerings. It also reports an operational automation and robotics rollout. The disclosure remains general and does not provide detailed evidence of an AI The page 32 AI match appears to be an OCR or keyword false positive. The limited valid evidence therefore supports retaining the provisional transparency score.","25, 74",Page 25 identifies artificial intelligence and broader digital disruption as emerging operational risks with the potential to reshape financial services. Page 74 refers to the rollout of automation and robotics across business operations. The remaining AI and bias matches are not directly relevant to substantive AI transparency.,Reviewed - provisional score retained

In [79]:
# Moving to the next company for manual validation

review_status = manual_review["review_status"].fillna("").astype(str)

next_company = manual_review[
    ~review_status.str.contains("Reviewed", case=False, na=False)
].head(1)

next_company

Empty DataFrame
Columns: [company_id, company_name, total_ai_transparency_mentions, unique_keywords, unique_pages, total_score, score_percentage, manual_adjusted_score, manual_adjusted_percentage, reason_for_adjustment, important_pages, important_extracts, review_status]
Index: []

In [80]:
# Final check: confirming that all companies have been manually reviewed

review_status = manual_review["review_status"].fillna("").astype(str)

pending_reviews = manual_review[
    ~review_status.str.contains("Reviewed", case=False, na=False)
]

reviewed_count = len(manual_review) - len(pending_reviews)
total_count = len(manual_review)

print(f"Companies reviewed: {reviewed_count} out of {total_count}")

if pending_reviews.empty:
    print("Manual validation complete — all companies have been reviewed.")
else:
    print("The following companies still require review:")
    display(
        pending_reviews[
            ["company_id", "company_name", "review_status"]
        ]
    )

Companies reviewed: 20 out of 20
Manual validation complete — all companies have been reviewed.

In [81]:
# Saving the completed manual-review table

manual_review.to_csv(manual_review_file, index=False)

print(f"Completed manual review saved to: {manual_review_file}")
print(f"Rows saved: {len(manual_review)}")

Completed manual review saved to: ..\data\manual_review_notes.csv
Rows saved: 20